defmodule ServiceRadar.Plugins.Validations.AssignmentParamsTest do
  @moduledoc """
  Guards the boundary between operator-supplied plugin config and the
  platform-generated policy envelope.

  A package `config_schema` describes the knobs an OPERATOR may set. The
  `serviceradar.plugin_inputs.v1` envelope is generated by the policy
  reconciler and is already validated, one step earlier in the same `with`,
  against `PluginInputs`' own closed schema. Running it through `config_schema`
  a second time is a category error: every package that sets
  `additionalProperties: false` then rejects its own materialized assignment.
  That is exactly how proxmox-inventory became unmaterializable when its
  manifest gained `additionalProperties: false`.

  The schema below is READ FROM THE MANIFEST rather than copied, so the
  manifest change that caused the outage would land in this test.
  """

  use ExUnit.Case, async: true

  alias Ash.Changeset
  alias ServiceRadar.Plugins.PluginAssignment
  alias ServiceRadar.Plugins.Validations.AssignmentParams

  @config_schema_path Path.expand(
                        "../../../../../../go/cmd/wasm-plugins/proxmox/config.schema.json",
                        __DIR__
                      )
  @external_resource @config_schema_path
  @strict_schema @config_schema_path |> File.read!() |> Jason.decode!()

  # What the credential parameter template actually renders for the
  # proxmox-inventory consumer. Four of these keys are NOT declared in
  # config.schema.json, which is why "just validate params[\"template\"]
  # instead" is not the fix -- it moves the failure, it does not remove it.
  @materialized_template %{
    "credential_broker" => %{
      "schema" => "serviceradar.edge_credential_broker_grant.v1",
      "grant_id" => "33333333-3333-4333-8333-333333333333",
      "grant_type" => "proxmox_api_token",
      "credential_rule_id" => "11111111-1111-4111-8111-111111111111"
    },
    "api_token_secret_ref" =>
      "credentialref:network-credential-secret:22222222-2222-4222-8222-222222222222",
    "credential_rule_id" => "11111111-1111-4111-8111-111111111111",
    "auto_discovery_enabled" => false,
    "include_guests" => true,
    "timeout_ms" => 30_000
  }

  defp policy_envelope(overrides \\ %{}) do
    Map.merge(
      %{
        "schema" => "serviceradar.plugin_inputs.v1",
        "policy_id" => "network-credential-rule:11111111-1111-4111-8111-111111111111",
        "policy_version" => 1_783_236_925,
        "agent_id" => "k8s-agent",
        "generated_at" => "2026-08-14T03:00:00.000000Z",
        "template" => @materialized_template,
        "inputs" => [
          %{
            "name" => "targets",
            "entity" => "devices",
            "query" => "in:devices metadata.proxmox_candidate:true",
            "chunk_index" => 0,
            "chunk_total" => 1,
            "chunk_hash" => String.duplicate("a", 64),
            "items" => [%{"uid" => "sr:097c9ba3", "ip" => "192.168.2.10", "hostname" => "pve01"}]
          }
        ]
      },
      overrides
    )
  end

  defp validate(params, opts \\ []) do
    PluginAssignment
    |> Changeset.new()
    |> Changeset.set_context(%{config_schema: @strict_schema})
    |> Changeset.force_change_attribute(:source, Keyword.get(opts, :source, :policy))
    |> Changeset.force_change_attribute(:params, params)
    |> AssignmentParams.validate([], %{})
  end

  test "accepts the materialized policy envelope against a strict package schema" do
    assert :ok = validate(policy_envelope())
  end

  test "rejects the same envelope on a manual assignment" do
    # Security boundary. ProxmoxHostAuthority reads the broker grant from
    # params["credential_broker"] OR params["template"]["credential_broker"],
    # and PluginInputs types "template" as a free-form object -- it constrains
    # nothing inside it. config_schema's additionalProperties:false is therefore
    # the only thing stopping a hand-written assignment from carrying a forged
    # grant. The carve-out must not extend to operator-created rows.
    assert {:error, error} = validate(policy_envelope(), source: :manual)
    assert error[:field] == :params
    assert error[:message] =~ "#/template"
  end

  test "still rejects an unknown operator key against a strict package schema" do
    assert {:error, error} = validate(%{"timeout_ms" => 30_000, "not_a_real_knob" => true})
    assert error[:field] == :params
    assert error[:message] =~ "not_a_real_knob"
  end

  test "still accepts plain operator params that satisfy the package schema" do
    assert :ok = validate(%{"timeout_ms" => 30_000, "include_guests" => false})
  end

  test "still rejects a malformed envelope" do
    # policy_version must be an integer >= 1 per PluginInputs' own schema. The
    # carve-out must not become a way to skip validation by presenting
    # something merely envelope-shaped.
    assert {:error, error} = validate(policy_envelope(%{"policy_version" => "not-an-integer"}))
    assert error[:field] == :params
  end

  test "rejects an envelope carrying an extra top-level key" do
    # Pins the PluginInputs additionalProperties:false invariant that makes the
    # dropped-key remainder provably empty: if the envelope could carry
    # arbitrary extra top-level keys, dropping the known ones would silently
    # exempt them from every schema.
    assert {:error, _error} = validate(policy_envelope(%{"rogue_knob" => 1}))
  end
end
