// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/carverauto/serviceradar/pkg/db (interfaces: Service,SysmonMetricsProvider,Rows,QueryExecutor)
//
// Generated by this command:
//
//	mockgen -destination=mock_db.go -package=db github.com/carverauto/serviceradar/pkg/db Service,SysmonMetricsProvider,Rows,QueryExecutor
//

// Package db is a generated GoMock package.
package db

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/carverauto/serviceradar/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// BatchGetDeviceIDsByIdentifier mocks base method.
func (m *MockService) BatchGetDeviceIDsByIdentifier(arg0 context.Context, arg1 string, arg2 []string, arg3 string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetDeviceIDsByIdentifier", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetDeviceIDsByIdentifier indicates an expected call of BatchGetDeviceIDsByIdentifier.
func (mr *MockServiceMockRecorder) BatchGetDeviceIDsByIdentifier(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetDeviceIDsByIdentifier", reflect.TypeOf((*MockService)(nil).BatchGetDeviceIDsByIdentifier), arg0, arg1, arg2, arg3)
}

// CleanupStaleOCSFDevices mocks base method.
func (m *MockService) CleanupStaleOCSFDevices(arg0 context.Context, arg1 time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupStaleOCSFDevices", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupStaleOCSFDevices indicates an expected call of CleanupStaleOCSFDevices.
func (mr *MockServiceMockRecorder) CleanupStaleOCSFDevices(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupStaleOCSFDevices", reflect.TypeOf((*MockService)(nil).CleanupStaleOCSFDevices), arg0, arg1)
}

// Close mocks base method.
func (m *MockService) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockService)(nil).Close))
}

// CountActiveSightings mocks base method.
func (m *MockService) CountActiveSightings(arg0 context.Context, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveSightings", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveSightings indicates an expected call of CountActiveSightings.
func (mr *MockServiceMockRecorder) CountActiveSightings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveSightings", reflect.TypeOf((*MockService)(nil).CountActiveSightings), arg0, arg1)
}

// CountOCSFDevices mocks base method.
func (m *MockService) CountOCSFDevices(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOCSFDevices", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOCSFDevices indicates an expected call of CountOCSFDevices.
func (mr *MockServiceMockRecorder) CountOCSFDevices(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOCSFDevices", reflect.TypeOf((*MockService)(nil).CountOCSFDevices), arg0)
}

// DeleteEdgeOnboardingPackage mocks base method.
func (m *MockService) DeleteEdgeOnboardingPackage(arg0 context.Context, arg1 *models.EdgeOnboardingPackage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdgeOnboardingPackage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEdgeOnboardingPackage indicates an expected call of DeleteEdgeOnboardingPackage.
func (mr *MockServiceMockRecorder) DeleteEdgeOnboardingPackage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdgeOnboardingPackage", reflect.TypeOf((*MockService)(nil).DeleteEdgeOnboardingPackage), arg0, arg1)
}

// DeleteOCSFDevices mocks base method.
func (m *MockService) DeleteOCSFDevices(arg0 context.Context, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOCSFDevices", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOCSFDevices indicates an expected call of DeleteOCSFDevices.
func (mr *MockServiceMockRecorder) DeleteOCSFDevices(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOCSFDevices", reflect.TypeOf((*MockService)(nil).DeleteOCSFDevices), arg0, arg1)
}

// DeletePoller mocks base method.
func (m *MockService) DeletePoller(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePoller", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePoller indicates an expected call of DeletePoller.
func (mr *MockServiceMockRecorder) DeletePoller(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePoller", reflect.TypeOf((*MockService)(nil).DeletePoller), arg0, arg1)
}

// ExecuteQuery mocks base method.
func (m *MockService) ExecuteQuery(arg0 context.Context, arg1 string, arg2 ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteQuery", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockServiceMockRecorder) ExecuteQuery(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockService)(nil).ExecuteQuery), varargs...)
}

// ExpireNetworkSightings mocks base method.
func (m *MockService) ExpireNetworkSightings(arg0 context.Context, arg1 time.Time) ([]*models.NetworkSighting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireNetworkSightings", arg0, arg1)
	ret0, _ := ret[0].([]*models.NetworkSighting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireNetworkSightings indicates an expected call of ExpireNetworkSightings.
func (mr *MockServiceMockRecorder) ExpireNetworkSightings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireNetworkSightings", reflect.TypeOf((*MockService)(nil).ExpireNetworkSightings), arg0, arg1)
}

// GetAllCPUMetrics mocks base method.
func (m *MockService) GetAllCPUMetrics(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.SysmonCPUResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCPUMetrics", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.SysmonCPUResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCPUMetrics indicates an expected call of GetAllCPUMetrics.
func (mr *MockServiceMockRecorder) GetAllCPUMetrics(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCPUMetrics", reflect.TypeOf((*MockService)(nil).GetAllCPUMetrics), arg0, arg1, arg2, arg3)
}

// GetAllDiskMetrics mocks base method.
func (m *MockService) GetAllDiskMetrics(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.DiskMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDiskMetrics", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.DiskMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDiskMetrics indicates an expected call of GetAllDiskMetrics.
func (mr *MockServiceMockRecorder) GetAllDiskMetrics(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDiskMetrics", reflect.TypeOf((*MockService)(nil).GetAllDiskMetrics), arg0, arg1, arg2, arg3)
}

// GetAllDiskMetricsGrouped mocks base method.
func (m *MockService) GetAllDiskMetricsGrouped(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.SysmonDiskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDiskMetricsGrouped", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.SysmonDiskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDiskMetricsGrouped indicates an expected call of GetAllDiskMetricsGrouped.
func (mr *MockServiceMockRecorder) GetAllDiskMetricsGrouped(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDiskMetricsGrouped", reflect.TypeOf((*MockService)(nil).GetAllDiskMetricsGrouped), arg0, arg1, arg2, arg3)
}

// GetAllMountPoints mocks base method.
func (m *MockService) GetAllMountPoints(arg0 context.Context, arg1 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMountPoints", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMountPoints indicates an expected call of GetAllMountPoints.
func (mr *MockServiceMockRecorder) GetAllMountPoints(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMountPoints", reflect.TypeOf((*MockService)(nil).GetAllMountPoints), arg0, arg1)
}

// GetAllProcessMetrics mocks base method.
func (m *MockService) GetAllProcessMetrics(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.ProcessMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProcessMetrics", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.ProcessMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProcessMetrics indicates an expected call of GetAllProcessMetrics.
func (mr *MockServiceMockRecorder) GetAllProcessMetrics(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProcessMetrics", reflect.TypeOf((*MockService)(nil).GetAllProcessMetrics), arg0, arg1, arg2, arg3)
}

// GetAllProcessMetricsGrouped mocks base method.
func (m *MockService) GetAllProcessMetricsGrouped(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.SysmonProcessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProcessMetricsGrouped", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.SysmonProcessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProcessMetricsGrouped indicates an expected call of GetAllProcessMetricsGrouped.
func (mr *MockServiceMockRecorder) GetAllProcessMetricsGrouped(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProcessMetricsGrouped", reflect.TypeOf((*MockService)(nil).GetAllProcessMetricsGrouped), arg0, arg1, arg2, arg3)
}

// GetCPUMetrics mocks base method.
func (m *MockService) GetCPUMetrics(arg0 context.Context, arg1 string, arg2 int, arg3, arg4 time.Time) ([]models.CPUMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCPUMetrics", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.CPUMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCPUMetrics indicates an expected call of GetCPUMetrics.
func (mr *MockServiceMockRecorder) GetCPUMetrics(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCPUMetrics", reflect.TypeOf((*MockService)(nil).GetCPUMetrics), arg0, arg1, arg2, arg3, arg4)
}

// GetDeviceByID mocks base method.
func (m *MockService) GetDeviceByID(arg0 context.Context, arg1 string) (*models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByID indicates an expected call of GetDeviceByID.
func (mr *MockServiceMockRecorder) GetDeviceByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByID", reflect.TypeOf((*MockService)(nil).GetDeviceByID), arg0, arg1)
}

// GetDeviceIDByIdentifier mocks base method.
func (m *MockService) GetDeviceIDByIdentifier(arg0 context.Context, arg1, arg2, arg3 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceIDByIdentifier", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceIDByIdentifier indicates an expected call of GetDeviceIDByIdentifier.
func (mr *MockServiceMockRecorder) GetDeviceIDByIdentifier(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceIDByIdentifier", reflect.TypeOf((*MockService)(nil).GetDeviceIDByIdentifier), arg0, arg1, arg2, arg3)
}

// GetDeviceMetricTypes mocks base method.
func (m *MockService) GetDeviceMetricTypes(arg0 context.Context, arg1 []string, arg2 time.Time) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMetricTypes", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceMetricTypes indicates an expected call of GetDeviceMetricTypes.
func (mr *MockServiceMockRecorder) GetDeviceMetricTypes(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMetricTypes", reflect.TypeOf((*MockService)(nil).GetDeviceMetricTypes), arg0, arg1, arg2)
}

// GetDevicesByIP mocks base method.
func (m *MockService) GetDevicesByIP(arg0 context.Context, arg1 string) ([]*models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicesByIP", arg0, arg1)
	ret0, _ := ret[0].([]*models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicesByIP indicates an expected call of GetDevicesByIP.
func (mr *MockServiceMockRecorder) GetDevicesByIP(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicesByIP", reflect.TypeOf((*MockService)(nil).GetDevicesByIP), arg0, arg1)
}

// GetDevicesWithRecentSNMPMetrics mocks base method.
func (m *MockService) GetDevicesWithRecentSNMPMetrics(arg0 context.Context, arg1 []string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicesWithRecentSNMPMetrics", arg0, arg1)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicesWithRecentSNMPMetrics indicates an expected call of GetDevicesWithRecentSNMPMetrics.
func (mr *MockServiceMockRecorder) GetDevicesWithRecentSNMPMetrics(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicesWithRecentSNMPMetrics", reflect.TypeOf((*MockService)(nil).GetDevicesWithRecentSNMPMetrics), arg0, arg1)
}

// GetDiskMetrics mocks base method.
func (m *MockService) GetDiskMetrics(arg0 context.Context, arg1, arg2 string, arg3, arg4 time.Time) ([]models.DiskMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiskMetrics", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.DiskMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiskMetrics indicates an expected call of GetDiskMetrics.
func (mr *MockServiceMockRecorder) GetDiskMetrics(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiskMetrics", reflect.TypeOf((*MockService)(nil).GetDiskMetrics), arg0, arg1, arg2, arg3, arg4)
}

// GetEdgeOnboardingPackage mocks base method.
func (m *MockService) GetEdgeOnboardingPackage(arg0 context.Context, arg1 string) (*models.EdgeOnboardingPackage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEdgeOnboardingPackage", arg0, arg1)
	ret0, _ := ret[0].(*models.EdgeOnboardingPackage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEdgeOnboardingPackage indicates an expected call of GetEdgeOnboardingPackage.
func (mr *MockServiceMockRecorder) GetEdgeOnboardingPackage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEdgeOnboardingPackage", reflect.TypeOf((*MockService)(nil).GetEdgeOnboardingPackage), arg0, arg1)
}

// GetICMPMetricsForDevice mocks base method.
func (m *MockService) GetICMPMetricsForDevice(arg0 context.Context, arg1, arg2 string, arg3, arg4 time.Time) ([]models.TimeseriesMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetICMPMetricsForDevice", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.TimeseriesMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetICMPMetricsForDevice indicates an expected call of GetICMPMetricsForDevice.
func (mr *MockServiceMockRecorder) GetICMPMetricsForDevice(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetICMPMetricsForDevice", reflect.TypeOf((*MockService)(nil).GetICMPMetricsForDevice), arg0, arg1, arg2, arg3, arg4)
}

// GetMemoryMetrics mocks base method.
func (m *MockService) GetMemoryMetrics(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.MemoryMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemoryMetrics", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.MemoryMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemoryMetrics indicates an expected call of GetMemoryMetrics.
func (mr *MockServiceMockRecorder) GetMemoryMetrics(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemoryMetrics", reflect.TypeOf((*MockService)(nil).GetMemoryMetrics), arg0, arg1, arg2, arg3)
}

// GetMemoryMetricsGrouped mocks base method.
func (m *MockService) GetMemoryMetricsGrouped(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.SysmonMemoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemoryMetricsGrouped", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.SysmonMemoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemoryMetricsGrouped indicates an expected call of GetMemoryMetricsGrouped.
func (mr *MockServiceMockRecorder) GetMemoryMetricsGrouped(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemoryMetricsGrouped", reflect.TypeOf((*MockService)(nil).GetMemoryMetricsGrouped), arg0, arg1, arg2, arg3)
}

// GetMetrics mocks base method.
func (m *MockService) GetMetrics(arg0 context.Context, arg1, arg2 string, arg3, arg4 time.Time) ([]models.TimeseriesMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.TimeseriesMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockServiceMockRecorder) GetMetrics(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockService)(nil).GetMetrics), arg0, arg1, arg2, arg3, arg4)
}

// GetMetricsByType mocks base method.
func (m *MockService) GetMetricsByType(arg0 context.Context, arg1, arg2 string, arg3, arg4 time.Time) ([]models.TimeseriesMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsByType", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.TimeseriesMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsByType indicates an expected call of GetMetricsByType.
func (mr *MockServiceMockRecorder) GetMetricsByType(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsByType", reflect.TypeOf((*MockService)(nil).GetMetricsByType), arg0, arg1, arg2, arg3, arg4)
}

// GetMetricsForDevice mocks base method.
func (m *MockService) GetMetricsForDevice(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.TimeseriesMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsForDevice", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.TimeseriesMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsForDevice indicates an expected call of GetMetricsForDevice.
func (mr *MockServiceMockRecorder) GetMetricsForDevice(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsForDevice", reflect.TypeOf((*MockService)(nil).GetMetricsForDevice), arg0, arg1, arg2, arg3)
}

// GetMetricsForDeviceByType mocks base method.
func (m *MockService) GetMetricsForDeviceByType(arg0 context.Context, arg1, arg2 string, arg3, arg4 time.Time) ([]models.TimeseriesMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsForDeviceByType", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.TimeseriesMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsForDeviceByType indicates an expected call of GetMetricsForDeviceByType.
func (mr *MockServiceMockRecorder) GetMetricsForDeviceByType(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsForDeviceByType", reflect.TypeOf((*MockService)(nil).GetMetricsForDeviceByType), arg0, arg1, arg2, arg3, arg4)
}

// GetMetricsForPartition mocks base method.
func (m *MockService) GetMetricsForPartition(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.TimeseriesMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsForPartition", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.TimeseriesMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsForPartition indicates an expected call of GetMetricsForPartition.
func (mr *MockServiceMockRecorder) GetMetricsForPartition(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsForPartition", reflect.TypeOf((*MockService)(nil).GetMetricsForPartition), arg0, arg1, arg2, arg3)
}

// GetNetworkSighting mocks base method.
func (m *MockService) GetNetworkSighting(arg0 context.Context, arg1 string) (*models.NetworkSighting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkSighting", arg0, arg1)
	ret0, _ := ret[0].(*models.NetworkSighting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkSighting indicates an expected call of GetNetworkSighting.
func (mr *MockServiceMockRecorder) GetNetworkSighting(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkSighting", reflect.TypeOf((*MockService)(nil).GetNetworkSighting), arg0, arg1)
}

// GetOCSFDevice mocks base method.
func (m *MockService) GetOCSFDevice(arg0 context.Context, arg1 string) (*models.OCSFDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCSFDevice", arg0, arg1)
	ret0, _ := ret[0].(*models.OCSFDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOCSFDevice indicates an expected call of GetOCSFDevice.
func (mr *MockServiceMockRecorder) GetOCSFDevice(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCSFDevice", reflect.TypeOf((*MockService)(nil).GetOCSFDevice), arg0, arg1)
}

// GetOCSFDevicesByIP mocks base method.
func (m *MockService) GetOCSFDevicesByIP(arg0 context.Context, arg1 string) ([]*models.OCSFDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCSFDevicesByIP", arg0, arg1)
	ret0, _ := ret[0].([]*models.OCSFDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOCSFDevicesByIP indicates an expected call of GetOCSFDevicesByIP.
func (mr *MockServiceMockRecorder) GetOCSFDevicesByIP(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCSFDevicesByIP", reflect.TypeOf((*MockService)(nil).GetOCSFDevicesByIP), arg0, arg1)
}

// GetOCSFDevicesByIPsOrIDs mocks base method.
func (m *MockService) GetOCSFDevicesByIPsOrIDs(arg0 context.Context, arg1, arg2 []string) ([]*models.OCSFDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCSFDevicesByIPsOrIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.OCSFDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOCSFDevicesByIPsOrIDs indicates an expected call of GetOCSFDevicesByIPsOrIDs.
func (mr *MockServiceMockRecorder) GetOCSFDevicesByIPsOrIDs(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCSFDevicesByIPsOrIDs", reflect.TypeOf((*MockService)(nil).GetOCSFDevicesByIPsOrIDs), arg0, arg1, arg2)
}

// GetPollerHistory mocks base method.
func (m *MockService) GetPollerHistory(arg0 context.Context, arg1 string) ([]models.PollerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPollerHistory", arg0, arg1)
	ret0, _ := ret[0].([]models.PollerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPollerHistory indicates an expected call of GetPollerHistory.
func (mr *MockServiceMockRecorder) GetPollerHistory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPollerHistory", reflect.TypeOf((*MockService)(nil).GetPollerHistory), arg0, arg1)
}

// GetPollerHistoryPoints mocks base method.
func (m *MockService) GetPollerHistoryPoints(arg0 context.Context, arg1 string, arg2 int) ([]models.PollerHistoryPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPollerHistoryPoints", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.PollerHistoryPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPollerHistoryPoints indicates an expected call of GetPollerHistoryPoints.
func (mr *MockServiceMockRecorder) GetPollerHistoryPoints(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPollerHistoryPoints", reflect.TypeOf((*MockService)(nil).GetPollerHistoryPoints), arg0, arg1, arg2)
}

// GetPollerServices mocks base method.
func (m *MockService) GetPollerServices(arg0 context.Context, arg1 string) ([]models.ServiceStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPollerServices", arg0, arg1)
	ret0, _ := ret[0].([]models.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPollerServices indicates an expected call of GetPollerServices.
func (mr *MockServiceMockRecorder) GetPollerServices(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPollerServices", reflect.TypeOf((*MockService)(nil).GetPollerServices), arg0, arg1)
}

// GetPollerStatus mocks base method.
func (m *MockService) GetPollerStatus(arg0 context.Context, arg1 string) (*models.PollerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPollerStatus", arg0, arg1)
	ret0, _ := ret[0].(*models.PollerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPollerStatus indicates an expected call of GetPollerStatus.
func (mr *MockServiceMockRecorder) GetPollerStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPollerStatus", reflect.TypeOf((*MockService)(nil).GetPollerStatus), arg0, arg1)
}

// GetServiceHistory mocks base method.
func (m *MockService) GetServiceHistory(arg0 context.Context, arg1, arg2 string, arg3 int) ([]models.ServiceStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceHistory", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceHistory indicates an expected call of GetServiceHistory.
func (mr *MockServiceMockRecorder) GetServiceHistory(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceHistory", reflect.TypeOf((*MockService)(nil).GetServiceHistory), arg0, arg1, arg2, arg3)
}

// GetStaleIPOnlyDevices mocks base method.
func (m *MockService) GetStaleIPOnlyDevices(arg0 context.Context, arg1 time.Duration) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaleIPOnlyDevices", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaleIPOnlyDevices indicates an expected call of GetStaleIPOnlyDevices.
func (mr *MockServiceMockRecorder) GetStaleIPOnlyDevices(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaleIPOnlyDevices", reflect.TypeOf((*MockService)(nil).GetStaleIPOnlyDevices), arg0, arg1)
}

// GetSweepHostStates mocks base method.
func (m *MockService) GetSweepHostStates(arg0 context.Context, arg1 string, arg2 int) ([]*models.SweepHostState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSweepHostStates", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.SweepHostState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSweepHostStates indicates an expected call of GetSweepHostStates.
func (mr *MockServiceMockRecorder) GetSweepHostStates(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSweepHostStates", reflect.TypeOf((*MockService)(nil).GetSweepHostStates), arg0, arg1, arg2)
}

// GetUserByID mocks base method.
func (m *MockService) GetUserByID(arg0 context.Context, arg1 string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockServiceMockRecorder) GetUserByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockService)(nil).GetUserByID), arg0, arg1)
}

// InsertEdgeOnboardingEvent mocks base method.
func (m *MockService) InsertEdgeOnboardingEvent(arg0 context.Context, arg1 *models.EdgeOnboardingEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEdgeOnboardingEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEdgeOnboardingEvent indicates an expected call of InsertEdgeOnboardingEvent.
func (mr *MockServiceMockRecorder) InsertEdgeOnboardingEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEdgeOnboardingEvent", reflect.TypeOf((*MockService)(nil).InsertEdgeOnboardingEvent), arg0, arg1)
}

// InsertSightingEvents mocks base method.
func (m *MockService) InsertSightingEvents(arg0 context.Context, arg1 []*models.SightingEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSightingEvents", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSightingEvents indicates an expected call of InsertSightingEvents.
func (mr *MockServiceMockRecorder) InsertSightingEvents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSightingEvents", reflect.TypeOf((*MockService)(nil).InsertSightingEvents), arg0, arg1)
}

// IsPollerOffline mocks base method.
func (m *MockService) IsPollerOffline(arg0 context.Context, arg1 string, arg2 time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPollerOffline", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPollerOffline indicates an expected call of IsPollerOffline.
func (mr *MockServiceMockRecorder) IsPollerOffline(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPollerOffline", reflect.TypeOf((*MockService)(nil).IsPollerOffline), arg0, arg1, arg2)
}

// ListActiveSightings mocks base method.
func (m *MockService) ListActiveSightings(arg0 context.Context, arg1 string, arg2, arg3 int) ([]*models.NetworkSighting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveSightings", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*models.NetworkSighting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveSightings indicates an expected call of ListActiveSightings.
func (mr *MockServiceMockRecorder) ListActiveSightings(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveSightings", reflect.TypeOf((*MockService)(nil).ListActiveSightings), arg0, arg1, arg2, arg3)
}

// ListAgentsByPoller mocks base method.
func (m *MockService) ListAgentsByPoller(arg0 context.Context, arg1 string) ([]AgentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentsByPoller", arg0, arg1)
	ret0, _ := ret[0].([]AgentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgentsByPoller indicates an expected call of ListAgentsByPoller.
func (mr *MockServiceMockRecorder) ListAgentsByPoller(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentsByPoller", reflect.TypeOf((*MockService)(nil).ListAgentsByPoller), arg0, arg1)
}

// ListAgentsWithPollers mocks base method.
func (m *MockService) ListAgentsWithPollers(arg0 context.Context) ([]AgentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentsWithPollers", arg0)
	ret0, _ := ret[0].([]AgentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgentsWithPollers indicates an expected call of ListAgentsWithPollers.
func (mr *MockServiceMockRecorder) ListAgentsWithPollers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentsWithPollers", reflect.TypeOf((*MockService)(nil).ListAgentsWithPollers), arg0)
}

// ListEdgeOnboardingEvents mocks base method.
func (m *MockService) ListEdgeOnboardingEvents(arg0 context.Context, arg1 string, arg2 int) ([]*models.EdgeOnboardingEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEdgeOnboardingEvents", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.EdgeOnboardingEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEdgeOnboardingEvents indicates an expected call of ListEdgeOnboardingEvents.
func (mr *MockServiceMockRecorder) ListEdgeOnboardingEvents(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEdgeOnboardingEvents", reflect.TypeOf((*MockService)(nil).ListEdgeOnboardingEvents), arg0, arg1, arg2)
}

// ListEdgeOnboardingPackages mocks base method.
func (m *MockService) ListEdgeOnboardingPackages(arg0 context.Context, arg1 *models.EdgeOnboardingListFilter) ([]*models.EdgeOnboardingPackage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEdgeOnboardingPackages", arg0, arg1)
	ret0, _ := ret[0].([]*models.EdgeOnboardingPackage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEdgeOnboardingPackages indicates an expected call of ListEdgeOnboardingPackages.
func (mr *MockServiceMockRecorder) ListEdgeOnboardingPackages(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEdgeOnboardingPackages", reflect.TypeOf((*MockService)(nil).ListEdgeOnboardingPackages), arg0, arg1)
}

// ListEdgeOnboardingPollerIDs mocks base method.
func (m *MockService) ListEdgeOnboardingPollerIDs(arg0 context.Context, arg1 ...models.EdgeOnboardingStatus) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListEdgeOnboardingPollerIDs", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEdgeOnboardingPollerIDs indicates an expected call of ListEdgeOnboardingPollerIDs.
func (mr *MockServiceMockRecorder) ListEdgeOnboardingPollerIDs(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEdgeOnboardingPollerIDs", reflect.TypeOf((*MockService)(nil).ListEdgeOnboardingPollerIDs), varargs...)
}

// ListMergeAuditEvents mocks base method.
func (m *MockService) ListMergeAuditEvents(arg0 context.Context, arg1 string, arg2 int) ([]*models.MergeAuditEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMergeAuditEvents", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.MergeAuditEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMergeAuditEvents indicates an expected call of ListMergeAuditEvents.
func (mr *MockServiceMockRecorder) ListMergeAuditEvents(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMergeAuditEvents", reflect.TypeOf((*MockService)(nil).ListMergeAuditEvents), arg0, arg1, arg2)
}

// ListNeverReportedPollers mocks base method.
func (m *MockService) ListNeverReportedPollers(arg0 context.Context, arg1 []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNeverReportedPollers", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNeverReportedPollers indicates an expected call of ListNeverReportedPollers.
func (mr *MockServiceMockRecorder) ListNeverReportedPollers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNeverReportedPollers", reflect.TypeOf((*MockService)(nil).ListNeverReportedPollers), arg0, arg1)
}

// ListOCSFDevices mocks base method.
func (m *MockService) ListOCSFDevices(arg0 context.Context, arg1, arg2 int) ([]*models.OCSFDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOCSFDevices", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.OCSFDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOCSFDevices indicates an expected call of ListOCSFDevices.
func (mr *MockServiceMockRecorder) ListOCSFDevices(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOCSFDevices", reflect.TypeOf((*MockService)(nil).ListOCSFDevices), arg0, arg1, arg2)
}

// ListOCSFDevicesByType mocks base method.
func (m *MockService) ListOCSFDevicesByType(arg0 context.Context, arg1, arg2, arg3 int) ([]*models.OCSFDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOCSFDevicesByType", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*models.OCSFDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOCSFDevicesByType indicates an expected call of ListOCSFDevicesByType.
func (mr *MockServiceMockRecorder) ListOCSFDevicesByType(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOCSFDevicesByType", reflect.TypeOf((*MockService)(nil).ListOCSFDevicesByType), arg0, arg1, arg2, arg3)
}

// ListPollerStatuses mocks base method.
func (m *MockService) ListPollerStatuses(arg0 context.Context, arg1 []string) ([]models.PollerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPollerStatuses", arg0, arg1)
	ret0, _ := ret[0].([]models.PollerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPollerStatuses indicates an expected call of ListPollerStatuses.
func (mr *MockServiceMockRecorder) ListPollerStatuses(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPollerStatuses", reflect.TypeOf((*MockService)(nil).ListPollerStatuses), arg0, arg1)
}

// ListPollers mocks base method.
func (m *MockService) ListPollers(arg0 context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPollers", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPollers indicates an expected call of ListPollers.
func (mr *MockServiceMockRecorder) ListPollers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPollers", reflect.TypeOf((*MockService)(nil).ListPollers), arg0)
}

// ListPromotableSightings mocks base method.
func (m *MockService) ListPromotableSightings(arg0 context.Context, arg1 time.Time) ([]*models.NetworkSighting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPromotableSightings", arg0, arg1)
	ret0, _ := ret[0].([]*models.NetworkSighting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPromotableSightings indicates an expected call of ListPromotableSightings.
func (mr *MockServiceMockRecorder) ListPromotableSightings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPromotableSightings", reflect.TypeOf((*MockService)(nil).ListPromotableSightings), arg0, arg1)
}

// ListSightingEvents mocks base method.
func (m *MockService) ListSightingEvents(arg0 context.Context, arg1 string, arg2 int) ([]*models.SightingEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSightingEvents", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.SightingEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSightingEvents indicates an expected call of ListSightingEvents.
func (mr *MockServiceMockRecorder) ListSightingEvents(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSightingEvents", reflect.TypeOf((*MockService)(nil).ListSightingEvents), arg0, arg1, arg2)
}

// ListSubnetPolicies mocks base method.
func (m *MockService) ListSubnetPolicies(arg0 context.Context, arg1 int) ([]*models.SubnetPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubnetPolicies", arg0, arg1)
	ret0, _ := ret[0].([]*models.SubnetPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubnetPolicies indicates an expected call of ListSubnetPolicies.
func (mr *MockServiceMockRecorder) ListSubnetPolicies(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubnetPolicies", reflect.TypeOf((*MockService)(nil).ListSubnetPolicies), arg0, arg1)
}

// LockOCSFDevices mocks base method.
func (m *MockService) LockOCSFDevices(arg0 context.Context, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockOCSFDevices", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockOCSFDevices indicates an expected call of LockOCSFDevices.
func (mr *MockServiceMockRecorder) LockOCSFDevices(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockOCSFDevices", reflect.TypeOf((*MockService)(nil).LockOCSFDevices), arg0, arg1)
}

// MarkSightingsPromoted mocks base method.
func (m *MockService) MarkSightingsPromoted(arg0 context.Context, arg1 []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSightingsPromoted", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkSightingsPromoted indicates an expected call of MarkSightingsPromoted.
func (mr *MockServiceMockRecorder) MarkSightingsPromoted(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSightingsPromoted", reflect.TypeOf((*MockService)(nil).MarkSightingsPromoted), arg0, arg1)
}

// PublishBatchDeviceUpdates mocks base method.
func (m *MockService) PublishBatchDeviceUpdates(arg0 context.Context, arg1 []*models.DeviceUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBatchDeviceUpdates", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBatchDeviceUpdates indicates an expected call of PublishBatchDeviceUpdates.
func (mr *MockServiceMockRecorder) PublishBatchDeviceUpdates(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBatchDeviceUpdates", reflect.TypeOf((*MockService)(nil).PublishBatchDeviceUpdates), arg0, arg1)
}

// PublishBatchDiscoveredInterfaces mocks base method.
func (m *MockService) PublishBatchDiscoveredInterfaces(arg0 context.Context, arg1 []*models.DiscoveredInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBatchDiscoveredInterfaces", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBatchDiscoveredInterfaces indicates an expected call of PublishBatchDiscoveredInterfaces.
func (mr *MockServiceMockRecorder) PublishBatchDiscoveredInterfaces(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBatchDiscoveredInterfaces", reflect.TypeOf((*MockService)(nil).PublishBatchDiscoveredInterfaces), arg0, arg1)
}

// PublishBatchTopologyDiscoveryEvents mocks base method.
func (m *MockService) PublishBatchTopologyDiscoveryEvents(arg0 context.Context, arg1 []*models.TopologyDiscoveryEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBatchTopologyDiscoveryEvents", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBatchTopologyDiscoveryEvents indicates an expected call of PublishBatchTopologyDiscoveryEvents.
func (mr *MockServiceMockRecorder) PublishBatchTopologyDiscoveryEvents(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBatchTopologyDiscoveryEvents", reflect.TypeOf((*MockService)(nil).PublishBatchTopologyDiscoveryEvents), arg0, arg1)
}

// PublishDeviceUpdate mocks base method.
func (m *MockService) PublishDeviceUpdate(arg0 context.Context, arg1 *models.DeviceUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDeviceUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDeviceUpdate indicates an expected call of PublishDeviceUpdate.
func (mr *MockServiceMockRecorder) PublishDeviceUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeviceUpdate", reflect.TypeOf((*MockService)(nil).PublishDeviceUpdate), arg0, arg1)
}

// PublishDiscoveredInterface mocks base method.
func (m *MockService) PublishDiscoveredInterface(arg0 context.Context, arg1 *models.DiscoveredInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDiscoveredInterface", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDiscoveredInterface indicates an expected call of PublishDiscoveredInterface.
func (mr *MockServiceMockRecorder) PublishDiscoveredInterface(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDiscoveredInterface", reflect.TypeOf((*MockService)(nil).PublishDiscoveredInterface), arg0, arg1)
}

// PublishTopologyDiscoveryEvent mocks base method.
func (m *MockService) PublishTopologyDiscoveryEvent(arg0 context.Context, arg1 *models.TopologyDiscoveryEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTopologyDiscoveryEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTopologyDiscoveryEvent indicates an expected call of PublishTopologyDiscoveryEvent.
func (mr *MockServiceMockRecorder) PublishTopologyDiscoveryEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTopologyDiscoveryEvent", reflect.TypeOf((*MockService)(nil).PublishTopologyDiscoveryEvent), arg0, arg1)
}

// SoftDeleteDevices mocks base method.
func (m *MockService) SoftDeleteDevices(arg0 context.Context, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteDevices", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteDevices indicates an expected call of SoftDeleteDevices.
func (mr *MockServiceMockRecorder) SoftDeleteDevices(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteDevices", reflect.TypeOf((*MockService)(nil).SoftDeleteDevices), arg0, arg1)
}

// StoreMetric mocks base method.
func (m *MockService) StoreMetric(arg0 context.Context, arg1 string, arg2 *models.TimeseriesMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreMetric", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreMetric indicates an expected call of StoreMetric.
func (mr *MockServiceMockRecorder) StoreMetric(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMetric", reflect.TypeOf((*MockService)(nil).StoreMetric), arg0, arg1, arg2)
}

// StoreMetrics mocks base method.
func (m *MockService) StoreMetrics(arg0 context.Context, arg1 string, arg2 []*models.TimeseriesMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreMetrics", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreMetrics indicates an expected call of StoreMetrics.
func (mr *MockServiceMockRecorder) StoreMetrics(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMetrics", reflect.TypeOf((*MockService)(nil).StoreMetrics), arg0, arg1, arg2)
}

// StoreNetflowMetrics mocks base method.
func (m *MockService) StoreNetflowMetrics(arg0 context.Context, arg1 []*models.NetflowMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreNetflowMetrics", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreNetflowMetrics indicates an expected call of StoreNetflowMetrics.
func (mr *MockServiceMockRecorder) StoreNetflowMetrics(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreNetflowMetrics", reflect.TypeOf((*MockService)(nil).StoreNetflowMetrics), arg0, arg1)
}

// StoreRperfMetrics mocks base method.
func (m *MockService) StoreRperfMetrics(arg0 context.Context, arg1, arg2, arg3 string, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRperfMetrics", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRperfMetrics indicates an expected call of StoreRperfMetrics.
func (mr *MockServiceMockRecorder) StoreRperfMetrics(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRperfMetrics", reflect.TypeOf((*MockService)(nil).StoreRperfMetrics), arg0, arg1, arg2, arg3, arg4)
}

// StoreServices mocks base method.
func (m *MockService) StoreServices(arg0 context.Context, arg1 []*models.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreServices", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreServices indicates an expected call of StoreServices.
func (mr *MockServiceMockRecorder) StoreServices(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreServices", reflect.TypeOf((*MockService)(nil).StoreServices), arg0, arg1)
}

// StoreSweepHostStates mocks base method.
func (m *MockService) StoreSweepHostStates(arg0 context.Context, arg1 []*models.SweepHostState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreSweepHostStates", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreSweepHostStates indicates an expected call of StoreSweepHostStates.
func (mr *MockServiceMockRecorder) StoreSweepHostStates(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreSweepHostStates", reflect.TypeOf((*MockService)(nil).StoreSweepHostStates), arg0, arg1)
}

// StoreSysmonMetrics mocks base method.
func (m *MockService) StoreSysmonMetrics(arg0 context.Context, arg1, arg2, arg3, arg4, arg5, arg6 string, arg7 *models.SysmonMetrics, arg8 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreSysmonMetrics", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreSysmonMetrics indicates an expected call of StoreSysmonMetrics.
func (mr *MockServiceMockRecorder) StoreSysmonMetrics(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreSysmonMetrics", reflect.TypeOf((*MockService)(nil).StoreSysmonMetrics), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
}

// StoreUser mocks base method.
func (m *MockService) StoreUser(arg0 context.Context, arg1 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreUser indicates an expected call of StoreUser.
func (mr *MockServiceMockRecorder) StoreUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreUser", reflect.TypeOf((*MockService)(nil).StoreUser), arg0, arg1)
}

// UpdatePollerStatus mocks base method.
func (m *MockService) UpdatePollerStatus(arg0 context.Context, arg1 *models.PollerStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePollerStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePollerStatus indicates an expected call of UpdatePollerStatus.
func (mr *MockServiceMockRecorder) UpdatePollerStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePollerStatus", reflect.TypeOf((*MockService)(nil).UpdatePollerStatus), arg0, arg1)
}

// UpdateServiceStatus mocks base method.
func (m *MockService) UpdateServiceStatus(arg0 context.Context, arg1 *models.ServiceStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceStatus indicates an expected call of UpdateServiceStatus.
func (mr *MockServiceMockRecorder) UpdateServiceStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceStatus", reflect.TypeOf((*MockService)(nil).UpdateServiceStatus), arg0, arg1)
}

// UpdateServiceStatuses mocks base method.
func (m *MockService) UpdateServiceStatuses(arg0 context.Context, arg1 []*models.ServiceStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceStatuses", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceStatuses indicates an expected call of UpdateServiceStatuses.
func (mr *MockServiceMockRecorder) UpdateServiceStatuses(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceStatuses", reflect.TypeOf((*MockService)(nil).UpdateServiceStatuses), arg0, arg1)
}

// UpdateSightingStatus mocks base method.
func (m *MockService) UpdateSightingStatus(arg0 context.Context, arg1 string, arg2 models.NetworkSightingStatus) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSightingStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSightingStatus indicates an expected call of UpdateSightingStatus.
func (mr *MockServiceMockRecorder) UpdateSightingStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSightingStatus", reflect.TypeOf((*MockService)(nil).UpdateSightingStatus), arg0, arg1, arg2)
}

// UpsertDeviceIdentifiers mocks base method.
func (m *MockService) UpsertDeviceIdentifiers(arg0 context.Context, arg1 []*models.DeviceIdentifier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDeviceIdentifiers", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDeviceIdentifiers indicates an expected call of UpsertDeviceIdentifiers.
func (mr *MockServiceMockRecorder) UpsertDeviceIdentifiers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDeviceIdentifiers", reflect.TypeOf((*MockService)(nil).UpsertDeviceIdentifiers), arg0, arg1)
}

// UpsertEdgeOnboardingPackage mocks base method.
func (m *MockService) UpsertEdgeOnboardingPackage(arg0 context.Context, arg1 *models.EdgeOnboardingPackage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEdgeOnboardingPackage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEdgeOnboardingPackage indicates an expected call of UpsertEdgeOnboardingPackage.
func (mr *MockServiceMockRecorder) UpsertEdgeOnboardingPackage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEdgeOnboardingPackage", reflect.TypeOf((*MockService)(nil).UpsertEdgeOnboardingPackage), arg0, arg1)
}

// UpsertOCSFDevice mocks base method.
func (m *MockService) UpsertOCSFDevice(arg0 context.Context, arg1 *models.OCSFDevice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertOCSFDevice", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertOCSFDevice indicates an expected call of UpsertOCSFDevice.
func (mr *MockServiceMockRecorder) UpsertOCSFDevice(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertOCSFDevice", reflect.TypeOf((*MockService)(nil).UpsertOCSFDevice), arg0, arg1)
}

// UpsertOCSFDeviceBatch mocks base method.
func (m *MockService) UpsertOCSFDeviceBatch(arg0 context.Context, arg1 []*models.OCSFDevice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertOCSFDeviceBatch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertOCSFDeviceBatch indicates an expected call of UpsertOCSFDeviceBatch.
func (mr *MockServiceMockRecorder) UpsertOCSFDeviceBatch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertOCSFDeviceBatch", reflect.TypeOf((*MockService)(nil).UpsertOCSFDeviceBatch), arg0, arg1)
}

// WithTx mocks base method.
func (m *MockService) WithTx(arg0 context.Context, arg1 func(Service) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockServiceMockRecorder) WithTx(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockService)(nil).WithTx), arg0, arg1)
}

// MockSysmonMetricsProvider is a mock of SysmonMetricsProvider interface.
type MockSysmonMetricsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSysmonMetricsProviderMockRecorder
}

// MockSysmonMetricsProviderMockRecorder is the mock recorder for MockSysmonMetricsProvider.
type MockSysmonMetricsProviderMockRecorder struct {
	mock *MockSysmonMetricsProvider
}

// NewMockSysmonMetricsProvider creates a new mock instance.
func NewMockSysmonMetricsProvider(ctrl *gomock.Controller) *MockSysmonMetricsProvider {
	mock := &MockSysmonMetricsProvider{ctrl: ctrl}
	mock.recorder = &MockSysmonMetricsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSysmonMetricsProvider) EXPECT() *MockSysmonMetricsProviderMockRecorder {
	return m.recorder
}

// GetAllCPUMetrics mocks base method.
func (m *MockSysmonMetricsProvider) GetAllCPUMetrics(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.SysmonCPUResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCPUMetrics", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.SysmonCPUResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCPUMetrics indicates an expected call of GetAllCPUMetrics.
func (mr *MockSysmonMetricsProviderMockRecorder) GetAllCPUMetrics(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCPUMetrics", reflect.TypeOf((*MockSysmonMetricsProvider)(nil).GetAllCPUMetrics), arg0, arg1, arg2, arg3)
}

// GetAllDiskMetrics mocks base method.
func (m *MockSysmonMetricsProvider) GetAllDiskMetrics(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.DiskMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDiskMetrics", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.DiskMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDiskMetrics indicates an expected call of GetAllDiskMetrics.
func (mr *MockSysmonMetricsProviderMockRecorder) GetAllDiskMetrics(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDiskMetrics", reflect.TypeOf((*MockSysmonMetricsProvider)(nil).GetAllDiskMetrics), arg0, arg1, arg2, arg3)
}

// GetAllDiskMetricsGrouped mocks base method.
func (m *MockSysmonMetricsProvider) GetAllDiskMetricsGrouped(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.SysmonDiskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDiskMetricsGrouped", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.SysmonDiskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDiskMetricsGrouped indicates an expected call of GetAllDiskMetricsGrouped.
func (mr *MockSysmonMetricsProviderMockRecorder) GetAllDiskMetricsGrouped(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDiskMetricsGrouped", reflect.TypeOf((*MockSysmonMetricsProvider)(nil).GetAllDiskMetricsGrouped), arg0, arg1, arg2, arg3)
}

// GetAllMountPoints mocks base method.
func (m *MockSysmonMetricsProvider) GetAllMountPoints(arg0 context.Context, arg1 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMountPoints", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMountPoints indicates an expected call of GetAllMountPoints.
func (mr *MockSysmonMetricsProviderMockRecorder) GetAllMountPoints(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMountPoints", reflect.TypeOf((*MockSysmonMetricsProvider)(nil).GetAllMountPoints), arg0, arg1)
}

// GetAllProcessMetrics mocks base method.
func (m *MockSysmonMetricsProvider) GetAllProcessMetrics(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.ProcessMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProcessMetrics", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.ProcessMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProcessMetrics indicates an expected call of GetAllProcessMetrics.
func (mr *MockSysmonMetricsProviderMockRecorder) GetAllProcessMetrics(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProcessMetrics", reflect.TypeOf((*MockSysmonMetricsProvider)(nil).GetAllProcessMetrics), arg0, arg1, arg2, arg3)
}

// GetAllProcessMetricsGrouped mocks base method.
func (m *MockSysmonMetricsProvider) GetAllProcessMetricsGrouped(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.SysmonProcessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProcessMetricsGrouped", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.SysmonProcessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProcessMetricsGrouped indicates an expected call of GetAllProcessMetricsGrouped.
func (mr *MockSysmonMetricsProviderMockRecorder) GetAllProcessMetricsGrouped(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProcessMetricsGrouped", reflect.TypeOf((*MockSysmonMetricsProvider)(nil).GetAllProcessMetricsGrouped), arg0, arg1, arg2, arg3)
}

// GetCPUMetrics mocks base method.
func (m *MockSysmonMetricsProvider) GetCPUMetrics(arg0 context.Context, arg1 string, arg2 int, arg3, arg4 time.Time) ([]models.CPUMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCPUMetrics", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.CPUMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCPUMetrics indicates an expected call of GetCPUMetrics.
func (mr *MockSysmonMetricsProviderMockRecorder) GetCPUMetrics(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCPUMetrics", reflect.TypeOf((*MockSysmonMetricsProvider)(nil).GetCPUMetrics), arg0, arg1, arg2, arg3, arg4)
}

// GetDiskMetrics mocks base method.
func (m *MockSysmonMetricsProvider) GetDiskMetrics(arg0 context.Context, arg1, arg2 string, arg3, arg4 time.Time) ([]models.DiskMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiskMetrics", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.DiskMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiskMetrics indicates an expected call of GetDiskMetrics.
func (mr *MockSysmonMetricsProviderMockRecorder) GetDiskMetrics(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiskMetrics", reflect.TypeOf((*MockSysmonMetricsProvider)(nil).GetDiskMetrics), arg0, arg1, arg2, arg3, arg4)
}

// GetMemoryMetrics mocks base method.
func (m *MockSysmonMetricsProvider) GetMemoryMetrics(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.MemoryMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemoryMetrics", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.MemoryMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemoryMetrics indicates an expected call of GetMemoryMetrics.
func (mr *MockSysmonMetricsProviderMockRecorder) GetMemoryMetrics(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemoryMetrics", reflect.TypeOf((*MockSysmonMetricsProvider)(nil).GetMemoryMetrics), arg0, arg1, arg2, arg3)
}

// GetMemoryMetricsGrouped mocks base method.
func (m *MockSysmonMetricsProvider) GetMemoryMetricsGrouped(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]models.SysmonMemoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemoryMetricsGrouped", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.SysmonMemoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemoryMetricsGrouped indicates an expected call of GetMemoryMetricsGrouped.
func (mr *MockSysmonMetricsProviderMockRecorder) GetMemoryMetricsGrouped(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemoryMetricsGrouped", reflect.TypeOf((*MockSysmonMetricsProvider)(nil).GetMemoryMetricsGrouped), arg0, arg1, arg2, arg3)
}

// MockRows is a mock of Rows interface.
type MockRows struct {
	ctrl     *gomock.Controller
	recorder *MockRowsMockRecorder
}

// MockRowsMockRecorder is the mock recorder for MockRows.
type MockRowsMockRecorder struct {
	mock *MockRows
}

// NewMockRows creates a new mock instance.
func NewMockRows(ctrl *gomock.Controller) *MockRows {
	mock := &MockRows{ctrl: ctrl}
	mock.recorder = &MockRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRows) EXPECT() *MockRowsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRows) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRowsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRows)(nil).Close))
}

// Err mocks base method.
func (m *MockRows) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockRowsMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockRows)(nil).Err))
}

// Next mocks base method.
func (m *MockRows) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockRowsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockRows)(nil).Next))
}

// Scan mocks base method.
func (m *MockRows) Scan(arg0 ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockRowsMockRecorder) Scan(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockRows)(nil).Scan), arg0...)
}

// MockQueryExecutor is a mock of QueryExecutor interface.
type MockQueryExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockQueryExecutorMockRecorder
}

// MockQueryExecutorMockRecorder is the mock recorder for MockQueryExecutor.
type MockQueryExecutorMockRecorder struct {
	mock *MockQueryExecutor
}

// NewMockQueryExecutor creates a new mock instance.
func NewMockQueryExecutor(ctrl *gomock.Controller) *MockQueryExecutor {
	mock := &MockQueryExecutor{ctrl: ctrl}
	mock.recorder = &MockQueryExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryExecutor) EXPECT() *MockQueryExecutorMockRecorder {
	return m.recorder
}

// ExecuteQuery mocks base method.
func (m *MockQueryExecutor) ExecuteQuery(arg0 context.Context, arg1 string, arg2 ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteQuery", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockQueryExecutorMockRecorder) ExecuteQuery(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockQueryExecutor)(nil).ExecuteQuery), varargs...)
}
