//
// Copyright 2026 Carver Automation Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: agent/discovery/v1/discovery.proto

package discoverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DiscoveryEnvelope carries device observations an add-on made about OTHER
// hosts, from the add-on to the control plane, through the agent and gateway
// unchanged.
//
// It rides as the payload of a
// serviceradar.agent.addon.v1.TelemetryRecord whose payload_kind is
// TELEMETRY_PAYLOAD_KIND_DISCOVERY_V1.
//
// THE POINT OF THIS MESSAGE is that `schema` is a string. Adding a new
// observation type is one registry entry in core: no proto edit, no Go/Elixir/
// Rust regeneration, no agent or gateway change, no agent release. Everything
// between the add-on and core treats `payload` as opaque bytes and must
// continue to.
//
// Nothing here is trusted for identity. agent_id, gateway_id and partition are
// stamped by the control plane from the gateway-attested status metadata, and
// the source string comes from the schema registry -- never from this message.
// See serviceradar.agent.addon.v1.TelemetrySource for the same rule stated for
// telemetry.
type DiscoveryEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// schema names the payload contract, for example
	// "serviceradar.netprobe.census.v1". Core maps it to a decoder and to the
	// identity policy that governs the observations it produces. An unregistered
	// schema is dropped loudly; it is never ingested on a guess.
	Schema string `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// producer_id names the add-on that observed this, for operator display and
	// telemetry only. It is NOT an identity claim and MUST NOT be used to
	// attribute an observation to a device or an agent.
	ProducerId string `protobuf:"bytes,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	// observation_scope is the supersession key: within one schema, a later
	// envelope with the same scope replaces an earlier one. netprobe uses the
	// capture interface name, so a snapshot of eth0 never hides eth1. Empty
	// means no supersession.
	ObservationScope string `protobuf:"bytes,3,opt,name=observation_scope,json=observationScope,proto3" json:"observation_scope,omitempty"`
	// snapshot_id set means SNAPSHOT semantics: the envelope (with its siblings,
	// see part_index) is a complete replacement for observation_scope, and a
	// device absent from it has gone away. Empty means EVENT semantics: an
	// independent observation that adds to what is known and implies nothing
	// about what is missing.
	//
	// Producers that restart MUST seed this with something that cannot repeat --
	// netprobe uses its process start time -- so a reassembler can never merge
	// parts of two different snapshots.
	SnapshotId string `protobuf:"bytes,4,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// part_index and part_count split one snapshot across several envelopes when
	// it does not fit a single telemetry batch. Reassembly happens in the CONTROL
	// PLANE, not the agent: the agent forwards parts without understanding them.
	//
	// This is not an optional nicety. The agent drops a whole batch that exceeds
	// its size cap, with no re-queue -- so an unsplit oversized snapshot is total
	// silence for exactly the largest segments, which are the ones that matter.
	PartIndex uint32 `protobuf:"varint,5,opt,name=part_index,json=partIndex,proto3" json:"part_index,omitempty"`
	PartCount uint32 `protobuf:"varint,6,opt,name=part_count,json=partCount,proto3" json:"part_count,omitempty"`
	// complete marks the last part of a snapshot. A set is ingested only when
	// every part has arrived AND one of them is marked complete; counting parts
	// alone accepts a set whose final part never came but which received a
	// duplicate instead.
	Complete bool `protobuf:"varint,7,opt,name=complete,proto3" json:"complete,omitempty"`
	// generated_at_unix_nano is when the producer built this envelope, not when
	// it observed anything. Supersession compares this rather than arrival order,
	// because nothing between here and core guarantees ordering.
	GeneratedAtUnixNano int64 `protobuf:"varint,8,opt,name=generated_at_unix_nano,json=generatedAtUnixNano,proto3" json:"generated_at_unix_nano,omitempty"`
	// dropped_since_last counts observations the producer discarded since its
	// previous envelope for this scope -- a full ring buffer, a table at
	// capacity. A quiet segment and a saturated producer look identical without
	// it.
	DroppedSinceLast uint64 `protobuf:"varint,9,opt,name=dropped_since_last,json=droppedSinceLast,proto3" json:"dropped_since_last,omitempty"`
	// payload is the schema-specific body. Opaque to the agent and the gateway;
	// decoded only in core, only by the decoder the schema registry names.
	Payload       []byte `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryEnvelope) Reset() {
	*x = DiscoveryEnvelope{}
	mi := &file_agent_discovery_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryEnvelope) ProtoMessage() {}

func (x *DiscoveryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_agent_discovery_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryEnvelope.ProtoReflect.Descriptor instead.
func (*DiscoveryEnvelope) Descriptor() ([]byte, []int) {
	return file_agent_discovery_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryEnvelope) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *DiscoveryEnvelope) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *DiscoveryEnvelope) GetObservationScope() string {
	if x != nil {
		return x.ObservationScope
	}
	return ""
}

func (x *DiscoveryEnvelope) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *DiscoveryEnvelope) GetPartIndex() uint32 {
	if x != nil {
		return x.PartIndex
	}
	return 0
}

func (x *DiscoveryEnvelope) GetPartCount() uint32 {
	if x != nil {
		return x.PartCount
	}
	return 0
}

func (x *DiscoveryEnvelope) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *DiscoveryEnvelope) GetGeneratedAtUnixNano() int64 {
	if x != nil {
		return x.GeneratedAtUnixNano
	}
	return 0
}

func (x *DiscoveryEnvelope) GetDroppedSinceLast() uint64 {
	if x != nil {
		return x.DroppedSinceLast
	}
	return 0
}

func (x *DiscoveryEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_agent_discovery_v1_discovery_proto protoreflect.FileDescriptor

const file_agent_discovery_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"\"agent/discovery/v1/discovery.proto\x12\x1fserviceradar.agent.discovery.v1\"\xf1\x02\n" +
	"\x11DiscoveryEnvelope\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x1f\n" +
	"\vproducer_id\x18\x02 \x01(\tR\n" +
	"producerId\x12+\n" +
	"\x11observation_scope\x18\x03 \x01(\tR\x10observationScope\x12\x1f\n" +
	"\vsnapshot_id\x18\x04 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"part_index\x18\x05 \x01(\rR\tpartIndex\x12\x1d\n" +
	"\n" +
	"part_count\x18\x06 \x01(\rR\tpartCount\x12\x1a\n" +
	"\bcomplete\x18\a \x01(\bR\bcomplete\x123\n" +
	"\x16generated_at_unix_nano\x18\b \x01(\x03R\x13generatedAtUnixNano\x12,\n" +
	"\x12dropped_since_last\x18\t \x01(\x04R\x10droppedSinceLast\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayloadBIZGgithub.com/carverauto/serviceradar/proto/agent/discovery/v1;discoverypbb\x06proto3"

var (
	file_agent_discovery_v1_discovery_proto_rawDescOnce sync.Once
	file_agent_discovery_v1_discovery_proto_rawDescData []byte
)

func file_agent_discovery_v1_discovery_proto_rawDescGZIP() []byte {
	file_agent_discovery_v1_discovery_proto_rawDescOnce.Do(func() {
		file_agent_discovery_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_discovery_v1_discovery_proto_rawDesc), len(file_agent_discovery_v1_discovery_proto_rawDesc)))
	})
	return file_agent_discovery_v1_discovery_proto_rawDescData
}

var file_agent_discovery_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agent_discovery_v1_discovery_proto_goTypes = []any{
	(*DiscoveryEnvelope)(nil), // 0: serviceradar.agent.discovery.v1.DiscoveryEnvelope
}
var file_agent_discovery_v1_discovery_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_discovery_v1_discovery_proto_init() }
func file_agent_discovery_v1_discovery_proto_init() {
	if File_agent_discovery_v1_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_discovery_v1_discovery_proto_rawDesc), len(file_agent_discovery_v1_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_discovery_v1_discovery_proto_goTypes,
		DependencyIndexes: file_agent_discovery_v1_discovery_proto_depIdxs,
		MessageInfos:      file_agent_discovery_v1_discovery_proto_msgTypes,
	}.Build()
	File_agent_discovery_v1_discovery_proto = out.File
	file_agent_discovery_v1_discovery_proto_goTypes = nil
	file_agent_discovery_v1_discovery_proto_depIdxs = nil
}
