apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
  namespace: demo
spec:
  instances: 3
  imageName: ghcr.io/carverauto/serviceradar-cnpg:16.6.0-sr4
  imagePullSecrets:
    - name: ghcr-io-cred

  storage:
    size: 100Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: spire
      owner: spire
      secret:
        name: spire-db-credentials
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb;
        - CREATE EXTENSION IF NOT EXISTS age;
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

  postgresql:
    shared_preload_libraries:
      - timescaledb
      - age
      - pg_stat_statements
    pg_hba:
      - "hostnossl all all all reject"
      - "hostssl all all all scram-sha-256 clientcert=verify-ca"

  certificates:
    clientCASecret: serviceradar-cnpg-client-ca

  managed:
    roles:
      - name: spire
        ensure: present
        login: true
        passwordSecret:
          name: spire-db-credentials

  monitoring:
    enablePodMonitor: true
