version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - mirror
    - misspell
    - mnd
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - wsl
  settings:
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - (gofr.dev/pkg/gofr/Logger).Logf
            - (gofr.dev/pkg/gofr/Logger).Errorf
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    nestif:
      min-complexity: 6
    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
        - name: var-naming
        - name: bare-return
        - name: bool-literal-in-expr
        - name: comment-spacings
        - name: early-return
        - name: defer
        - name: deep-exit
        - name: unused-receiver
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Exclude certain linters from test files
      - linters:
          - mnd
          - dupl
          - goconst
          - funlen
          - gocognit
          - gocyclo
          - err113
          - noctx
          - gocritic
        path: _test\.go
      # Exclude magic numbers from common cases
      - linters:
          - mnd
        text: "Magic number: (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9]),|Magic number: (100|50|10|5|2|1|0),"
      # Exclude revive exported rule for interfaces
      - linters:
          - revive
        text: "exported: type name will be used as"
      # Exclude stylecheck ST1003 for test methods
      - linters:
          - stylecheck
        text: "ST1003:"
        path: _test\.go
      # Specific file exclusions
      - linters:
          - typecheck
        path: pkg/core/api/server\.go
      # Exclude err113 for common error patterns
      - linters:
          - err113
        text: "do not define dynamic errors"
      # Exclude gosec G404 for non-crypto random
      - linters:
          - gosec
        text: "G404:"
      # Allow TODO comments
      - linters:
          - godox
        text: "TODO|FIXME|BUG"
    paths:
      - proto/flow
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - proto/flow
      - third_party$
      - builtin$
      - examples$
global:
  timeout: 5m
