project_name: serviceradar

before:
  hooks:
    - go mod tidy

builds:
  - id: agent
    main: ./cmd/agent/main.go
    binary: serviceradar-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: poller
    main: ./cmd/poller/main.go
    binary: serviceradar-poller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: dusk-checker
    main: ./cmd/checkers/dusk/main.go
    binary: serviceradar-dusk-checker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

dockers:
  - id: cloud
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/mfreeman451/serviceradar-cloud:{{ .Version }}"
      - "ghcr.io/mfreeman451/serviceradar-cloud:latest"
    dockerfile: Dockerfile.build
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - web
      - cmd/cloud
      - pkg/cloud
      - go.mod
      - go.sum

nfpms:
  - id: agent
    package_name: serviceradar-agent
    file_name_template: "{{ .PackageName }}_{{ .Version }}"
    builds:
      - agent
    vendor: ServiceRadar
    homepage: https://github.com/mfreeman451/serviceradar
    maintainer: Michael Freeman <mfreeman451@gmail.com>
    description: ServiceRadar Agent Component
    license: MIT
    formats:
      - deb
    dependencies:
      - systemd
    contents:
      - src: packaging/agent/systemd/serviceradar-agent.service
        dst: /lib/systemd/system/serviceradar-agent.service
      - src: packaging/agent/config/agent.json
        dst: /etc/serviceradar/agent.json
        type: config
    scripts:
      postinstall: packaging/agent/scripts/postinstall.sh
      preremove: packaging/agent/scripts/preremove.sh

  - id: poller
    package_name: serviceradar-poller
    file_name_template: "{{ .PackageName }}_{{ .Version }}"
    builds:
      - poller
    vendor: ServiceRadar
    homepage: https://github.com/mfreeman451/serviceradar
    maintainer: Michael Freeman <mfreeman451@gmail.com>
    description: ServiceRadar Poller Component
    license: MIT
    formats:
      - deb
    dependencies:
      - systemd
    contents:
      - src: packaging/poller/systemd/serviceradar-poller.service
        dst: /lib/systemd/system/serviceradar-poller.service
      - src: packaging/poller/config/poller.json
        dst: /etc/serviceradar/poller.json
        type: config
    scripts:
      postinstall: packaging/poller/scripts/postinstall.sh
      preremove: packaging/poller/scripts/preremove.sh

  - id: dusk-checker
    package_name: serviceradar-dusk-checker
    file_name_template: "{{ .PackageName }}_{{ .Version }}"
    builds:
      - dusk-checker
    vendor: ServiceRadar
    homepage: https://github.com/mfreeman451/serviceradar
    maintainer: Michael Freeman <mfreeman451@gmail.com>
    description: ServiceRadar Dusk Checker Component
    license: MIT
    formats:
      - deb
    dependencies:
      - systemd
    contents:
      - src: packaging/dusk/config/dusk.json
        dst: /etc/serviceradar/checkers/dusk.json
        type: config
      - src: packaging/dusk/config/external.json
        dst: /etc/serviceradar/checkers/external.json
        type: config
    scripts:
      postinstall: packaging/dusk/scripts/postinstall.sh
      preremove: packaging/dusk/scripts/preremove.sh

release:
  github:
    owner: mfreeman451
    name: serviceradar
  draft: true
  prerelease: auto
  mode: replace
  header: |
    # ServiceRadar {{ .Version }}
    Release of ServiceRadar monitoring system.
    
    ## Components
    - serviceradar-dusk-checker: Agent package for monitoring Dusk nodes
    - serviceradar-agent: Agent performs checks, collects information from external checkers (dusk)
    - serviceradar-poller: Network poller for collecting monitoring data from Agent
    - serviceradar-cloud: Cloud service with web interface and alerts
    
    ## Installation
    See the [README.md](README.md) for detailed installation instructions.
    
    ### Quick Start
    ```bash
    # On Agents:
    sudo dpkg -i serviceradar-agent_{{ .Version }}.deb
    # With Dusk Checker (on agent)
    sudo dpkg -i serviceradar-dusk-checker_{{ .Version }}.deb
    # On monitoring host (can co-locate with agent):
    sudo dpkg -i serviceradar-poller_{{ .Version }}.deb
    # On cloud host (can co-locate with poller+agent):
    sudo dpkg -i serviceradar-cloud_{{ .Version }}.deb
    ```

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - 'Merge pull request'
      - 'Merge branch'