exclude:
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/target/**"
  - "**/.git/**"
  - "**/build/**"
  - "**/release/**"
  - "**/dist/**"
  - "**/.next/**"
  - "**/testdata/**"
  - "**/test/**"
  - "**/tests/**"
  - "**/examples/**"
  - "**/.bazel/**"
  - "**/.cache/**"
  - "**/docs/.docusaurus/**"
  - "**/bazel-*/**"
