# gazelle:ignore
#
# This TinyGo plugin is compiled to wasip1 by //build/wasm_plugins.
package(default_visibility = ["//visibility:public"])

exports_files([
    "config.local.schema.json",
    "config.schema.json",
    "display/alert_event.display.json",
    "main_tinygo.go",
    "plugin.local.yaml",
    "plugin.yaml",
    "schemas/ocsf_alert_event.schema.json",
])

filegroup(
    name = "srcs",
    srcs = glob(
        ["**"],
        exclude = [
            "dist/**",
            "manifest.json",
        ],
    ),
)
