[package]
name = "profiler"
version = "0.1.0"
edition = "2021"

[lib]
name = "profiler"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "profiler"
path = "src/main.rs"

[dependencies]
# gRPC and serialization
tonic = { version = "0.12", features = ["tls"] }
prost = "0.13"
tokio = { workspace = true, features = ["full"] }
tokio-stream = "0.1"

# eBPF framework
aya = { workspace = true, features = ["async_tokio"] }
aya-log = { workspace = true }
profiler-common = { path = "../profiler-common", features = ["user"] }

# Utility crates
anyhow = { workspace = true, features = ["std"] }
uuid = { version = "1.0", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
clap = { workspace = true, features = ["derive"] }
log = { workspace = true }
env_logger = { workspace = true }
dashmap = "6.0"
futures-util = "0.3"

# Profiling output formats
pprof = { version = "0.13", features = ["flamegraph", "protobuf-codec"] }

# TUI for interactive flamegraph display
ratatui = "0.29"
crossterm = "0.28"

[dev-dependencies]
tempfile = "3.0"

[build-dependencies]
tonic-build = "0.12"