defmodule ServiceRadar.Repo.Migrations.AddTenantNatsAccountFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      add :nats_account_public_key, :text
      add :nats_account_jwt, :text
      add :nats_account_status, :text
      add :nats_account_error, :text
      add :encrypted_nats_account_seed_ciphertext, :binary
    end

    alter table(:polling_schedules) do
      add :assigned_domain, :text
    end
  end

  def down do
    alter table(:polling_schedules) do
      remove :assigned_domain
    end

    alter table(:tenants) do
      remove :encrypted_nats_account_seed_ciphertext
      remove :nats_account_error
      remove :nats_account_status
      remove :nats_account_jwt
      remove :nats_account_public_key
    end
  end
end
