defmodule ServiceRadar.Repo.TenantMigrations.AddStatefulAlertRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stateful_alert_rules, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :enabled, :boolean, default: true
      add :priority, :bigint, default: 100
      add :signal, :text, null: false, default: "log"
      add :match, :map, default: %{}
      add :group_by, {:array, :text}
      add :threshold, :bigint, null: false, default: 5
      add :window_seconds, :bigint, null: false, default: 600
      add :bucket_seconds, :bigint, null: false, default: 60
      add :cooldown_seconds, :bigint, null: false, default: 300
      add :renotify_seconds, :bigint, null: false, default: 21600
      add :event, :map, default: %{}
      add :alert, :map, default: %{}
      add :tenant_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:stateful_alert_rules, [:tenant_id, :name],
             name: "stateful_alert_rules_unique_name_index"
           )

    create table(:stateful_alert_rule_states, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rule_id, :uuid, null: false
      add :group_key, :text, null: false
      add :group_values, :map, default: %{}
      add :window_seconds, :bigint, null: false
      add :bucket_seconds, :bigint, null: false
      add :current_bucket_start, :utc_datetime_usec, null: false
      add :bucket_counts, :map, default: %{}
      add :last_seen_at, :utc_datetime_usec
      add :last_fired_at, :utc_datetime_usec
      add :last_notification_at, :utc_datetime_usec
      add :cooldown_until, :utc_datetime_usec
      add :alert_id, :uuid
      add :tenant_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:stateful_alert_rule_states, [:tenant_id, :rule_id, :group_key],
             name: "stateful_alert_rule_states_unique_state_index"
           )
  end

  def down do
    drop_if_exists unique_index(:stateful_alert_rule_states, [:tenant_id, :rule_id, :group_key],
                     name: "stateful_alert_rule_states_unique_state_index"
                   )

    drop table(:stateful_alert_rule_states, prefix: prefix())

    drop_if_exists unique_index(:stateful_alert_rules, [:tenant_id, :name],
                     name: "stateful_alert_rules_unique_name_index"
                   )

    drop table(:stateful_alert_rules, prefix: prefix())
  end
end
