defmodule ServiceRadar.Repo.TenantMigrations.AddLogPromotionRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:log_promotion_rules, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :enabled, :boolean, default: true
      add :priority, :bigint, default: 100
      add :match, :map, default: %{}
      add :event, :map, default: %{}
      add :tenant_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:log_promotion_rules, [:tenant_id, :name],
             name: "log_promotion_rules_unique_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:log_promotion_rules, [:tenant_id, :name],
                     name: "log_promotion_rules_unique_name_index"
                   )

    drop table(:log_promotion_rules, prefix: prefix())
  end
end
