load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "remoteaccess",
    srcs = [
        "manager.go",
        "ssh_open.go",
        "ssh.go",
    ],
    importpath = "github.com/carverauto/serviceradar/go/pkg/agent/remoteaccess",
    visibility = ["//visibility:public"],
    deps = ["@org_golang_x_crypto//ssh"],
)

go_test(
    name = "remoteaccess_test",
    srcs = [
        "ssh_integration_test.go",
        "manager_test.go",
        "ssh_open_test.go",
        "ssh_test.go",
    ],
    embed = [":remoteaccess"],
    deps = ["//go/pkg/remoteaccess/sshca"],
)
