apiVersion: v1
kind: Secret
metadata:
  name: cluster-pg-superuser
  namespace: cnpg-system
type: Opaque
stringData:
  username: postgres
  password: 28890621c8068ce8

---
apiVersion: v1
kind: Secret
metadata:
  name: kratos-db-credentials
  namespace: cnpg-system
type: Opaque
stringData:
  username: kratos
  password: fab9a3890aa6f68a
