# Default AlmaLinux VM configuration for the sysmon-vm checker.
# Copy this file to your workspace (dist/sysmonvm/config.yaml by default)
# and adjust values as needed before running the provisioning scripts.

vm_name: serviceradar-alma9

image:
  url: https://repo.almalinux.org/almalinux/9/cloud/aarch64/images/AlmaLinux-9-GenericCloud-latest.aarch64.qcow2
  # Replace the checksum after downloading the image; this is a placeholder.
  checksum: sha256:REPLACE_ME
  local_filename: AlmaLinux-9-GenericCloud-latest.aarch64.qcow2

hardware:
  cpu_count: 4
  memory_mb: 6144
  disk_size_gb: 40
  accelerator: hvf

networking:
  mode: user
  ssh_port: 2222
  forwarded_ports:
    - host: 50110
      guest: 50110

cloud_init:
  hostname: srv-sysmonvm
  user: alma
  ssh_authorized_key_path: ~/.ssh/id_ed25519.pub
  enable_passwordless_sudo: true

notes:
  - Review cpu_plan.md Phase 2 before modifying image.url.
  - Update forwarded_ports once the ServiceRadar agent port map is finalized.
