# flowgger.toml

[input]
type = "udp"
listen = "0.0.0.0:514"
format = "rfc3164"

[output]
type = "nats"
format = "gelf"
framing = "noop" # NATS output handles its own framing
# Partition for overlapping IP spaces
partition = "default"

# NATS JetStream specific settings
nats_url = "nats://127.0.0.1:4222"
nats_subject = "events.syslog"
nats_stream = "events" # Optional: defaults to "events"
nats_timeout = 30000 # Optional: ACK timeout in ms, defaults to 30000
# Retry behaviour (0 attempts = retry forever)
nats_connect_attempts = 0
nats_connect_initial_backoff_ms = 500
nats_connect_max_backoff_ms = 30000
nats_tls_ca_file = "/etc/serviceradar/certs/root.pem"
nats_tls_cert = "/etc/serviceradar/certs/checkers.pem"
nats_tls_key = "/etc/serviceradar/certs/checkers-key.pem"

[grpc]
listen_addr = "127.0.0.1:50044"
mode = "mtls"
cert_dir = "/etc/serviceradar/certs"
cert_file = "/etc/serviceradar/certs/flowgger.pem"
key_file = "/etc/serviceradar/certs/flowgger-key.pem"
ca_file = "/etc/serviceradar/certs/root.pem"
