# Dialyzer suppressions for serviceradar_web_ng.
#
# Convention: every entry is file + warning-kind + exact {line, col}, so a
# suppression covers exactly one known-false-positive instance. New findings
# stay visible, and `list_unused_filters: true` (mix.exs) turns a stale entry
# into a build failure instead of silent rot. When you fix the underlying
# code, delete the entry in the same commit.
#
# What lives here (and why it is a suppression, not a code fix):
# - Defensive catch-all clauses over dynamic data (LiveView params, socket
#   assigns, SRQL/external JSON). Dialyzer's closed-world inference calls
#   them dead; deleting them would trade graceful defaults for
#   FunctionClauseError crashes. Never "fix" these by deleting the clause.
# - MapSet/Map opaque-type imprecision (`call_without_opaque` on
#   MapSet.member?/2, `call_with_opaque` on URI.parse/1 results). The calls
#   are idiomatic; restructuring them to please the checker is forbidden.
# - Dependency success-typing gaps: Datasvc.KV.list_keys/2 and
#   ComponentTemplates.list/3 genuinely return {:error, _} at runtime, and
#   NetworkAddressPolicy genuinely returns :invalid_cidr, even when Dialyzer
#   infers narrower returns. The rules_live unused_fun entries cascade from
#   the list_kv_zen_rules {:ok, _} arm: if that arm is ever really dead, all
#   four entries go stale together and the build will say so.
# - Public context functions Dialyzer reports as never called
#   (`unused_fun` in dashboards/*, spatial_controller, edge_controller).
#   They are kept as intentional API surface; deleting them to silence the
#   checker would be degradation, not cleanup.
[
  {"lib/serviceradar_web_ng/alert_actions.ex", :pattern_match_cov, {487, 8}},
  {"lib/serviceradar_web_ng/dashboards/authored.ex", :call_without_opaque, 12},
  {"lib/serviceradar_web_ng/dashboards/authored.ex", :pattern_match_cov, 14},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :pattern_match, {133, 17}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :pattern_match, {172, 5}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {225, 8}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {246, 8}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {252, 8}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {258, 8}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {270, 8}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {294, 8}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {302, 8}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {320, 8}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {334, 8}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {358, 8}},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", :unused_fun, {376, 8}},
  {"lib/serviceradar_web_ng/dashboards/frame_runner.ex", :pattern_match_cov, {464, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :pattern_match, {106, 5}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :pattern_match, {140, 5}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :pattern_match, {59, 13}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, 778},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {390, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {396, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {420, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {447, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {461, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {507, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {531, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {539, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {645, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {662, 8}},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", :unused_fun, {713, 8}},
  {"lib/serviceradar_web_ng/devices/manual_device_creator.ex", :pattern_match_cov, {555, 9}},
  {"lib/serviceradar_web_ng/edge/component_templates.ex", :pattern_match, 93},
  {"lib/serviceradar_web_ng/edge/component_templates.ex", :pattern_match, {63, 13}},
  {"lib/serviceradar_web_ng/edge/component_templates.ex", :pattern_match, {96, 7}},
  {"lib/serviceradar_web_ng/edge/component_templates.ex", :pattern_match_cov, {79, 16}},
  {"lib/serviceradar_web_ng/edge/component_templates.ex", :unused_fun, {150, 8}},
  {"lib/serviceradar_web_ng/edge/onboarding_token.ex", :pattern_match_cov, {157, 8}},
  {"lib/serviceradar_web_ng/field_survey_review.ex", :guard_fail, 1977},
  {"lib/serviceradar_web_ng/field_survey_review.ex", :guard_fail, 1978},
  {"lib/serviceradar_web_ng/field_survey_review.ex", :guard_fail, 1979},
  {"lib/serviceradar_web_ng/field_survey_review.ex", :invalid_contract, 239},
  {"lib/serviceradar_web_ng/field_survey_review.ex", :pattern_match, {706, 8}},
  {"lib/serviceradar_web_ng/field_survey_review.ex", :pattern_match, {882, 8}},
  {"lib/serviceradar_web_ng/field_survey_review.ex", :pattern_match_cov, {1235, 7}},
  {"lib/serviceradar_web_ng/field_survey_review.ex", :pattern_match_cov, {1882, 8}},
  {"lib/serviceradar_web_ng/field_survey_room_artifacts.ex", :pattern_match_cov, {124, 8}},
  {"lib/serviceradar_web_ng/plugins/addon_rollouts.ex", :pattern_match_cov, {94, 8}},
  {"lib/serviceradar_web_ng/plugins/assignments.ex", :pattern_match_cov, {541, 8}},
  {"lib/serviceradar_web_ng/plugins/assignments.ex", :pattern_match_cov, {547, 8}},
  {"lib/serviceradar_web_ng/plugins/blob_retention.ex", :pattern_match_cov, {228, 8}},
  {"lib/serviceradar_web_ng/plugins/first_party_importer.ex", :guard_fail, 176},
  {"lib/serviceradar_web_ng/plugins/first_party_importer.ex", :guard_fail, 177},
  {"lib/serviceradar_web_ng/plugins/first_party_importer.ex", :pattern_match_cov, {416, 8}},
  {"lib/serviceradar_web_ng/plugins/first_party_release_client.ex", :guard_fail, {334, 75}},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", :pattern_match, {514, 13}},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", :pattern_match, {82, 5}},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", :unused_fun, {215, 8}},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", :unused_fun, {226, 8}},
  {"lib/serviceradar_web_ng/plugins/packages.ex", :call_without_opaque, {292, 27}},
  {"lib/serviceradar_web_ng/plugins/packages.ex", :guard_fail, 538},
  {"lib/serviceradar_web_ng/plugins/packages.ex", :guard_fail, 539},
  {"lib/serviceradar_web_ng/remote_access_desktop_targets.ex", :pattern_match_cov, {292, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {4855, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {909, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {942, 8}},
  {"lib/serviceradar_web_ng_web/auth/password_reset_delivery.ex", :pattern_match_cov, {65, 7}},
  {"lib/serviceradar_web_ng_web/camera_multiview.ex", :pattern_match_cov, {264, 8}},
  {"lib/serviceradar_web_ng_web/channels/dashboard_frame_channel.ex", :guard_fail, {444, 34}},
  {"lib/serviceradar_web_ng_web/channels/dashboard_frame_channel.ex", :pattern_match, {150, 16}},
  {"lib/serviceradar_web_ng_web/controllers/api/addon_package_controller.ex", :pattern_match, {36, 17}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :guard_fail, 453},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match, {610, 20}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match, {621, 20}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match, {632, 20}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match, {640, 16}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match_cov, {416, 7}},
  {"lib/serviceradar_web_ng_web/controllers/api/identity_controller.ex", :pattern_match_cov, {224, 8}},
  {"lib/serviceradar_web_ng_web/controllers/api/identity_controller.ex", :pattern_match_cov, {90, 8}},
  {"lib/serviceradar_web_ng_web/controllers/api/proxmox_console_session_controller.ex", :call_without_opaque, {184, 73}},
  {"lib/serviceradar_web_ng_web/controllers/api/remote_access_session_controller.ex", :pattern_match_cov, {768, 8}},
  {"lib/serviceradar_web_ng_web/controllers/api/remote_access_target_intent_controller.ex", :pattern_match_cov, {231, 8}},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", :pattern_match, {98, 16}},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", :unused_fun, {127, 8}},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", :unused_fun, {156, 8}},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", :unused_fun, {211, 8}},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", :unused_fun, {219, 8}},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", :unused_fun, {225, 8}},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", :unused_fun, {228, 8}},
  {"lib/serviceradar_web_ng_web/controllers/cli_auth_controller.ex", :pattern_match_cov, {466, 9}},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex", :pattern_match, {102, 31}},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex", :pattern_match, {106, 45}},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex", :pattern_match, {110, 34}},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex", :pattern_match, {73, 16}},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex", :unused_fun, {354, 8}},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex", :unused_fun, {373, 8}},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex", :unused_fun, {378, 8}},
  {"lib/serviceradar_web_ng_web/controllers/saml_controller.ex", :guard_fail, 733},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/table.ex", :pattern_match_cov, {307, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries/metrics.ex", :pattern_match_cov, {147, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries/series_data.ex", :pattern_match, {396, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries/series_data.ex", :pattern_match_cov, {394, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/topology.ex", :pattern_match_cov, {276, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/topology.ex", :pattern_match_cov, {43, 7}},
  {"lib/serviceradar_web_ng_web/live/admin/addon_package_live/index.ex", :pattern_match_cov, {2483, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/dashboard_package_live/index.ex", :pattern_match, {160, 16}},
  {"lib/serviceradar_web_ng_web/live/admin/dashboard_package_live/index.ex", :pattern_match_cov, {1053, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/dashboard_package_live/index.ex", :unused_fun, {951, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/dashboard_package_live/index.ex", :unused_fun, {980, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov, {3283, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov, {4655, 13}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov, {4685, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov, {5324, 8}},
  {"lib/serviceradar_web_ng_web/live/alert_live/show.ex", :pattern_match_cov, {1526, 8}},
  {"lib/serviceradar_web_ng_web/live/alert_live/show.ex", :pattern_match_cov, {1796, 8}},
  {"lib/serviceradar_web_ng_web/live/alert_live/show.ex", :pattern_match_cov, {1855, 8}},
  {"lib/serviceradar_web_ng_web/live/alert_live/show.ex", :pattern_match_cov, {1882, 8}},
  {"lib/serviceradar_web_ng_web/live/alert_live/show.ex", :pattern_match_cov, {2188, 8}},
  {"lib/serviceradar_web_ng_web/live/analytics_live/index.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/authored_dashboard_live/canvas_state.ex", :guard_fail, 146},
  {"lib/serviceradar_web_ng_web/live/authored_dashboard_live/panel_components.ex", :pattern_match_cov, {911, 8}},
  {"lib/serviceradar_web_ng_web/live/authored_dashboard_live/panel_components.ex", :pattern_match_cov, {918, 8}},
  {"lib/serviceradar_web_ng_web/live/authored_dashboard_live/panel_components.ex", :pattern_match_cov, {919, 8}},
  {"lib/serviceradar_web_ng_web/live/bgp_live/index.ex", :pattern_match_cov, {78, 8}},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/data.ex", :pattern_match, 18},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/data.ex", :pattern_match_cov, 10},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/data.ex", :pattern_match_cov, 18},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/data.ex", :pattern_match_cov, 24},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/index.ex", :pattern_match_cov, {208, 8}},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/index/fieldsurvey_panel.ex", :pattern_match_cov, {233, 8}},
  {"lib/serviceradar_web_ng_web/live/dashboard_package_live/show.ex", :guard_fail, 533},
  {"lib/serviceradar_web_ng_web/live/dashboard_package_live/show.ex", :pattern_match_cov, {484, 8}},
  {"lib/serviceradar_web_ng_web/live/dashboard_package_live/show.ex", :pattern_match_cov, {495, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/all_metadata_components.ex", :pattern_match_cov, {269, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/all_metadata_components.ex", :pattern_match_cov, {356, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/anomaly_capacity_components.ex", :pattern_match_cov, {1667, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/device_summary_components.ex", :pattern_match_cov, {244, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/endpoint_inventory_data.ex", :guard_fail, 283},
  {"lib/serviceradar_web_ng_web/live/device_live/endpoint_inventory_data.ex", :pattern_match_cov, {500, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/endpoint_inventory_runtime.ex", :pattern_match_cov, {420, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/index_path.ex", :call_with_opaque, {34, 57}},
  {"lib/serviceradar_web_ng_web/live/device_live/log_components.ex", :pattern_match_cov, {118, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/metric_section_components.ex", :pattern_match_cov, {143, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/mtr_components.ex", :pattern_match_cov, {789, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/process_metrics_components.ex", :guard_fail, {225, 31}},
  {"lib/serviceradar_web_ng_web/live/device_live/remote_access_data.ex", :pattern_match, {208, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/remote_access_data.ex", :pattern_match_cov, {175, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/remote_access_data.ex", :pattern_match_cov, {221, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {1867, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/sysmon_metrics/identity.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/device_live/sysmon_metrics/reference_lines.ex", :pattern_match_cov, {78, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/virtualization_components.ex", :pattern_match, {473, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :call_without_opaque, {759, 20}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :pattern_match_cov, {606, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :pattern_match_cov, {684, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :pattern_match_cov, {733, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :pattern_match_cov, {756, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :pattern_match_cov, {773, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :pattern_match_cov, {979, 8}},
  {"lib/serviceradar_web_ng_web/live/diagnostics_live/mtr_data.ex", :guard_fail, 821},
  {"lib/serviceradar_web_ng_web/live/diagnostics_live/mtr_data.ex", :guard_fail, 822},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :call_without_opaque, {1968, 29}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {1208, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {1462, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {2106, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {2194, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {2283, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {2426, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {2449, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {2631, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {2655, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {2697, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {2712, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {2862, 8}},
  {"lib/serviceradar_web_ng_web/live/interface_live/show.ex", :pattern_match, {471, 8}},
  {"lib/serviceradar_web_ng_web/live/interface_live/show.ex", :pattern_match, {473, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {3996, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {4013, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {6731, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {7900, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {891, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :call_without_opaque, {844, 52}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1040, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1060, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1109, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1130, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1184, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1198, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1207, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1232, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1264, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1277, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1284, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1287, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1297, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1307, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1313, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1328, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1351, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {1439, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {333, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {998, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize/events.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/observability_health_live/index.ex", :guard_fail, 680},
  {"lib/serviceradar_web_ng_web/live/observability_health_live/index.ex", :guard_fail, 681},
  {"lib/serviceradar_web_ng_web/live/observability_health_live/index.ex", :guard_fail, 682},
  {"lib/serviceradar_web_ng_web/live/security_live/index.ex", :pattern_match_cov, {756, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/anomaly_detection_live.ex", :pattern_match_cov, {764, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/ansible_live.ex", :pattern_match, {1561, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/event_show.ex", :call_without_opaque, {21, 27}},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/event_show.ex", :call_without_opaque, {62, 20}},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/events.ex", :call_without_opaque, {114, 20}},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/events.ex", :call_without_opaque, {39, 39}},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/events.ex", :pattern_match_cov, {173, 7}},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/history.ex", :call_without_opaque, {33, 44}},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/lockouts.ex", :call_without_opaque, {31, 44}},
  {"lib/serviceradar_web_ng_web/live/settings/cli_auth_policy_live.ex", :call_without_opaque, {34, 23}},
  {"lib/serviceradar_web_ng_web/live/settings/cli_sessions_live.ex", :call_without_opaque, {53, 48}},
  {"lib/serviceradar_web_ng_web/live/settings/composite_checks_live/form_state.ex", :pattern_match_cov, {314, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/integrations_live/index.ex", :pattern_match_cov, {3041, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/mtr_profiles_live/index.ex", :pattern_match_cov, {1240, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/network_credential_rules_live.ex", :pattern_match_cov, {2798, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/network_credential_rules_live/credential_management.ex", :pattern_match_cov, {116, 7}},
  {"lib/serviceradar_web_ng_web/live/settings/networks_live/agent_picker.ex", :contract_with_opaque, 123},
  {"lib/serviceradar_web_ng_web/live/settings/networks_live/index/event_handlers/agent_picker.ex", :call_without_opaque, {100, 57}},
  {"lib/serviceradar_web_ng_web/live/settings/networks_live/index/event_handlers/groups.ex", :pattern_match_cov, {109, 16}},
  {"lib/serviceradar_web_ng_web/live/settings/notifications_live/index.ex", :pattern_match_cov, {1210, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/notifications_live/provider_upload.ex", :pattern_match_cov, {370, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/notifications_live/provider_upload.ex", :pattern_match_cov, {379, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/notifications_live/provider_upload.ex", :pattern_match_cov, {390, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/notifications_live/test_send.ex", :pattern_match, {178, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/notifications_live/test_send.ex", :pattern_match_cov, {179, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/prefix_tags_live.ex", :pattern_match_cov, {767, 9}},
  {"lib/serviceradar_web_ng_web/live/settings/remote_access_desktop_targets_live.ex", :pattern_match_cov, {825, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/rules_live/index.ex", :pattern_match, {855, 13}},
  {"lib/serviceradar_web_ng_web/live/settings/rules_live/index.ex", :unused_fun, {867, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/rules_live/index.ex", :unused_fun, {896, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/rules_live/index.ex", :unused_fun, {922, 8}},
  {"lib/serviceradar_web_ng_web/live/spatial_live/field_survey_review.ex", :pattern_match, {744, 21}},
  {"lib/serviceradar_web_ng_web/plugs/upload_guard.ex", :guard_fail, 225},
  {"lib/serviceradar_web_ng_web/srql/builder.ex", :pattern_match_cov, {275, 8}},
  {"lib/serviceradar_web_ng_web/srql/page.ex", :pattern_match_cov, {938, 8}},
  {"lib/serviceradar_web_ng_web/srql/page.ex", :pattern_match_cov, {986, 8}},
  {"lib/serviceradar_web_ng_web/stats.ex", :pattern_match_cov, {991, 8}},
]
