[
  {"lib/mix/tasks/graph/ready.ex", :callback_info_missing, 1},
  {"lib/mix/tasks/graph/ready.ex", :unknown_function, {15, 14}},
  {"lib/mix/tasks/graph/ready.ex", :unknown_function, {26, 13}},
  {"lib/mix/tasks/serviceradar/maybe_test.ex", :callback_info_missing, 1},
  {"lib/mix/tasks/serviceradar/maybe_test.ex", :pattern_match_cov, {85, 9}},
  {"lib/mix/tasks/serviceradar/maybe_test.ex", :pattern_match_cov, {86, 9}},
  {"lib/mix/tasks/serviceradar/maybe_test.ex", :unknown_function, {16, 11}},
  {"lib/mix/tasks/serviceradar/maybe_test.ex", :unknown_function, {30, 16}},
  {"lib/mix/tasks/serviceradar/maybe_test.ex", :unknown_function, {32, 22}},
  {"lib/mix/tasks/serviceradar/maybe_test.ex", :unknown_function, {34, 11}},
  {"lib/mix/tasks/serviceradar/maybe_test.ex", :unknown_function, {68, 18}},
  {"lib/mix/tasks/serviceradar/maybe_test.ex", :unknown_function, {77, 13}},
  {"lib/serviceradar_web_ng/admin_api.ex", :unknown_type, {8, 50}},
  {"lib/serviceradar_web_ng/admin_api/http.ex", :pattern_match, {113, 8}},
  {"lib/serviceradar_web_ng/api/device_controller.ex", :pattern_match_cov, {396, 8}},
  {"lib/serviceradar_web_ng/api/device_controller.ex", :pattern_match_cov, {401, 8}},
  {"lib/serviceradar_web_ng/application.ex", :call, {154, 15}},
  {"lib/serviceradar_web_ng/application.ex", :no_return, {136, 8}},
  {"lib/serviceradar_web_ng/edge/bundle_generator.ex", :pattern_match_cov, {929, 8}},
  {"lib/serviceradar_web_ng/edge/bundle_generator.ex", :pattern_match_cov, {967, 8}},
  {"lib/serviceradar_web_ng/edge/onboarding_packages.ex", :pattern_match, {156, 13}},
  {"lib/serviceradar_web_ng/edge/workers/expire_packages_worker.ex", :call, {63, 27}},
  {"lib/serviceradar_web_ng/edge/workers/expire_packages_worker.ex", :no_return, {51, 40}},
  {"lib/serviceradar_web_ng/edge/workers/expire_packages_worker.ex", :no_return, {61, 8}},
  {"lib/serviceradar_web_ng/jobs/job_catalog.ex", :pattern_match, {210, 13}},
  {"lib/serviceradar_web_ng/jobs/job_catalog.ex", :pattern_match, {649, 8}},
  {"lib/serviceradar_web_ng/jobs/job_catalog.ex", :unused_fun, {220, 8}},
  {"lib/serviceradar_web_ng/jobs/job_catalog.ex", :unused_fun, {494, 8}},
  {"lib/serviceradar_web_ng/jobs/job_catalog.ex", :unused_fun, {501, 8}},
  {"lib/serviceradar_web_ng/jobs/job_catalog.ex", :unused_fun, {510, 8}},
  {"lib/serviceradar_web_ng/jobs/job_catalog.ex", :unused_fun, {517, 8}},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", :pattern_match_cov, {160, 8}},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", :pattern_match_cov, {194, 8}},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", :pattern_match_cov, {208, 8}},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", :pattern_match_cov, {289, 16}},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", :pattern_match_cov, {301, 8}},
  {"lib/serviceradar_web_ng/plugins/packages.ex", :guard_fail, 272},
  {"lib/serviceradar_web_ng/srql.ex", :pattern_match_cov, {77, 8}},
  {"lib/serviceradar_web_ng/srql.ex", :pattern_match_cov, {217, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_snapshot.ex", :pattern_match_cov, {156, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {379, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {414, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {528, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {836, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {1027, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {1393, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {1474, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {1498, 8}},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex", :pattern_match_cov, {1573, 8}},
  {"lib/serviceradar_web_ng/topology/runtime_graph.ex", :pattern_match_cov, {128, 7}},
  {"lib/serviceradar_web_ng_web/auth/guardian.ex", :callback_type_mismatch, {161, 7}},
  {"lib/serviceradar_web_ng_web/channels/topology_channel.ex", :guard_fail, 75},
  {"lib/serviceradar_web_ng_web/components/plugin_results.ex", :call, {285, 5}},
  {"lib/serviceradar_web_ng_web/components/plugin_results.ex", :call, {286, 14}},
  {"lib/serviceradar_web_ng_web/components/plugin_results.ex", :no_return, {235, 8}},
  {"lib/serviceradar_web_ng_web/components/plugin_results.ex", :no_return, {246, 8}},
  {"lib/serviceradar_web_ng_web/components/plugin_results.ex", :no_return, {284, 8}},
  {"lib/serviceradar_web_ng_web/components/plugin_results.ex", :pattern_match_cov, {254, 8}},
  {"lib/serviceradar_web_ng_web/components/plugin_results.ex", :pattern_match_cov, {319, 8}},
  {"lib/serviceradar_web_ng_web/components/settings_components.ex", :guard_fail, 287},
  {"lib/serviceradar_web_ng_web/components/srql_components.ex", :pattern_match_cov, {391, 8}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :call_without_opaque,
   {348, 5}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :guard_fail, 338},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match, {332, 7}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match, {333, 7}},
  {"lib/serviceradar_web_ng_web/controllers/api/topology_controller.ex", :pattern_match_cov,
   {121, 8}},
  {"lib/serviceradar_web_ng_web/controllers/oidc_controller.ex", :pattern_match_cov, {305, 8}},
  {"lib/serviceradar_web_ng_web/controllers/saml_controller.ex", :pattern_match, {222, 14}},
  {"lib/serviceradar_web_ng_web/controllers/saml_controller.ex", :pattern_match_cov, {403, 11}},
  {"lib/serviceradar_web_ng_web/controllers/saml_controller.ex", :pattern_match_cov, {417, 7}},
  {"lib/serviceradar_web_ng_web/controllers/topology_snapshot_controller.ex", :guard_fail, 116},
  {"lib/serviceradar_web_ng_web/controllers/user_session_controller.ex", :call, {67, 5}},
  {"lib/serviceradar_web_ng_web/controllers/user_session_controller.ex", :pattern_match, {81, 7}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/table.ex", :pattern_match_cov, {61, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/table.ex", :pattern_match_cov, {150, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries.ex", :guard_fail, 907},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries.ex", :pattern_match, {184, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries.ex", :pattern_match_cov, {247, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries.ex", :pattern_match_cov, {626, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries.ex", :pattern_match_cov, {646, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries.ex", :pattern_match_cov, {742, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries.ex", :pattern_match_cov, {1553, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries.ex", :pattern_match_cov, {1565, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/topology.ex", :pattern_match_cov, {41, 7}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/topology.ex", :pattern_match_cov, {247, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :guard_fail, 1797},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :guard_fail,
   {1772, 20}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match, 607},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match, 627},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match,
   {490, 11}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match,
   {576, 15}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov,
   {1705, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov,
   {1774, 9}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov,
   {1969, 8}},
  {"lib/serviceradar_web_ng_web/live/alert_live/show.ex", :pattern_match_cov, {326, 8}},
  {"lib/serviceradar_web_ng_web/live/analytics_live/index.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/device_live/index.ex", :exact_compare, 2969},
  {"lib/serviceradar_web_ng_web/live/device_live/index.ex", :pattern_match_cov, {602, 20}},
  {"lib/serviceradar_web_ng_web/live/device_live/index.ex", :pattern_match_cov, {1978, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/index.ex", :pattern_match_cov, {2007, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/index.ex", :pattern_match_cov, {2019, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/index.ex", :pattern_match_cov, {2535, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/index.ex", :pattern_match_cov, {2814, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :exact_compare, {2169, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match, {5897, 13}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match, {6150, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match, {6253, 13}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match, {7035, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match, {7249, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {1994, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {3630, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {4770, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {4779, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {4816, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {5845, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {6075, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {6087, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {6216, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {6222, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {6706, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {7045, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {7775, 7}},
  {"lib/serviceradar_web_ng_web/live/diagnostics_live/mtr_data.ex", :pattern_match_cov, {593, 8}},
  {"lib/serviceradar_web_ng_web/live/diagnostics_live/mtr_data.ex", :pattern_match_cov, {607, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {459, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {483, 8}},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex", :pattern_match_cov, {529, 8}},
  {"lib/serviceradar_web_ng_web/live/interface_live/index.ex", :guard_fail, 197},
  {"lib/serviceradar_web_ng_web/live/interface_live/show.ex", :pattern_match, {1718, 8}},
  {"lib/serviceradar_web_ng_web/live/interface_live/show.ex", :pattern_match, {1719, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :guard_fail, 7182},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :guard_fail, {5489, 42}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :guard_fail, {5928, 30}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :neg_guard_fail, {7146, 61}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :neg_guard_fail, {7518, 64}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match, {888, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match, {5487, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match, {6237, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {715, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {899, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {2904, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {4424, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {4989, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {4993, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {5122, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", :pattern_match_cov, {5497, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match, {263, 13}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {167, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {241, 7}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {257, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {268, 8}},
  {"lib/serviceradar_web_ng_web/live/log_live/show.ex", :pattern_match_cov, {745, 8}},
  {"lib/serviceradar_web_ng_web/live/metric_live/show.ex", :pattern_match_cov, {217, 8}},
  {"lib/serviceradar_web_ng_web/live/metric_live/show.ex", :pattern_match_cov, {437, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/dashboard.ex", :pattern_match, {1166, 83}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/dashboard.ex", :pattern_match_cov, {1346, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :call, {3727, 18}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match, 3759},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match, {1569, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match, {2607, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match, {2743, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, 1481},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, 1587},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, 2496},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {417, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {446, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {1515, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {1550, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {1674, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {2413, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {2986, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3109, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3198, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3213, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3258, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3361, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3479, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3509, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3790, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3812, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3829, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3835, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3854, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3875, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3960, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3961, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize.ex", :pattern_match_cov, {3962, 8}},
  {"lib/serviceradar_web_ng_web/live/service_live/index.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/service_live/index.ex", :pattern_match_cov, {465, 8}},
  {"lib/serviceradar_web_ng_web/live/service_live/index.ex", :pattern_match_cov, {477, 8}},
  {"lib/serviceradar_web_ng_web/live/service_live/index.ex", :pattern_match_cov, {489, 8}},
  {"lib/serviceradar_web_ng_web/live/service_live/index.ex", :pattern_match_cov, {538, 8}},
  {"lib/serviceradar_web_ng_web/live/service_live/index.ex", :pattern_match_cov, {567, 8}},
  {"lib/serviceradar_web_ng_web/live/service_live/index.ex", :pattern_match_cov, {701, 8}},
  {"lib/serviceradar_web_ng_web/live/service_live/index.ex", :pattern_match_cov, {804, 8}},
  {"lib/serviceradar_web_ng_web/live/service_live/show.ex", :pattern_match_cov, {615, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/auth_users_live.ex", :guard_fail, 639},
  {"lib/serviceradar_web_ng_web/live/settings/device_enrichment_rules_live.ex",
   :pattern_match_cov, {1111, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/integrations_live/index.ex", :call, {413, 33}},
  {"lib/serviceradar_web_ng_web/live/settings/integrations_live/index.ex", :pattern_match_cov,
   {513, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/mtr_profiles_live/index.ex", :guard_fail,
   {1069, 34}},
  {"lib/serviceradar_web_ng_web/live/settings/netflow_live/index.ex", :call, {263, 62}},
  {"lib/serviceradar_web_ng_web/live/settings/netflow_live/index.ex", :call, {284, 62}},
  {"lib/serviceradar_web_ng_web/live/settings/netflow_live/index.ex", :call, {306, 66}},
  {"lib/serviceradar_web_ng_web/live/settings/netflow_live/index.ex", :pattern_match_cov,
   {890, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/networks_live/index.ex", :call, {317, 32}},
  {"lib/serviceradar_web_ng_web/live/settings/networks_live/index.ex", :pattern_match_cov,
   {3145, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/networks_live/index.ex", :pattern_match_cov,
   {3804, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/networks_live/index.ex", :pattern_match_cov,
   {3811, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/networks_live/index.ex", :unused_fun, {840, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/rbac_live.ex", :pattern_match, {1144, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/snmp_profiles_live/index.ex", :call, {296, 18}},
  {"lib/serviceradar_web_ng_web/live/settings/snmp_profiles_live/index.ex", :exact_compare,
   {629, 22}},
  {"lib/serviceradar_web_ng_web/live/settings/snmp_profiles_live/index.ex", :pattern_match_cov,
   {624, 9}},
  {"lib/serviceradar_web_ng_web/live/settings/sysmon_profiles_live/index.ex", :pattern_match_cov,
   {1101, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/sysmon_profiles_live/index.ex", :pattern_match_cov,
   {1108, 8}},
  {"lib/serviceradar_web_ng_web/plugs/api_auth.ex", :pattern_match, {309, 8}},
  {"lib/serviceradar_web_ng_web/plugs/api_auth.ex", :pattern_match_cov, {164, 16}},
  {"lib/serviceradar_web_ng_web/plugs/api_auth.ex", :pattern_match_cov, {194, 16}},
  {"lib/serviceradar_web_ng_web/srql/builder.ex", :pattern_match_cov, {212, 8}},
  {"lib/serviceradar_web_ng_web/srql/builder.ex", :pattern_match_cov, {650, 8}},
  {"lib/serviceradar_web_ng_web/srql/page.ex", :pattern_match_cov, {314, 8}},
  {"lib/serviceradar_web_ng_web/srql/page.ex", :pattern_match_cov, {523, 8}}
]
