[
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex",
   "The pattern can never match the type {:error, [binary()] | {:first_party_dashboard_asset_unavailable, atom()}}."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex",
   "The pattern can never match the type {:error, [binary()]}."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", "Function package_attrs/3 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", "Function bundle_digest/1 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", "Function upsert_package/2 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex",
   "Function ensure_package_enabled/2 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex",
   "Function ensure_route_instance/3 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", "Function fetch_route_instance/2 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex",
   "Function create_route_instance/3 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex",
   "Function update_route_instance/3 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", "Function maybe_mark_default/3 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex",
   "Function fetch_default_dashboard_instance/1 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/first_party_packages.ex", "Function service_version/0 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function fetch_value/2 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex",
   "The pattern can never match the type {:error, :invalid_attributes | [binary()]}."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "The pattern can never match the type {:error, [binary()]}."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "The pattern can never match the type {:error, _}."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function upsert_package/2 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function store_wasm_blob/4 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function check_version_overwrite/3 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function fetch_existing_version/3 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function check_slug_ownership/3 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function finalize_publish/7 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function do_publish_write/5 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function maybe_bind_route/4 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function import_options/1 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function import_github_options/3 will never be called."},
  {"lib/serviceradar_web_ng/dashboards/packages.ex", "Function update_resource_with_opts/2 will never be called."},
  {"lib/serviceradar_web_ng/devices/manual_device_creator.ex",
   "The pattern pattern <__scope@1, __uid@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng/devices/manual_device_creator.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng/edge/onboarding_token.ex",
   "The pattern pattern <_parts@1, __payload@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng/field_survey_arrow_ingest.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng/field_survey_review.ex", "Invalid type specification for function build_review."},
  {"lib/serviceradar_web_ng/field_survey_review.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng/field_survey_review.ex", "The pattern can never match the type [any(), ...]."},
  {"lib/serviceradar_web_ng/field_survey_review.ex", "The pattern can never match the type _, [any()], binary()."},
  {"lib/serviceradar_web_ng/field_survey_review.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng/field_survey_review.ex",
   "The pattern pattern <__point@1, __polygon@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng/field_survey_room_artifacts.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng/dashboards/frame_runner.ex", :pattern_match_cov},
  {"lib/serviceradar_web_ng/plugins/first_party_importer.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng/plugins/first_party_release_client.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex",
   "The pattern can never match the type {:error, {:invalid_manifest, [binary()]}}."},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", "Function dashboard_renderer_path/2 will never be called."},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", "Function fetch_renderer_artifact/3 will never be called."},
  {"lib/serviceradar_web_ng/plugins/github_importer.ex", "The pattern can never match the type {:error, [binary()]}."},
  {"lib/serviceradar_web_ng/plugins/packages.ex", :guard_fail},
  {"lib/serviceradar_web_ng/remote_access_desktop_targets.ex",
   "The pattern pattern <__map@1, __keys@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng/topology/god_view_stream.ex",
   "The pattern variable _edges@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/camera_multiview.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/channels/dashboard_frame_channel.ex",
   "The pattern can never match the type {:ok, pid()}."},
  {"lib/serviceradar_web_ng_web/channels/dashboard_frame_channel.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng_web/controllers/api/addon_package_controller.ex",
   "The pattern can never match the type {:binary, binary()}."},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", "The pattern can never match the type {:error, _}."},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex",
   "The pattern can never match the type \n  {:error,\n   :already_activated\n   | :already_delivered\n   | :deleted\n   | :expired\n   | :invalid_token\n   | :no_token\n   | :not_found\n   | :revoked}\n."},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", "Function default_nats_url/0 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex",
   "Function wrap_bundle_error/1 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", "Function bundle_generator/0 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex",
   "The pattern can never match the type {:failure, _}."},
  {"lib/serviceradar_web_ng_web/controllers/api/remote_access_session_controller.ex",
   "The pattern variable __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/controllers/api/remote_access_target_intent_controller.ex",
   "The pattern variable _reason@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex",
   "The pattern can never match the type {:error, _}."},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex",
   "Function send_field_survey_export/3 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex",
   "Function field_survey_svg/1 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", "Function svg_grid/0 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", "Function rssi_color/1 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", "Function svg_number/1 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/api/spatial_controller.ex", "Function xml_escape/1 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/cli_auth_controller.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex",
   "The pattern can never match the type {:error, :invalid_attributes | [binary()]}."},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex",
   "Function record_publish_audit/3 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex",
   "Function result_route_slug/1 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/dashboard_package_publish_controller.ex",
   "Function respond_publish/2 will never be called."},
  {"lib/serviceradar_web_ng_web/controllers/saml_controller.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/table.ex",
   "The pattern pattern _ = _results@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/topology.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/topology.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/admin/addon_package_live/index.ex",
   "The pattern pattern _ = __summary@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/admin/dashboard_package_live/index.ex",
   "The pattern can never match the type {:error, _}."},
  {"lib/serviceradar_web_ng_web/live/admin/dashboard_package_live/index.ex",
   "Function maybe_enable_after_import/3 will never be called."},
  {"lib/serviceradar_web_ng_web/live/admin/dashboard_package_live/index.ex",
   "Function maybe_create_instance_after_import/3 will never be called."},
  {"lib/serviceradar_web_ng_web/live/admin/dashboard_package_live/index.ex",
   "The pattern pattern _ = _upload_name@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/analytics_live/index.ex", "The pattern can never match the type true."},
  {"lib/serviceradar_web_ng_web/live/authored_dashboard_live/canvas_state.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng_web/live/authored_dashboard_live/panel_components.ex",
   "The pattern pattern <_value@1, _min@1, _max@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/authored_dashboard_live/panel_components.ex",
   "The pattern pattern <__value@1, _min@1, __max@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/data.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/data.ex", "The pattern can never match the type :bps."},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/data.ex", "The pattern can never match the type _, :latency_ms."},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/index.ex",
   "The pattern pattern <__instances@1, __route_slug@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/dashboard_package_live/show.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng_web/live/dashboard_package_live/show.ex",
   "The pattern pattern _ = __data_frames@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/device_live/device_summary_components.ex",
   "The pattern pattern _ = __row@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/device_live/endpoint_inventory_data.ex", :guard_fail},
  {"lib/serviceradar_web_ng_web/live/device_live/endpoint_inventory_runtime.ex", :pattern_match_cov},
  {"lib/serviceradar_web_ng_web/live/device_live/process_metrics_components.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng_web/live/device_live/remote_access_data.ex",
   "The pattern variable __device_row@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/device_live/remote_access_data.ex", "The pattern can never match the type map()."},
  {"lib/serviceradar_web_ng_web/live/device_live/remote_access_data.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/device_live/virtualization_components.ex",
   "The pattern can never match the type binary(), <<_::56>>."},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", "The pattern can never match the type true."},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex",
   "The pattern pattern _ = __metadata@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex",
   "The pattern pattern _ = __active@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/diagnostics_live/mtr_data.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex",
   "The pattern pattern _ = __event@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex",
   "The pattern pattern <__event@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/event_live/show.ex",
   "The pattern pattern _ = __map@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/interface_live/show.ex",
   "The pattern can never match the type _, binary(), binary(), true."},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex", "The pattern can never match the type true."},
  {"lib/serviceradar_web_ng_web/live/log_live/index.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/security_live/index.ex",
   "The pattern pattern _ = __row@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/observability_health_live/index.ex", :guard_fail},
  {"lib/serviceradar_web_ng_web/live/settings/ansible_live.ex",
   "The pattern can never match the type {:error, :bad_cron | {:bad_extra_vars, binary()}}."},
  {"lib/serviceradar_web_ng_web/live/settings/ansible_live.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/settings/ansible_live.ex",
   "The pattern can never match the type [map()] | %{:__exception__ => true, :__struct__ => atom(), atom() => _}."},
  {"lib/serviceradar_web_ng_web/live/settings/ansible_live.ex",
   "The pattern can never match the type {:ok, _, [map()]}."},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/event_show.ex",
   "Type mismatch in call without opaque term in can_view?."},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/event_show.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/events.ex",
   "Type mismatch in call without opaque term in can_view?."},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/events.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/events.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/history.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/serviceradar_web_ng_web/live/settings/audit_live/lockouts.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/serviceradar_web_ng_web/live/settings/cli_auth_policy_live.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/serviceradar_web_ng_web/live/settings/cli_sessions_live.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/serviceradar_web_ng_web/live/settings/integrations_live/index.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/settings/network_credential_rules_live.ex",
   "The pattern pattern _ = __agents@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/settings/remote_access_desktop_targets_live.ex",
   "The pattern pattern <_attrs@1, __target@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar_web_ng_web/live/spatial_live/field_survey_review.ex",
   "The pattern can never match the type {:error, _}."},
  {"lib/serviceradar_web_ng_web/plugs/upload_guard.ex", "The guard clause can never succeed."},
  {"lib/serviceradar_web_ng_web/plugs/upload_guard.ex", "The function call replace will not succeed."},

  # Exact locations for dynamic Ash/LiveView and datasvc call paths. Keep these
  # line-specific so newly introduced Dialyzer findings remain visible.
  {"lib/serviceradar_web_ng/dashboards/authored.ex", :call_without_opaque, 12},
  {"lib/serviceradar_web_ng/dashboards/authored.ex", :pattern_match_cov, 14},
  {"lib/serviceradar_web_ng/edge/component_templates.ex", :pattern_match, 93},
  {"lib/serviceradar_web_ng/edge/component_templates.ex", :pattern_match, {63, 13}},
  {"lib/serviceradar_web_ng/edge/component_templates.ex", :pattern_match_cov, {79, 16}},
  {"lib/serviceradar_web_ng/edge/component_templates.ex", :pattern_match, {96, 7}},
  {"lib/serviceradar_web_ng/edge/component_templates.ex", :unused_fun, {150, 8}},
  {"lib/serviceradar_web_ng/plugins/assignments.ex", :pattern_match_cov, {536, 8}},
  {"lib/serviceradar_web_ng/plugins/assignments.ex", :pattern_match_cov, {542, 8}},
  {"lib/serviceradar_web_ng/plugins/blob_retention.ex", :pattern_match_cov, {228, 8}},
  {"lib/serviceradar_web_ng/plugins/first_party_importer.ex", :pattern_match_cov, {361, 8}},
  {"lib/serviceradar_web_ng/plugins/packages.ex", :call_without_opaque, {245, 27}},
  {"lib/serviceradar_web_ng_web/auth/password_reset_delivery.ex", :pattern_match_cov, {65, 7}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match, {617, 20}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match, {628, 20}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match, {639, 20}},
  {"lib/serviceradar_web_ng_web/controllers/api/edge_controller.ex", :pattern_match, {647, 16}},
  {"lib/serviceradar_web_ng_web/controllers/api/proxmox_console_session_controller.ex", :call_without_opaque, {184, 73}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries/series_data.ex", :pattern_match_cov, {391, 8}},
  {"lib/serviceradar_web_ng_web/dashboard/plugins/timeseries/series_data.ex", :pattern_match, {393, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match, {951, 15}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov, {2650, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov, {3730, 13}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov, {3760, 8}},
  {"lib/serviceradar_web_ng_web/live/admin/plugin_package_live/index.ex", :pattern_match_cov, {4394, 8}},
  {"lib/serviceradar_web_ng_web/live/dashboard_live/index/fieldsurvey_panel.ex", :pattern_match_cov, {238, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/all_metadata_components.ex", :pattern_match_cov, {267, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/all_metadata_components.ex", :pattern_match_cov, {354, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/anomaly_capacity_components.ex", :pattern_match_cov, {1572, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/metric_section_components.ex", :pattern_match_cov, {129, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/run_task_variables.ex", :pattern_match_cov, {121, 16}},
  {"lib/serviceradar_web_ng_web/live/device_live/show.ex", :pattern_match_cov, {1678, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/sysmon_metrics/identity.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/device_live/sysmon_metrics/reference_lines.ex", :pattern_match_cov, {78, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :pattern_match_cov, {626, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :pattern_match_cov, {670, 8}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :call_without_opaque, {689, 20}},
  {"lib/serviceradar_web_ng_web/live/device_live/visibility_components.ex", :pattern_match_cov, {703, 8}},
  {"lib/serviceradar_web_ng_web/live/netflow_live/visualize/events.ex", :pattern_match, 1},
  {"lib/serviceradar_web_ng_web/live/settings/anomaly_detection_live.ex", :pattern_match_cov, {740, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/prefix_tags_live.ex", :pattern_match_cov, {729, 9}},
  {"lib/serviceradar_web_ng_web/live/settings/rules_live/index.ex", :pattern_match, {833, 13}},
  {"lib/serviceradar_web_ng_web/live/settings/rules_live/index.ex", :unused_fun, {845, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/rules_live/index.ex", :unused_fun, {874, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/rules_live/index.ex", :unused_fun, {900, 8}},
  {"lib/serviceradar_web_ng_web/live/settings/threat_intel_live/index.ex", :pattern_match, {124, 11}},
  {"lib/serviceradar_web_ng_web/stats.ex", :pattern_match_cov, {626, 8}}
]
