-- Rebuild for a warehouse created before daily partitioning.
-- This file DOCUMENTS a destructive recovery procedure. It does not run it.
-- Applying 0001-0014 in order on a fresh warehouse must be a no-op here, so
-- the DROP statements below are commented out. Run them by hand,
-- deliberately, only after reading this.
--
-- When it applies: 0001-0004 previously created these tables with
-- PRIMARY KEY (id) and no PARTITION BY. StarRocks can neither add
-- partitioning to an existing table nor change a primary key with ALTER, so
-- the retention property those tables now carry (`partition_live_number`) is
-- rejected on them and the warehouse grows without bound. Core logs a
-- retention warning on such a warehouse; that warning is the signal to run
-- this procedure.
--
-- When it does NOT apply: a warehouse created from the partitioned DDL
-- already has everything this would rebuild. Skip the file entirely.
--
-- Preconditions: StarRocks must still be a shadow copy, i.e.
-- `cutoverDatasets` is empty, so CNPG stays authoritative and EventWriter
-- refills the warehouse from JetStream as new telemetry arrives. Do NOT run
-- this on a warehouse that already serves a cut-over dataset until that
-- dataset has been returned to CNPG.
--
-- Procedure, in order. The hourly materialized views read the base tables, so
-- they are dropped first and rebuilt by re-applying 0005:
--
--   DROP MATERIALIZED VIEW IF EXISTS serviceradar.ocsf_network_activity_hourly;
--   DROP MATERIALIZED VIEW IF EXISTS serviceradar.timeseries_metrics_hourly;
--   DROP MATERIALIZED VIEW IF EXISTS serviceradar.events_hourly;
--
--   DROP TABLE IF EXISTS serviceradar.ocsf_network_activity;
--   DROP TABLE IF EXISTS serviceradar.timeseries_metrics;
--   DROP TABLE IF EXISTS serviceradar.logs;
--   DROP TABLE IF EXISTS serviceradar.events;
--
-- then:
--   1. re-apply 0001, 0002, 0003, 0004 (they now create partitioned tables)
--   2. re-apply 0005 (hourly materialized views)
--   3. backfill history, newest first, from CNPG
--
-- Do NOT replay 0006-0015. Every column they add is already declared in
-- 0001-0004, and re-running an ADD COLUMN fails once the column exists.
SELECT 'partitioned telemetry rebuild is documented; not executed' AS status;
