{{- include "sr-edge.validate" . }}
{{- if and .Values.agent.enabled .Values.serviceAccount.agent.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sr-edge.agentServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sr-edge.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  {{- with .Values.serviceAccount.agent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if and .Values.k8sInventory.enabled .Values.serviceAccount.inventory.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sr-edge.inventoryServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sr-edge.labels" . | nindent 4 }}
    app.kubernetes.io/component: k8s-inventory
  {{- with .Values.serviceAccount.inventory.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
