# gazelle:ignore
package(default_visibility = ["//visibility:public"])

exports_files([
    "config.inventory_sync.schema.json",
    "main.go",
    "plugin.inventory_sync.yaml",
    "plugin.yaml",
])

filegroup(
    name = "srcs",
    srcs = glob(
        ["**"],
        exclude = [
            "dist/**",
            "manifest.json",
        ],
    ),
)
