defmodule ServiceRadar.Monitoring.Event do
  @moduledoc """
  Event resource for recording system and monitoring events.

  Events are immutable records of things that happened in the system.
  They can be generated by service checks, agents, pollers, or the
  system itself.

  ## Event Categories

  - `:check` - Service check events (success, failure, warning)
  - `:alert` - Alert lifecycle events
  - `:agent` - Agent status changes
  - `:poller` - Poller status changes
  - `:device` - Device discovery/changes
  - `:system` - System-level events
  - `:audit` - Audit log events

  ## Severity Levels

  - 0: Unknown
  - 1: Info
  - 2: Warning
  - 3: Error
  - 4: Critical
  """

  use Ash.Resource,
    domain: ServiceRadar.Monitoring,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer]

  postgres do
    table "monitoring_events"
    repo ServiceRadar.Repo
  end

  multitenancy do
    strategy :attribute
    attribute :tenant_id
    global? true
  end

  code_interface do
    define :list_by_category, action: :by_category, args: [:category]
    define :list_by_device, action: :by_device, args: [:device_uid]
    define :list_recent, action: :recent
  end

  actions do
    defaults [:read]

    read :by_category do
      argument :category, :atom, allow_nil?: false
      filter expr(category == ^arg(:category))
    end

    read :by_severity do
      argument :min_severity, :integer, allow_nil?: false
      filter expr(severity >= ^arg(:min_severity))
    end

    read :by_device do
      argument :device_uid, :string, allow_nil?: false
      filter expr(device_uid == ^arg(:device_uid))
    end

    read :by_agent do
      argument :agent_uid, :string, allow_nil?: false
      filter expr(agent_uid == ^arg(:agent_uid))
    end

    read :by_alert do
      argument :alert_id, :uuid, allow_nil?: false
      filter expr(alert_id == ^arg(:alert_id))
    end

    read :recent do
      description "Events from last hour"
      filter expr(occurred_at > ago(1, :hour))
    end

    read :in_time_range do
      argument :start_time, :utc_datetime, allow_nil?: false
      argument :end_time, :utc_datetime, allow_nil?: false
      filter expr(occurred_at >= ^arg(:start_time) and occurred_at <= ^arg(:end_time))
    end

    create :record do
      description "Record a new event"

      accept [
        :category,
        :event_type,
        :severity,
        :message,
        :details,
        :source_type,
        :source_id,
        :source_name,
        :target_type,
        :target_id,
        :target_name,
        :device_uid,
        :agent_uid,
        :alert_id,
        :metadata,
        :tags,
        :actor_type,
        :actor_id,
        :actor_name,
        :client_ip
      ]

      change set_attribute(:occurred_at, &DateTime.utc_now/0)
    end

    create :record_at_time do
      description "Record an event with specific timestamp"

      accept [
        :category,
        :event_type,
        :severity,
        :message,
        :details,
        :source_type,
        :source_id,
        :source_name,
        :target_type,
        :target_id,
        :target_name,
        :device_uid,
        :agent_uid,
        :alert_id,
        :metadata,
        :tags,
        :occurred_at,
        :actor_type,
        :actor_id,
        :actor_name,
        :client_ip
      ]
    end
  end

  policies do
    # Import common policy checks

    # Super admins bypass all policies (platform-wide access)
    bypass always() do
      authorize_if actor_attribute_equals(:role, :super_admin)
    end

    # TENANT ISOLATION: Events are audit/log data for a tenant
    # Must be strictly isolated

    # Read access: Must be authenticated AND in same tenant
    policy action_type(:read) do
      authorize_if expr(
                     ^actor(:role) in [:viewer, :operator, :admin] and
                       tenant_id == ^actor(:tenant_id)
                   )
    end

    # Record events: Operators/admins in same tenant
    policy action([:record, :record_at_time]) do
      authorize_if expr(
                     ^actor(:role) in [:operator, :admin] and
                       tenant_id == ^actor(:tenant_id)
                   )
    end
  end

  attributes do
    uuid_primary_key :id

    attribute :category, :atom do
      allow_nil? false
      public? true
      constraints one_of: [:check, :alert, :agent, :poller, :device, :system, :audit]
      description "Event category"
    end

    attribute :event_type, :string do
      allow_nil? false
      public? true
      description "Specific event type (e.g., 'check.success', 'agent.connected')"
    end

    attribute :severity, :integer do
      default 1
      public? true
      description "Severity level (0=unknown, 1=info, 2=warning, 3=error, 4=critical)"
    end

    attribute :message, :string do
      allow_nil? false
      public? true
      description "Human-readable event message"
    end

    attribute :details, :string do
      public? true
      description "Detailed event information"
    end

    # Source entity
    attribute :source_type, :atom do
      public? true
      constraints one_of: [:service_check, :alert, :agent, :poller, :device, :user, :system]
      description "Type of source that generated this event"
    end

    attribute :source_id, :string do
      public? true
      description "ID of the source entity"
    end

    attribute :source_name, :string do
      public? true
      description "Display name of the source"
    end

    # Target entity (what the event is about)
    attribute :target_type, :atom do
      public? true
      constraints one_of: [:service_check, :alert, :agent, :poller, :device, :user, :system]
      description "Type of entity this event is about"
    end

    attribute :target_id, :string do
      public? true
      description "ID of the target entity"
    end

    attribute :target_name, :string do
      public? true
      description "Display name of the target"
    end

    # Related entities
    attribute :device_uid, :string do
      public? true
      description "Related device UID"
    end

    attribute :agent_uid, :string do
      public? true
      description "Related agent UID"
    end

    attribute :alert_id, :uuid do
      public? true
      description "Related alert ID"
    end

    # Event metadata
    attribute :metadata, :map do
      default %{}
      public? true
      description "Additional event data"
    end

    attribute :tags, {:array, :string} do
      default []
      public? true
      description "Event tags for filtering"
    end

    # Actor information (who/what caused the event)
    attribute :actor_type, :atom do
      public? true
      constraints one_of: [:user, :system, :agent, :poller, :scheduler]
      description "Type of actor that caused this event"
    end

    attribute :actor_id, :string do
      public? true
      description "ID of the actor"
    end

    attribute :actor_name, :string do
      public? true
      description "Display name of the actor"
    end

    attribute :client_ip, :string do
      public? true
      description "Client IP address (for user-initiated events)"
    end

    # Timestamp
    attribute :occurred_at, :utc_datetime do
      allow_nil? false
      public? true
      description "When the event occurred"
    end

    # Multi-tenancy
    attribute :tenant_id, :uuid do
      allow_nil? false
      public? false
      description "Tenant this event belongs to"
    end

    create_timestamp :created_at
  end

  relationships do
    belongs_to :device, ServiceRadar.Inventory.Device do
      source_attribute :device_uid
      destination_attribute :uid
      allow_nil? true
      public? true
    end

    belongs_to :agent, ServiceRadar.Infrastructure.Agent do
      source_attribute :agent_uid
      destination_attribute :uid
      allow_nil? true
      public? true
    end

    belongs_to :alert, ServiceRadar.Monitoring.Alert do
      source_attribute :alert_id
      destination_attribute :id
      allow_nil? true
      public? true
    end
  end

  calculations do
    calculate :severity_label,
              :string,
              expr(
                cond do
                  severity == 0 -> "Unknown"
                  severity == 1 -> "Info"
                  severity == 2 -> "Warning"
                  severity == 3 -> "Error"
                  severity == 4 -> "Critical"
                  true -> "Unknown"
                end
              )

    calculate :severity_color,
              :string,
              expr(
                cond do
                  severity == 4 -> "red"
                  severity == 3 -> "red"
                  severity == 2 -> "yellow"
                  severity == 1 -> "blue"
                  true -> "gray"
                end
              )

    calculate :category_label,
              :string,
              expr(
                cond do
                  category == :check -> "Check"
                  category == :alert -> "Alert"
                  category == :agent -> "Agent"
                  category == :poller -> "Poller"
                  category == :device -> "Device"
                  category == :system -> "System"
                  category == :audit -> "Audit"
                  true -> "Unknown"
                end
              )
  end
end
