[package]
name = "serviceradar-rperf-checker"
version = "1.0.28"
edition = "2021"
description = "gRPC plugin for rperf network performance testing tool"
authors = ["Michael Freeman <mfreeman451@gmail.com>"]
license = "Apache-2.0"

[dependencies]
chrono = "0.4"
rperf = "0.1.18"
tokio = { version = "1.28", features = ["full"] }
prost = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
tonic-health = "0.9"
tonic-reflection = "0.9"
tonic = { version = "0.9", features = ["tls"] }
clap = "~2.33.3"
anyhow = "1.0"

[build-dependencies]
tonic-build = "0.9"