[package]
name = "serviceradar-host-metrics-checker"
version = "1.0.31"
edition = "2021"
description = "gRPC plugin for ServiceRadar host metrics collection"
authors = ["Michael Freeman <mfreeman@carverauto.dev>"]
license = "Apache-2.0"

[dependencies]
chrono = "0.4"
tokio = { version = "1.44", features = ["full"] }
prost = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
tonic-health = "0.9"
tonic-reflection = "0.9"
tonic = { version = "0.9", features = ["tls"] }

[build-dependencies]
tonic-build = "0.9"

