[
  {"lib/serviceradar/observability/anomaly_detection/counter_normalizer.ex", :pattern_match},
  {"lib/mix/tasks/serviceradar.dire_remediation.ex",
   "The pattern pattern {'error', _error@1} can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/actors/device.ex",
   "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/actors/telemetry.ex", "Function metrics/0 has no local return."},
  {"lib/serviceradar/agent_commands/status_handler.ex",
   "The pattern variable __data@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/agent_config/compilers/mapper_compiler.ex",
   "The pattern pattern <__payload@1, __payload_keys@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/automation/ansible/event_ingestor.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/automation/ansible/ingestor_ash_actions.ex",
   "The pattern can never match the type \n  {:error,\n   %{\n     :__exception__ => true,\n     :__struct__ => atom(),\n     :bread_crumbs => [binary()],\n     :class => :forbidden | :framework | :invalid | :unknown,\n     :context => map(),\n     :stacktrace => nil | %Splode.Stacktrace{:stacktrace => [any()]},\n     :vars => [{_, _}],\n     atom() => _\n   }}\n  | {:ok, nil | struct()}\n."},
  {"lib/serviceradar/automation/ansible/northbound_bridge.ex",
   "The pattern can never match the type \n  {:error,\n   %{\n     :__exception__ => true,\n     :__struct__ => atom(),\n     :bread_crumbs => [binary()],\n     :class => :forbidden | :framework | :invalid | :unknown,\n     :context => map(),\n     :stacktrace => nil | %Splode.Stacktrace{:stacktrace => [any()]},\n     :vars => [{_, _}],\n     atom() => _\n   }}\n  | {:ok, nil | struct()}\n."},
  {"lib/serviceradar/automation/ansible/retention_worker.ex",
   "The pattern can never match the type \n  {:ok,\n   %{:detail_runs_pruned => non_neg_integer(), :summary_runs_pruned => non_neg_integer()}}\n."},
  {"lib/serviceradar/automation/ansible/schedule_evaluator_worker.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/automation/northbound/ansible_action_sync.ex",
   "The pattern can never match the type \n  {:error,\n   %{\n     :__exception__ => true,\n     :__struct__ => atom(),\n     :bread_crumbs => [binary()],\n     :class => :forbidden | :framework | :invalid | :unknown,\n     :context => map(),\n     :stacktrace => nil | %Splode.Stacktrace{:stacktrace => [any()]},\n     :vars => [{_, _}],\n     atom() => _\n   }}\n  | {:ok, nil | struct()}\n."},
  {"lib/serviceradar/automation/northbound/command_result_handler.ex",
   "The pattern can never match the type \n  {:error,\n   %{\n     :__exception__ => true,\n     :__struct__ => atom(),\n     :bread_crumbs => [binary()],\n     :class => :forbidden | :framework | :invalid | :unknown,\n     :context => map(),\n     :stacktrace => nil | %Splode.Stacktrace{:stacktrace => [any()]},\n     :vars => [{_, _}],\n     atom() => _\n   }}\n  | {:ok, nil | struct()}\n."},
  {"lib/serviceradar/automation/northbound/command_result_handler.ex",
   "The pattern can never match the type true."},
  {"lib/serviceradar/automation/northbound/dispatcher.ex", "The guard clause can never succeed."},
  {"lib/serviceradar/automation/northbound/dispatcher.ex",
   "The pattern can never match the type \n  {:error,\n   %{\n     :__exception__ => true,\n     :__struct__ => atom(),\n     :bread_crumbs => [binary()],\n     :class => :forbidden | :framework | :invalid | :unknown,\n     :context => map(),\n     :stacktrace => nil | %Splode.Stacktrace{:stacktrace => [any()]},\n     :vars => [{_, _}],\n     atom() => _\n   }}\n  | {:ok, nil | struct()}\n."},
  {"lib/serviceradar/automation/northbound/dispatcher.ex",
   "Function launch_ansible_run/4 has no local return."},
  {"lib/serviceradar/automation/northbound/dispatcher.ex",
   "The function call launch will not succeed."},
  {"lib/serviceradar/automation/northbound/dispatcher.ex",
   "Function mark_ansible_dispatched/3 will never be called."},
  {"lib/serviceradar/automation/northbound/dispatcher.ex",
   "Function mark_invocation_running/2 will never be called."},
  {"lib/serviceradar/automation/northbound/dispatcher.ex",
   "The pattern pattern <__invocation@1, __reason@1, __actor@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/automation/northbound/event_handler_runner.ex",
   "The pattern pattern <__resolver@1, __context@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/automation/northbound/event_handler_runner.ex",
   "The pattern pattern <__context@1, __path@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/automation/northbound/invocation_service.ex",
   "The pattern pattern <__map@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/automation/northbound/plugin_action_sync.ex",
   "The guard clause can never succeed."},
  {"lib/serviceradar/automation/northbound/poll_worker.ex",
   "The pattern can never match the type \n  {:error,\n   :canceled\n   | :expired\n   | %{\n       :__exception__ => true,\n       :__struct__ => atom(),\n       :bread_crumbs => [any()],\n       :class => :forbidden | :framework | :invalid | :unknown,\n       :context => map(),\n       :stacktrace => nil | map(),\n       :vars => [any()],\n       atom() => _\n     }}\n."},
  {"lib/serviceradar/camera/inventory_ingestor.ex",
   "The pattern pattern {_device@3 = \#{'__struct__':='Elixir.ServiceRadar.Inventory.Device'}, _target_uid@1} can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/camera/inventory_ingestor.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/camera/inventory_ingestor.ex",
   "The pattern pattern <__device@1, __attrs@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/camera/inventory_ingestor.ex",
   "The pattern variable __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/camera/inventory_ingestor.ex",
   "Function camera_device_update_attrs/1 will never be called."},
  {"lib/serviceradar/camera/inventory_ingestor.ex",
   "The pattern variable __mac@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/camera/inventory_ingestor.ex",
   "The pattern pattern <__descriptor@1, __actor@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/cluster/cluster_health.ex", "The guard clause can never succeed."},
  {"lib/serviceradar/cluster/coordinator_manager.ex",
   "The pattern can never match the type :ok | {:error, :not_found}."},
  {"lib/serviceradar/cluster/coordinator_manager.ex",
   "The pattern pattern {'error', __reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/cluster/gateway_registration_worker.ex",
   "The pattern variable _error@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/cluster/registration_worker.ex",
   "The pattern pattern {'error', _reason@2} can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/cluster/registration_worker.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/cluster/startup_migrations.ex",
   "The pattern can never match the type {:error, _}."},
  {"lib/serviceradar/cluster/startup_migrations.ex",
   "The pattern can never match the type {:error, _} | {:ok, :ok | {:retry, map()}}."},
  {"lib/serviceradar/cluster/startup_migrations.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/cluster/startup_migrations.ex",
   "The pattern can never match the type {:error, _} | {:ok, {:retry, map()}}."},
  {"lib/serviceradar/core/result_processor.ex", "The pattern can never match the type true."},
  {"lib/serviceradar/core/stats_aggregator.ex",
   "Unknown type: ServiceRadar.Core.StatsAggregator.Snapshot.t/0."},
  {"lib/serviceradar/core/stats_aggregator.ex",
   "Unknown type: ServiceRadar.Core.StatsAggregator.Meta.t/0."},
  {"lib/serviceradar/credentials/network_credential_rule_test_plan.ex",
   "The guard clause can never succeed."},
  {"lib/serviceradar/credentials/ssh_private_key_credential.ex",
   "The pattern variable __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/dashboards/package_import.ex",
   "The pattern can never match the type {:error, [binary()]}."},
  {"lib/serviceradar/dashboards/validations/manifest.ex",
   "The pattern can never match the type {:error, [binary()]}."},
  {"lib/serviceradar/edge/agent_config_generator.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/agent_config_generator.ex",
   "The pattern pattern <__map@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/agent_config_generator.ex",
   "The pattern can never match the type map()."},
  {"lib/serviceradar/edge/agent_gateway_sync.ex",
   "Function complete_agent_device_sync/5 has no local return."},
  {"lib/serviceradar/edge/agent_gateway_sync.ex",
   "The function call extract_strong_identifiers will not succeed."},
  {"lib/serviceradar/edge/agent_gateway_sync.ex",
   "The pattern can never match the type \n  {:error,\n   %{\n     :__exception__ => true,\n     :__struct__ => atom(),\n     :bread_crumbs => [any()],\n     :class => :forbidden | :framework | :invalid | :unknown,\n     :context => map(),\n     :stacktrace => nil | map(),\n     :vars => [any()],\n     atom() => _\n   }}\n  | {:ok,\n     [struct()]\n     | %{\n         :__struct__ => Ash.Page.Keyset | Ash.Page.Offset,\n         :count => integer(),\n         :limit => integer(),\n         :more? => boolean(),\n         :rerun => {map(), [any()]},\n         :results => [map()],\n         :after => nil | binary(),\n         :before => nil | binary(),\n         :offset => integer()\n       }}\n."},
  {"lib/serviceradar/edge/agent_gateway_sync.ex",
   "The pattern can never match the type \n  {:error,\n   %{\n     :__exception__ => true,\n     :__struct__ => atom(),\n     :bread_crumbs => [any()],\n     :class => :forbidden | :framework | :invalid | :unknown,\n     :context => map(),\n     :stacktrace => nil | map(),\n     :vars => [any()],\n     atom() => _\n   }}\n  | {:ok,\n     %{\n       :__struct__ => Ash.Page.Keyset | Ash.Page.Offset,\n       :count => integer(),\n       :limit => integer(),\n       :more? => boolean(),\n       :rerun => {map(), [any()]},\n       :results => [map()],\n       :after => nil | binary(),\n       :before => nil | binary(),\n       :offset => integer()\n     }}\n."},
  {"lib/serviceradar/edge/agent_gateway_sync.ex",
   "The pattern pattern <__metadata@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/agent_gateway_sync.ex",
   "The pattern pattern <__map@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/agent_process.ex", "Unknown type: Monitoring.ServiceStatus.t/0."},
  {"lib/serviceradar/edge/agent_release_manager.ex",
   "The pattern variable __version@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/proxmox_console_sessions.ex",
   "The pattern can never match the type nil | binary()."},
  {"lib/serviceradar/edge/remote_access_broker.ex",
   "The pattern variable _frame_type@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_file_transfers.ex",
   "The pattern variable _key@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_file_transfers.ex",
   "The pattern variable _action@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_host_keys.ex",
   "The pattern pattern <__map@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_requests.ex",
   "The pattern variable _action@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_sessions.ex",
   "The pattern variable _error@2 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_sessions.ex",
   "The pattern can never match the type \n  :remote_access_session_active\n  | :remote_access_session_attach\n  | :remote_access_session_close_requested\n  | :remote_access_session_closed\n  | :remote_access_session_create\n  | :remote_access_session_expired\n  | :remote_access_session_opening\n."},
  {"lib/serviceradar/edge/remote_access_sessions.ex",
   "The pattern can never match the type \n  :remote_access_session_active\n  | :remote_access_session_close_requested\n  | :remote_access_session_closed\n  | :remote_access_session_expired\n  | :remote_access_session_failed\n  | :remote_access_session_opening\n."},
  {"lib/serviceradar/edge/remote_access_sessions.ex",
   "The pattern variable _action@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_ssh_identity_issuer.ex",
   "The pattern pattern <__container@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_ssh_principal_mapper.ex",
   "The pattern pattern <__map@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_ssh_session_credentials.ex",
   "The pattern pattern <__container@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_target_policy.ex",
   "The pattern variable __other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/edge/remote_access_target_policy.ex",
   "The pattern pattern <__map@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/event_writer/pipeline.ex",
   "The pattern pattern <_links@1, __link@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/event_writer/pipeline.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/event_writer/processors/default.ex",
   "The pattern can never match the type true."},
  {"lib/serviceradar/event_writer/processors/logs.ex",
   "The pattern pattern <__json@1, __resource_attributes@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/event_writer/processors/sweep.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/events/health_writer.ex",
   "The pattern can never match the type 1 | 2 | 3 | 4."},
  {"lib/serviceradar/events/health_writer.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/events/health_writer.ex",
   "The pattern variable _value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/events/internal_log_publisher.ex",
   "The pattern variable _value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/events/onboarding_writer.ex", "The pattern can never match the type 1 | 3."},
  {"lib/serviceradar/events/onboarding_writer.ex", "The pattern can never match the type 1."},
  {"lib/serviceradar/events/onboarding_writer.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/identity/rbac.ex", "Type mismatch in call without opaque term in put."},
  {"lib/serviceradar/identity/rbac.ex",
   "The pattern can never match the type \n  {:error,\n   :no_profile\n   | %{\n       :__exception__ => true,\n       :__struct__ => atom(),\n       :bread_crumbs => [binary()],\n       :class => :forbidden | :framework | :invalid | :unknown,\n       :context => map(),\n       :stacktrace => nil | %Splode.Stacktrace{:stacktrace => [any()]},\n       :vars => [{_, _}],\n       atom() => _\n     }}\n."},
  {"lib/serviceradar/inventory/active_fingerprint_payload.ex",
   "The pattern pattern <__map@1, __keys@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/bumblebee_catalog_refresh_worker.ex",
   "The pattern can never match the type \n  {:error,\n   %{\n     :__exception__ => true,\n     :__struct__ => atom(),\n     :bread_crumbs => _,\n     :class => _,\n     :stacktrace => _,\n     :vars => _,\n     :context => map(),\n     atom() => _\n   }}\n  | {:ok, struct()}\n  | {:ok, struct(), [map()]}\n."},
  {"lib/serviceradar/inventory/bumblebee_catalog_refresh_worker.ex",
   "The pattern variable _key@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/bumblebee_catalog_refresh_worker.ex",
   "The pattern variable __key@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/bumblebee_ingestor.ex",
   "The pattern pattern <__map@1, __key@1, _default@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/bumblebee_ingestor.ex",
   "The pattern pattern <__map@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/bumblebee_ingestor.ex",
   "The pattern variable __map@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/device_discovery_ingestor.ex",
   "The pattern pattern <__map@1, __keys@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/device_enrichment_rules.ex",
   "The pattern variable _parsed@2 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/device_enrichment_rules.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/device_enrichment_rules.ex",
   "The pattern pattern <__branch@1, _label@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/device_enrichment_rules.ex",
   "The pattern pattern <__ctx@1, _> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/device_enrichment_rules.ex",
   "The pattern variable _value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/device_identifier.ex",
   "Call to missing or private function Ash.Query.filter/2."},
  {"lib/serviceradar/inventory/dpi_payload.ex",
   "The pattern pattern <__map@1, __keys@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/endpoint_inventory_artifact_store.ex",
   "The pattern pattern <__map@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/endpoint_inventory_ingestor_queue.ex",
   "The pattern can never match the type {:ok, pid()}."},
  {"lib/serviceradar/inventory/endpoint_inventory_retention.ex",
   "The pattern can never match the type {:error, _}."},
  {"lib/serviceradar/inventory/hypervisor_enrichment_ingestor.ex",
   "The pattern variable __role@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/hypervisor_enrichment_ingestor.ex",
   "Function lookup_device_by_macs/3 has no local return."},
  {"lib/serviceradar/inventory/hypervisor_enrichment_ingestor.ex",
   "The function call extract_strong_identifiers will not succeed."},
  {"lib/serviceradar/inventory/hypervisor_enrichment_ingestor.ex",
   "The pattern pattern <__map@1, __key@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/hypervisor_enrichment_ingestor.ex",
   "The pattern variable __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/identity/ids.ex",
   "The pattern variable __metadata@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/identity/merge_engine.ex",
   "The pattern can never match the type \n  {:error,\n   %{\n     :__exception__ => true,\n     :__struct__ => atom(),\n     :bread_crumbs => [any()],\n     :class => :forbidden | :framework | :invalid | :unknown,\n     :context => map(),\n     :stacktrace => nil | map(),\n     :vars => [any()],\n     atom() => _\n   }}\n  | {:ok,\n     %{\n       :__struct__ => Ash.Page.Keyset | Ash.Page.Offset,\n       :count => integer(),\n       :limit => integer(),\n       :more? => boolean(),\n       :rerun => {map(), [any()]},\n       :results => [map()],\n       :after => nil | binary(),\n       :before => nil | binary(),\n       :offset => integer()\n     }}\n."},
  {"lib/serviceradar/inventory/passive_fingerprint_payload.ex",
   "The pattern pattern <__metadata@1, __protocol@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/passive_fingerprint_payload.ex",
   "The pattern pattern <__map@1, __keys@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/sync/identifier_records.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/sync/normalize.ex",
   "The pattern pattern <__metadata@1, __update@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/sync_ingestor.ex",
   "The pattern pattern <__result@1, __resolved_updates@1, __actor@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/inventory/sync_ingestor.ex",
   "The pattern can never match the type {:ok, :ok, :ok, :ok, :ok}."},
  {"lib/serviceradar/inventory/sync_ingestor_queue.ex",
   "The pattern can never match the type {:ok, pid()}."},
  {"lib/serviceradar/inventory/vulnerability_advisory_ingestor.ex",
   "The pattern variable __payload@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/jobs/schedule_health_check.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/monitoring/alert.ex", "The guard clause can never succeed."},
  {"lib/serviceradar/monitoring/alert_generator.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/monitoring/ocsf_event.ex", "The guard clause can never succeed."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "The pattern can never match the type {:ok, _}."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function create_topology_candidate_device_for_ip/5 has no local return."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function create_candidate_device_for_ip/4 has no local return."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function create_device_for_ip/4 has no local return."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function create_resolved_device_for_ip/8 will never be called."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function resolve_device_uid_via_dire/4 has no local return."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "The function call resolve_device_id will not succeed."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "The pattern can never match the type {:ok, binary()}."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function register_mapper_mac_identifiers/5 will never be called."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function find_management_device_uid/3 will never be called."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function ip_matches?/2 will never be called."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function maybe_put/3 will never be called."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function recover_existing_device_uid/4 will never be called."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function recover_existing_device_uid_from_conflict/4 will never be called."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "Function device_exists?/2 will never be called."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "The pattern variable __record@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/network_discovery/mapper_results_ingestor.ex",
   "The function call generate_deterministic_device_id will not succeed."},
  {"lib/serviceradar/observability/event_title.ex", "The guard clause can never succeed."},
  {"lib/serviceradar/observability/event_title.ex",
   "The pattern can never match the type binary() | {integer(), integer()}."},
  {"lib/serviceradar/observability/log_promotion.ex",
   "The pattern can never match the type {:ok, pid()}."},
  {"lib/serviceradar/observability/log_promotion.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/observability/mtr_automation_dispatcher.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/serviceradar/observability/mtr_automation_dispatcher.ex",
   "Type mismatch in call with opaque term in collect_target_contexts."},
  {"lib/serviceradar/observability/mtr_automation_dispatcher.ex",
   "Type mismatch in call without opaque term in put."},
  {"lib/serviceradar/observability/mtr_automation_dispatcher.ex",
   "The pattern variable _targets@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/observability/mtr_graph.ex",
   "The pattern pattern <__value@1, _default@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/observability/mtr_metrics_ingestor.ex",
   "The pattern can never match the type \n  {:ok, _,\n   [\n     %Ash.Notifier.Notification{\n       :action => _,\n       :actor => _,\n       :changeset => _,\n       :data => _,\n       :domain => _,\n       :for => _,\n       :from => _,\n       :metadata => _,\n       :resource => _\n     }\n   ]}\n."},
  {"lib/serviceradar/observability/mtr_metrics_ingestor.ex",
   "The pattern can never match the type \n  []\n  | %Ash.BulkResult{\n      :error_count => non_neg_integer(),\n      :errors => nil | [[any()] | map()],\n      :notifications => nil | [map()],\n      :records => nil | [map()],\n      :status => :partial_success\n    }\n."},
  {"lib/serviceradar/observability/netflow_oui_dataset_refresh_worker.ex",
   "The pattern can never match the type true."},
  {"lib/serviceradar/observability/stateful_alert_engine.ex",
   "The guard clause can never succeed."},
  {"lib/serviceradar/observability/stateful_alert_evaluation_queue.ex",
   "The pattern can never match the type {:ok, pid()}."},
  {"lib/serviceradar/observability/threat_intel_plugin_ingestor.ex",
   "The guard clause can never succeed."},
  {"lib/serviceradar/observability/threat_intel_plugin_ingestor.ex",
   "The pattern variable __cursor@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/observability/threat_intel_plugin_ingestor.ex",
   "The pattern pattern <__page@1, __payload@1, __actor@1, __observed_at@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/observability/threat_intel_plugin_ingestor.ex",
   "The pattern pattern <__page@1, __indicator_attrs@1, __actor@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/observability/zen_rule_seeder.ex",
   "The pattern variable _updated@2 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/observability/zen_rule_sync.ex",
   "The pattern variable _unexpected@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/otel/propagation.ex",
   "The pattern can never match the type %{\n  :attributes =>\n    [{_, _}] | %{atom() | binary() => atom() | binary() | [any()] | number() | tuple()},\n  :span_id => non_neg_integer(),\n  :trace_id => non_neg_integer(),\n  :tracestate => {:tracestate, [any()]}\n}."},
  {"lib/serviceradar/plugins/addon_profile_ops.ex",
   "The pattern variable _error@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/plugins/native_addon_importer.ex",
   "The pattern variable _bytes@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/plugins/producer_schedule_dispatcher.ex",
   "The pattern can never match the type {:error, :missing_target_query}."},
  {"lib/serviceradar/plugins/producer_schedule_dispatcher.ex",
   "The function call resolve will not succeed."},
  {"lib/serviceradar/plugins/producer_schedule_dispatcher.ex",
   "Function load_plugin_assignments_for_agents/3 will never be called."},
  {"lib/serviceradar/plugins/producer_schedule_dispatcher.ex",
   "Function load_addon_assignments_for_agents/3 will never be called."},
  {"lib/serviceradar/plugins/secret_refs.ex",
   "The pattern variable __params@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/plugins/secret_refs.ex",
   "The pattern variable __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/security/events.ex", "The pattern can never match the type [any(), ...]."},
  {"lib/serviceradar/security/rate_limiter.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/snmp_profiles/credential_resolver.ex",
   "The pattern pattern <__payload@1, __record@1, __secret@1> can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/spatial/actions/bulk_insert_spectrum_observations.ex",
   "The guard clause can never succeed."},
  {"lib/serviceradar/spiffe/workload_api.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/sweep_jobs/sweep_results_ingestor.ex",
   "The created anonymous function has no local return."},
  {"lib/serviceradar/sweep_jobs/sweep_results_ingestor.ex",
   "Function create_available_unknown_device/3 has no local return."},
  {"lib/serviceradar/sweep_jobs/sweep_results_ingestor.ex",
   "The function call generate_deterministic_device_id will not succeed."},
  {"lib/serviceradar/sweep_jobs/sweep_results_ingestor.ex",
   "The pattern variable __message@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/telemetry/otel_setup.ex", "The function call add_handler will not succeed."},
  {"lib/serviceradar/wifi_map/batch_ingestor.ex", "The pattern can never match the type :ok."},
  {"lib/serviceradar/wifi_map/batch_ingestor.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/serviceradar/wifi_map/batch_ingestor.ex",
   "The function call generate_deterministic_device_id will not succeed."},
  {"src/otel_exporter_logs_otlp.erl",
   "The pattern variable Batch can never match the type, because it is covered by previous clauses."},
  {"src/otel_exporter_logs_otlp.erl",
   "The pattern variable Req can never match the type, because it is covered by previous clauses."},
  {"src/otel_exporter_logs_otlp.erl",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"src/otel_exporter_logs_otlp.erl",
   "The pattern can never match the type {:grpc_status, binary()} | {:http_error, integer()} | {:export_error, _, _}."},
  {"src/otel_exporter_logs_otlp.erl",
   "The pattern can never match the type {:grpc_status, binary()} | {:export_error, _, _}."},
  {"src/otel_exporter_logs_otlp.erl",
   "The pattern can never match the type \n  {:grpc_status, binary()} | {:http_error, integer()} | {:export_error, _, _},\n  _,\n  [\n    %{\n      :host => binary() | maybe_improper_list(any(), binary() | []),\n      :scheme => binary() | maybe_improper_list(any(), binary() | []),\n      :path => binary() | maybe_improper_list(any(), binary() | []),\n      :port => integer(),\n      :ssl_options => []\n    }\n  ],\n  :gzip | :undefined\n."},
  {"src/serviceradar_otel_exporter_traces_otlp.erl",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."}
]
