//
// Copyright 2026 Carver Automation Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: agent/addon/v1/addon.proto

package addonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryPayloadKind int32

const (
	TelemetryPayloadKind_TELEMETRY_PAYLOAD_KIND_UNSPECIFIED TelemetryPayloadKind = 0
	TelemetryPayloadKind_TELEMETRY_PAYLOAD_KIND_OCSF_EVENT  TelemetryPayloadKind = 1
	TelemetryPayloadKind_TELEMETRY_PAYLOAD_KIND_OTEL_LOG    TelemetryPayloadKind = 2
	// OTLP relay payload kinds (RelayOtlp / otlp-relay:v1). The record payload
	// is exactly one encoded OTLP ExportTraceServiceRequest /
	// ExportLogsServiceRequest / ExportMetricsServiceRequest chunk, chunked
	// ONCE at the edge so one TelemetryRecord maps to one NATS message
	// upstream.
	TelemetryPayloadKind_TELEMETRY_PAYLOAD_KIND_OTLP_TRACES  TelemetryPayloadKind = 3
	TelemetryPayloadKind_TELEMETRY_PAYLOAD_KIND_OTLP_LOGS    TelemetryPayloadKind = 4
	TelemetryPayloadKind_TELEMETRY_PAYLOAD_KIND_OTLP_METRICS TelemetryPayloadKind = 5
	// Metrics the edge collector derived locally from other signals (e.g.
	// span-derived RED metrics), kept distinct from pass-through OTLP_METRICS
	// so core can route them to the derived-metrics subject.
	TelemetryPayloadKind_TELEMETRY_PAYLOAD_KIND_OTLP_DERIVED_METRIC TelemetryPayloadKind = 6
	// ServiceRadar-native metric batches produced by non-OTLP collectors.
	// TelemetryRecord.payload is exactly one encoded
	// serviceradar.metric.v1.MetricBatch. Gateway republishes this payload
	// unchanged to metrics.* so core/event_writer owns persistence.
	TelemetryPayloadKind_TELEMETRY_PAYLOAD_KIND_SERVICERADAR_METRICS TelemetryPayloadKind = 7
	// Device observations an add-on made about OTHER hosts, for the inventory
	// pipeline rather than the observability one.
	//
	// TelemetryRecord.payload is exactly one encoded
	// serviceradar.agent.discovery.v1.DiscoveryEnvelope, whose `schema` field --
	// a STRING, not another enum value -- selects the decoder in core.
	//
	// This is deliberately the ONLY discovery payload kind that will ever be
	// added. A kind per observation type would put every new payload back on the
	// path this exists to remove: edit the proto, regenerate Go, Elixir and Rust,
	// teach the agent and the gateway, ship an agent release. With a schema
	// string, a new observation type is one registry entry in core and nothing
	// else. Add a schema, never a kind.
	TelemetryPayloadKind_TELEMETRY_PAYLOAD_KIND_DISCOVERY_V1 TelemetryPayloadKind = 8
)

// Enum value maps for TelemetryPayloadKind.
var (
	TelemetryPayloadKind_name = map[int32]string{
		0: "TELEMETRY_PAYLOAD_KIND_UNSPECIFIED",
		1: "TELEMETRY_PAYLOAD_KIND_OCSF_EVENT",
		2: "TELEMETRY_PAYLOAD_KIND_OTEL_LOG",
		3: "TELEMETRY_PAYLOAD_KIND_OTLP_TRACES",
		4: "TELEMETRY_PAYLOAD_KIND_OTLP_LOGS",
		5: "TELEMETRY_PAYLOAD_KIND_OTLP_METRICS",
		6: "TELEMETRY_PAYLOAD_KIND_OTLP_DERIVED_METRIC",
		7: "TELEMETRY_PAYLOAD_KIND_SERVICERADAR_METRICS",
		8: "TELEMETRY_PAYLOAD_KIND_DISCOVERY_V1",
	}
	TelemetryPayloadKind_value = map[string]int32{
		"TELEMETRY_PAYLOAD_KIND_UNSPECIFIED":          0,
		"TELEMETRY_PAYLOAD_KIND_OCSF_EVENT":           1,
		"TELEMETRY_PAYLOAD_KIND_OTEL_LOG":             2,
		"TELEMETRY_PAYLOAD_KIND_OTLP_TRACES":          3,
		"TELEMETRY_PAYLOAD_KIND_OTLP_LOGS":            4,
		"TELEMETRY_PAYLOAD_KIND_OTLP_METRICS":         5,
		"TELEMETRY_PAYLOAD_KIND_OTLP_DERIVED_METRIC":  6,
		"TELEMETRY_PAYLOAD_KIND_SERVICERADAR_METRICS": 7,
		"TELEMETRY_PAYLOAD_KIND_DISCOVERY_V1":         8,
	}
)

func (x TelemetryPayloadKind) Enum() *TelemetryPayloadKind {
	p := new(TelemetryPayloadKind)
	*p = x
	return p
}

func (x TelemetryPayloadKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryPayloadKind) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_addon_v1_addon_proto_enumTypes[0].Descriptor()
}

func (TelemetryPayloadKind) Type() protoreflect.EnumType {
	return &file_agent_addon_v1_addon_proto_enumTypes[0]
}

func (x TelemetryPayloadKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryPayloadKind.Descriptor instead.
func (TelemetryPayloadKind) EnumDescriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{0}
}

type HealthResponse_Status int32

const (
	HealthResponse_STATUS_UNSPECIFIED HealthResponse_Status = 0
	HealthResponse_STATUS_HEALTHY     HealthResponse_Status = 1
	HealthResponse_STATUS_DEGRADED    HealthResponse_Status = 2
	HealthResponse_STATUS_UNHEALTHY   HealthResponse_Status = 3
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_HEALTHY",
		2: "STATUS_DEGRADED",
		3: "STATUS_UNHEALTHY",
	}
	HealthResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_HEALTHY":     1,
		"STATUS_DEGRADED":    2,
		"STATUS_UNHEALTHY":   3,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_addon_v1_addon_proto_enumTypes[1].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_agent_addon_v1_addon_proto_enumTypes[1]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{5, 0}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// config_json is the operator-selected configuration for this add-on,
	// validated by the control plane against the add-on's config.schema.json.
	ConfigJson    []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ConfigureResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// config_hash is a stable hash of the applied configuration for change
	// detection by the agent.
	ConfigHash string `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Accepted   bool   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// error is a bounded diagnostic when accepted is false.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureResponse) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ConfigureResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConfigureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=serviceradar.agent.addon.v1.HealthResponse_Status" json:"status,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// degradation_reason is a bounded explanation when status is not HEALTHY
	// (e.g. "CAP_BPF not granted").
	DegradationReason string `protobuf:"bytes,3,opt,name=degradation_reason,json=degradationReason,proto3" json:"degradation_reason,omitempty"`
	// details carries bounded, STRUCTURED capability state the agent reads to
	// make decisions -- distinct from degradation_reason, which is prose for a
	// human and must not be parsed.
	//
	// netprobe reports `running_as_root` and its p0f/muonfp/recog/satori corpus
	// revisions here; the agent turns those into the sweep banner-grab capability
	// status. Without a structured carrier that state has no home once the
	// bespoke IPC is retired, and the capability silently reports unavailable.
	//
	// Keys are add-on-defined and NOT trusted for identity or authorization: this
	// is the add-on describing its own runtime, the same trust level as
	// TelemetrySource.metadata.
	Details       map[string]string `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetDegradationReason() string {
	if x != nil {
		return x.DegradationReason
	}
	return ""
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type StreamTelemetryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// capability is the telemetry capability version requested by the agent, for
	// example "native-telemetry:v1".
	Capability    string `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTelemetryRequest) Reset() {
	*x = StreamTelemetryRequest{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTelemetryRequest) ProtoMessage() {}

func (x *StreamTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTelemetryRequest.ProtoReflect.Descriptor instead.
func (*StreamTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{6}
}

func (x *StreamTelemetryRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type StreamArtifactsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// capability is the artifact staging capability version requested by the
	// agent, for example "artifact-staging:v1".
	Capability    string `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamArtifactsRequest) Reset() {
	*x = StreamArtifactsRequest{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamArtifactsRequest) ProtoMessage() {}

func (x *StreamArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamArtifactsRequest.ProtoReflect.Descriptor instead.
func (*StreamArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{7}
}

func (x *StreamArtifactsRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type RunCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command_id is the platform command identifier assigned by the commandbus.
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// command_type identifies the generic control-plane command, for example
	// "addon.run_command".
	CommandType string `protobuf:"bytes,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	// action_id is the package-declared producer action to execute.
	ActionId string `protobuf:"bytes,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// schema identifies the payload contract carried in payload_json.
	Schema string `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	// payload_json is an opaque JSON object for the add-on to interpret according
	// to schema and action_id. It may include credential broker grants, never raw
	// secret values.
	PayloadJson []byte `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	// deadline_unix is the absolute Unix second deadline supplied by the agent
	// after applying command TTL limits. Zero means no explicit deadline.
	DeadlineUnix  int64             `protobuf:"varint,6,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{8}
}

func (x *RunCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RunCommandRequest) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *RunCommandRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *RunCommandRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *RunCommandRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *RunCommandRequest) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *RunCommandRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RunCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandResponse) Reset() {
	*x = RunCommandResponse{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResponse) ProtoMessage() {}

func (x *RunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResponse.ProtoReflect.Descriptor instead.
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{9}
}

func (x *RunCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunCommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RunCommandResponse) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *RunCommandResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ArtifactMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object_key is a producer-local relative path. The agent-gateway scopes it
	// below the authenticated agent and add-on assignment before writing storage.
	ObjectKey     string            `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ContentType   string            `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Sha256        string            `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	SizeBytes     int64             `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Attributes    map[string]string `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactMetadata) Reset() {
	*x = ArtifactMetadata{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactMetadata) ProtoMessage() {}

func (x *ArtifactMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactMetadata.ProtoReflect.Descriptor instead.
func (*ArtifactMetadata) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{10}
}

func (x *ArtifactMetadata) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ArtifactMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ArtifactMetadata) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactMetadata) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ArtifactUploadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// metadata is required on the first chunk of each artifact and omitted on
	// continuation chunks.
	Metadata      *ArtifactMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data          []byte            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ChunkIndex    uint32            `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	IsFinal       bool              `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactUploadChunk) Reset() {
	*x = ArtifactUploadChunk{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactUploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactUploadChunk) ProtoMessage() {}

func (x *ArtifactUploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactUploadChunk.ProtoReflect.Descriptor instead.
func (*ArtifactUploadChunk) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{11}
}

func (x *ArtifactUploadChunk) GetMetadata() *ArtifactMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ArtifactUploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArtifactUploadChunk) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ArtifactUploadChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type TelemetrySource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source_type identifies the producer family, for example "powerdns".
	SourceType string `protobuf:"bytes,1,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// source_instance identifies the local producer instance, for example
	// "recursor" or a configured listener name.
	SourceInstance string `protobuf:"bytes,2,opt,name=source_instance,json=sourceInstance,proto3" json:"source_instance,omitempty"`
	// metadata carries bounded source-local labels. Gateway-attested identity is
	// attached upstream and MUST NOT be trusted from this map.
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetrySource) Reset() {
	*x = TelemetrySource{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySource) ProtoMessage() {}

func (x *TelemetrySource) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySource.ProtoReflect.Descriptor instead.
func (*TelemetrySource) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{12}
}

func (x *TelemetrySource) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *TelemetrySource) GetSourceInstance() string {
	if x != nil {
		return x.SourceInstance
	}
	return ""
}

func (x *TelemetrySource) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TelemetryCounters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      uint64                 `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Filtered      uint64                 `protobuf:"varint,2,opt,name=filtered,proto3" json:"filtered,omitempty"`
	Emitted       uint64                 `protobuf:"varint,3,opt,name=emitted,proto3" json:"emitted,omitempty"`
	Dropped       uint64                 `protobuf:"varint,4,opt,name=dropped,proto3" json:"dropped,omitempty"`
	QueueDepth    uint64                 `protobuf:"varint,5,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryCounters) Reset() {
	*x = TelemetryCounters{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryCounters) ProtoMessage() {}

func (x *TelemetryCounters) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryCounters.ProtoReflect.Descriptor instead.
func (*TelemetryCounters) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{13}
}

func (x *TelemetryCounters) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *TelemetryCounters) GetFiltered() uint64 {
	if x != nil {
		return x.Filtered
	}
	return 0
}

func (x *TelemetryCounters) GetEmitted() uint64 {
	if x != nil {
		return x.Emitted
	}
	return 0
}

func (x *TelemetryCounters) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *TelemetryCounters) GetQueueDepth() uint64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

type TelemetryRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id is a stable idempotency key for this record.
	EventId              string               `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ObservedTimeUnixNano int64                `protobuf:"varint,2,opt,name=observed_time_unix_nano,json=observedTimeUnixNano,proto3" json:"observed_time_unix_nano,omitempty"`
	EventTimeUnixNano    int64                `protobuf:"varint,3,opt,name=event_time_unix_nano,json=eventTimeUnixNano,proto3" json:"event_time_unix_nano,omitempty"`
	PayloadKind          TelemetryPayloadKind `protobuf:"varint,4,opt,name=payload_kind,json=payloadKind,proto3,enum=serviceradar.agent.addon.v1.TelemetryPayloadKind" json:"payload_kind,omitempty"`
	Payload              []byte               `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata             map[string]string    `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TelemetryRecord) Reset() {
	*x = TelemetryRecord{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRecord) ProtoMessage() {}

func (x *TelemetryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRecord.ProtoReflect.Descriptor instead.
func (*TelemetryRecord) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{14}
}

func (x *TelemetryRecord) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TelemetryRecord) GetObservedTimeUnixNano() int64 {
	if x != nil {
		return x.ObservedTimeUnixNano
	}
	return 0
}

func (x *TelemetryRecord) GetEventTimeUnixNano() int64 {
	if x != nil {
		return x.EventTimeUnixNano
	}
	return 0
}

func (x *TelemetryRecord) GetPayloadKind() TelemetryPayloadKind {
	if x != nil {
		return x.PayloadKind
	}
	return TelemetryPayloadKind_TELEMETRY_PAYLOAD_KIND_UNSPECIFIED
}

func (x *TelemetryRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TelemetryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *TelemetrySource       `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Records       []*TelemetryRecord     `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Counters      *TelemetryCounters     `protobuf:"bytes,3,opt,name=counters,proto3" json:"counters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{15}
}

func (x *TelemetryBatch) GetSource() *TelemetrySource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TelemetryBatch) GetRecords() []*TelemetryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *TelemetryBatch) GetCounters() *TelemetryCounters {
	if x != nil {
		return x.Counters
	}
	return nil
}

// OtlpRelayFrame is one acked relay unit the add-on ships to the agent on the
// RelayOtlp response stream. relay_id is a persistent, strictly increasing
// sequence number assigned by the add-on's durable spool; it identifies the
// frame for acknowledgement and never resets across reconnects (unacked
// frames are re-sent with their original relay_ids). batch reuses
// TelemetryBatch with the OTLP payload kinds; each TelemetryRecord.payload is
// one pre-chunked Export*ServiceRequest, so the agent can forward a frame
// verbatim as the GatewayServiceStatus.message bytes for source ==
// "otlp-relay" without re-chunking.
type OtlpRelayFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       uint64                 `protobuf:"varint,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	Batch         *TelemetryBatch        `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtlpRelayFrame) Reset() {
	*x = OtlpRelayFrame{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtlpRelayFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtlpRelayFrame) ProtoMessage() {}

func (x *OtlpRelayFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtlpRelayFrame.ProtoReflect.Descriptor instead.
func (*OtlpRelayFrame) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{16}
}

func (x *OtlpRelayFrame) GetRelayId() uint64 {
	if x != nil {
		return x.RelayId
	}
	return 0
}

func (x *OtlpRelayFrame) GetBatch() *TelemetryBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

// OtlpRelayAck is the agent-to-add-on acknowledgement watermark on the
// RelayOtlp request stream. acked_relay_id confirms that every frame with
// relay_id <= acked_relay_id has been accepted upstream by the agent-gateway;
// the add-on may then release those frames from its spool. Acks are
// cumulative, so the agent may coalesce them.
type OtlpRelayAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckedRelayId  uint64                 `protobuf:"varint,1,opt,name=acked_relay_id,json=ackedRelayId,proto3" json:"acked_relay_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtlpRelayAck) Reset() {
	*x = OtlpRelayAck{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtlpRelayAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtlpRelayAck) ProtoMessage() {}

func (x *OtlpRelayAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtlpRelayAck.ProtoReflect.Descriptor instead.
func (*OtlpRelayAck) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{17}
}

func (x *OtlpRelayAck) GetAckedRelayId() uint64 {
	if x != nil {
		return x.AckedRelayId
	}
	return 0
}

// MetricFeedFrame is one unit of the agent-to-add-on local metric feed
// (StreamMetricFeed / metric-feed:v1). The agent writes frames on the request
// stream. feed_id is a per-stream, strictly increasing sequence the agent
// assigns for acknowledgement and drop accounting; unlike RelayOtlp's relay_id
// it resets when the stream is re-opened (the feed is lossy, not a durable
// spool). source identifies which local collector produced the samples (for
// example sysmon, snmp, icmp, timeseries) so an add-on can route or subscribe to
// a subset. payload is exactly one encoded serviceradar.metric.v1.MetricBatch,
// matching the SERVICERADAR_METRICS telemetry payload kind, so edge and central
// analysis decode identical bytes.
type MetricFeedFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        uint64                 `protobuf:"varint,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Source        *TelemetrySource       `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricFeedFrame) Reset() {
	*x = MetricFeedFrame{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricFeedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricFeedFrame) ProtoMessage() {}

func (x *MetricFeedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricFeedFrame.ProtoReflect.Descriptor instead.
func (*MetricFeedFrame) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{18}
}

func (x *MetricFeedFrame) GetFeedId() uint64 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *MetricFeedFrame) GetSource() *TelemetrySource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *MetricFeedFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// MetricFeedAck is the add-on-to-agent flow-control watermark on the
// StreamMetricFeed response stream. acked_feed_id confirms the add-on has
// accepted every frame with feed_id <= acked_feed_id; the agent uses it to bound
// in-flight frames and to detect a stalled add-on. Acks are cumulative, so the
// add-on may coalesce them.
type MetricFeedAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckedFeedId   uint64                 `protobuf:"varint,1,opt,name=acked_feed_id,json=ackedFeedId,proto3" json:"acked_feed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricFeedAck) Reset() {
	*x = MetricFeedAck{}
	mi := &file_agent_addon_v1_addon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricFeedAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricFeedAck) ProtoMessage() {}

func (x *MetricFeedAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_addon_v1_addon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricFeedAck.ProtoReflect.Descriptor instead.
func (*MetricFeedAck) Descriptor() ([]byte, []int) {
	return file_agent_addon_v1_addon_proto_rawDescGZIP(), []int{19}
}

func (x *MetricFeedAck) GetAckedFeedId() uint64 {
	if x != nil {
		return x.AckedFeedId
	}
	return 0
}

var File_agent_addon_v1_addon_proto protoreflect.FileDescriptor

const file_agent_addon_v1_addon_proto_rawDesc = "" +
	"\n" +
	"\x1aagent/addon/v1/addon.proto\x12\x1bserviceradar.agent.addon.v1\"\r\n" +
	"\vInfoRequest\"\\\n" +
	"\fInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"3\n" +
	"\x10ConfigureRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"f\n" +
	"\x11ConfigureResponse\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"\x96\x03\n" +
	"\x0eHealthResponse\x12J\n" +
	"\x06status\x18\x01 \x01(\x0e22.serviceradar.agent.addon.v1.HealthResponse.StatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12-\n" +
	"\x12degradation_reason\x18\x03 \x01(\tR\x11degradationReason\x12R\n" +
	"\adetails\x18\x04 \x03(\v28.serviceradar.agent.addon.v1.HealthResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_HEALTHY\x10\x01\x12\x13\n" +
	"\x0fSTATUS_DEGRADED\x10\x02\x12\x14\n" +
	"\x10STATUS_UNHEALTHY\x10\x03\"8\n" +
	"\x16StreamTelemetryRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\"8\n" +
	"\x16StreamArtifactsRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\"\xe9\x02\n" +
	"\x11RunCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\tR\vcommandType\x12\x1b\n" +
	"\taction_id\x18\x03 \x01(\tR\bactionId\x12\x16\n" +
	"\x06schema\x18\x04 \x01(\tR\x06schema\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\fR\vpayloadJson\x12#\n" +
	"\rdeadline_unix\x18\x06 \x01(\x03R\fdeadlineUnix\x12X\n" +
	"\bmetadata\x18\a \x03(\v2<.serviceradar.agent.addon.v1.RunCommandRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\x12RunCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\fR\vpayloadJson\x12Y\n" +
	"\bmetadata\x18\x04 \x03(\v2=.serviceradar.agent.addon.v1.RunCommandResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x02\n" +
	"\x10ArtifactMetadata\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12]\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2=.serviceradar.agent.addon.v1.ArtifactMetadata.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x13ArtifactUploadChunk\x12I\n" +
	"\bmetadata\x18\x01 \x01(\v2-.serviceradar.agent.addon.v1.ArtifactMetadataR\bmetadata\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\rR\n" +
	"chunkIndex\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\"\xf0\x01\n" +
	"\x0fTelemetrySource\x12\x1f\n" +
	"\vsource_type\x18\x01 \x01(\tR\n" +
	"sourceType\x12'\n" +
	"\x0fsource_instance\x18\x02 \x01(\tR\x0esourceInstance\x12V\n" +
	"\bmetadata\x18\x03 \x03(\v2:.serviceradar.agent.addon.v1.TelemetrySource.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\x11TelemetryCounters\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x04R\breceived\x12\x1a\n" +
	"\bfiltered\x18\x02 \x01(\x04R\bfiltered\x12\x18\n" +
	"\aemitted\x18\x03 \x01(\x04R\aemitted\x12\x18\n" +
	"\adropped\x18\x04 \x01(\x04R\adropped\x12\x1f\n" +
	"\vqueue_depth\x18\x05 \x01(\x04R\n" +
	"queueDepth\"\x99\x03\n" +
	"\x0fTelemetryRecord\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x125\n" +
	"\x17observed_time_unix_nano\x18\x02 \x01(\x03R\x14observedTimeUnixNano\x12/\n" +
	"\x14event_time_unix_nano\x18\x03 \x01(\x03R\x11eventTimeUnixNano\x12T\n" +
	"\fpayload_kind\x18\x04 \x01(\x0e21.serviceradar.agent.addon.v1.TelemetryPayloadKindR\vpayloadKind\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12V\n" +
	"\bmetadata\x18\x06 \x03(\v2:.serviceradar.agent.addon.v1.TelemetryRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xea\x01\n" +
	"\x0eTelemetryBatch\x12D\n" +
	"\x06source\x18\x01 \x01(\v2,.serviceradar.agent.addon.v1.TelemetrySourceR\x06source\x12F\n" +
	"\arecords\x18\x02 \x03(\v2,.serviceradar.agent.addon.v1.TelemetryRecordR\arecords\x12J\n" +
	"\bcounters\x18\x03 \x01(\v2..serviceradar.agent.addon.v1.TelemetryCountersR\bcounters\"n\n" +
	"\x0eOtlpRelayFrame\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\x04R\arelayId\x12A\n" +
	"\x05batch\x18\x02 \x01(\v2+.serviceradar.agent.addon.v1.TelemetryBatchR\x05batch\"4\n" +
	"\fOtlpRelayAck\x12$\n" +
	"\x0eacked_relay_id\x18\x01 \x01(\x04R\fackedRelayId\"\x8a\x01\n" +
	"\x0fMetricFeedFrame\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\x04R\x06feedId\x12D\n" +
	"\x06source\x18\x02 \x01(\v2,.serviceradar.agent.addon.v1.TelemetrySourceR\x06source\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"3\n" +
	"\rMetricFeedAck\x12\"\n" +
	"\racked_feed_id\x18\x01 \x01(\x04R\vackedFeedId*\x8b\x03\n" +
	"\x14TelemetryPayloadKind\x12&\n" +
	"\"TELEMETRY_PAYLOAD_KIND_UNSPECIFIED\x10\x00\x12%\n" +
	"!TELEMETRY_PAYLOAD_KIND_OCSF_EVENT\x10\x01\x12#\n" +
	"\x1fTELEMETRY_PAYLOAD_KIND_OTEL_LOG\x10\x02\x12&\n" +
	"\"TELEMETRY_PAYLOAD_KIND_OTLP_TRACES\x10\x03\x12$\n" +
	" TELEMETRY_PAYLOAD_KIND_OTLP_LOGS\x10\x04\x12'\n" +
	"#TELEMETRY_PAYLOAD_KIND_OTLP_METRICS\x10\x05\x12.\n" +
	"*TELEMETRY_PAYLOAD_KIND_OTLP_DERIVED_METRIC\x10\x06\x12/\n" +
	"+TELEMETRY_PAYLOAD_KIND_SERVICERADAR_METRICS\x10\a\x12'\n" +
	"#TELEMETRY_PAYLOAD_KIND_DISCOVERY_V1\x10\b2\xf7\x06\n" +
	"\fAddonService\x12[\n" +
	"\x04Info\x12(.serviceradar.agent.addon.v1.InfoRequest\x1a).serviceradar.agent.addon.v1.InfoResponse\x12j\n" +
	"\tConfigure\x12-.serviceradar.agent.addon.v1.ConfigureRequest\x1a..serviceradar.agent.addon.v1.ConfigureResponse\x12a\n" +
	"\x06Health\x12*.serviceradar.agent.addon.v1.HealthRequest\x1a+.serviceradar.agent.addon.v1.HealthResponse\x12u\n" +
	"\x0fStreamTelemetry\x123.serviceradar.agent.addon.v1.StreamTelemetryRequest\x1a+.serviceradar.agent.addon.v1.TelemetryBatch0\x01\x12z\n" +
	"\x0fStreamArtifacts\x123.serviceradar.agent.addon.v1.StreamArtifactsRequest\x1a0.serviceradar.agent.addon.v1.ArtifactUploadChunk0\x01\x12g\n" +
	"\tRelayOtlp\x12).serviceradar.agent.addon.v1.OtlpRelayAck\x1a+.serviceradar.agent.addon.v1.OtlpRelayFrame(\x010\x01\x12p\n" +
	"\x10StreamMetricFeed\x12,.serviceradar.agent.addon.v1.MetricFeedFrame\x1a*.serviceradar.agent.addon.v1.MetricFeedAck(\x010\x01\x12m\n" +
	"\n" +
	"RunCommand\x12..serviceradar.agent.addon.v1.RunCommandRequest\x1a/.serviceradar.agent.addon.v1.RunCommandResponseBAZ?github.com/carverauto/serviceradar/proto/agent/addon/v1;addonpbb\x06proto3"

var (
	file_agent_addon_v1_addon_proto_rawDescOnce sync.Once
	file_agent_addon_v1_addon_proto_rawDescData []byte
)

func file_agent_addon_v1_addon_proto_rawDescGZIP() []byte {
	file_agent_addon_v1_addon_proto_rawDescOnce.Do(func() {
		file_agent_addon_v1_addon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_addon_v1_addon_proto_rawDesc), len(file_agent_addon_v1_addon_proto_rawDesc)))
	})
	return file_agent_addon_v1_addon_proto_rawDescData
}

var file_agent_addon_v1_addon_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_addon_v1_addon_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_agent_addon_v1_addon_proto_goTypes = []any{
	(TelemetryPayloadKind)(0),      // 0: serviceradar.agent.addon.v1.TelemetryPayloadKind
	(HealthResponse_Status)(0),     // 1: serviceradar.agent.addon.v1.HealthResponse.Status
	(*InfoRequest)(nil),            // 2: serviceradar.agent.addon.v1.InfoRequest
	(*InfoResponse)(nil),           // 3: serviceradar.agent.addon.v1.InfoResponse
	(*ConfigureRequest)(nil),       // 4: serviceradar.agent.addon.v1.ConfigureRequest
	(*ConfigureResponse)(nil),      // 5: serviceradar.agent.addon.v1.ConfigureResponse
	(*HealthRequest)(nil),          // 6: serviceradar.agent.addon.v1.HealthRequest
	(*HealthResponse)(nil),         // 7: serviceradar.agent.addon.v1.HealthResponse
	(*StreamTelemetryRequest)(nil), // 8: serviceradar.agent.addon.v1.StreamTelemetryRequest
	(*StreamArtifactsRequest)(nil), // 9: serviceradar.agent.addon.v1.StreamArtifactsRequest
	(*RunCommandRequest)(nil),      // 10: serviceradar.agent.addon.v1.RunCommandRequest
	(*RunCommandResponse)(nil),     // 11: serviceradar.agent.addon.v1.RunCommandResponse
	(*ArtifactMetadata)(nil),       // 12: serviceradar.agent.addon.v1.ArtifactMetadata
	(*ArtifactUploadChunk)(nil),    // 13: serviceradar.agent.addon.v1.ArtifactUploadChunk
	(*TelemetrySource)(nil),        // 14: serviceradar.agent.addon.v1.TelemetrySource
	(*TelemetryCounters)(nil),      // 15: serviceradar.agent.addon.v1.TelemetryCounters
	(*TelemetryRecord)(nil),        // 16: serviceradar.agent.addon.v1.TelemetryRecord
	(*TelemetryBatch)(nil),         // 17: serviceradar.agent.addon.v1.TelemetryBatch
	(*OtlpRelayFrame)(nil),         // 18: serviceradar.agent.addon.v1.OtlpRelayFrame
	(*OtlpRelayAck)(nil),           // 19: serviceradar.agent.addon.v1.OtlpRelayAck
	(*MetricFeedFrame)(nil),        // 20: serviceradar.agent.addon.v1.MetricFeedFrame
	(*MetricFeedAck)(nil),          // 21: serviceradar.agent.addon.v1.MetricFeedAck
	nil,                            // 22: serviceradar.agent.addon.v1.HealthResponse.DetailsEntry
	nil,                            // 23: serviceradar.agent.addon.v1.RunCommandRequest.MetadataEntry
	nil,                            // 24: serviceradar.agent.addon.v1.RunCommandResponse.MetadataEntry
	nil,                            // 25: serviceradar.agent.addon.v1.ArtifactMetadata.AttributesEntry
	nil,                            // 26: serviceradar.agent.addon.v1.TelemetrySource.MetadataEntry
	nil,                            // 27: serviceradar.agent.addon.v1.TelemetryRecord.MetadataEntry
}
var file_agent_addon_v1_addon_proto_depIdxs = []int32{
	1,  // 0: serviceradar.agent.addon.v1.HealthResponse.status:type_name -> serviceradar.agent.addon.v1.HealthResponse.Status
	22, // 1: serviceradar.agent.addon.v1.HealthResponse.details:type_name -> serviceradar.agent.addon.v1.HealthResponse.DetailsEntry
	23, // 2: serviceradar.agent.addon.v1.RunCommandRequest.metadata:type_name -> serviceradar.agent.addon.v1.RunCommandRequest.MetadataEntry
	24, // 3: serviceradar.agent.addon.v1.RunCommandResponse.metadata:type_name -> serviceradar.agent.addon.v1.RunCommandResponse.MetadataEntry
	25, // 4: serviceradar.agent.addon.v1.ArtifactMetadata.attributes:type_name -> serviceradar.agent.addon.v1.ArtifactMetadata.AttributesEntry
	12, // 5: serviceradar.agent.addon.v1.ArtifactUploadChunk.metadata:type_name -> serviceradar.agent.addon.v1.ArtifactMetadata
	26, // 6: serviceradar.agent.addon.v1.TelemetrySource.metadata:type_name -> serviceradar.agent.addon.v1.TelemetrySource.MetadataEntry
	0,  // 7: serviceradar.agent.addon.v1.TelemetryRecord.payload_kind:type_name -> serviceradar.agent.addon.v1.TelemetryPayloadKind
	27, // 8: serviceradar.agent.addon.v1.TelemetryRecord.metadata:type_name -> serviceradar.agent.addon.v1.TelemetryRecord.MetadataEntry
	14, // 9: serviceradar.agent.addon.v1.TelemetryBatch.source:type_name -> serviceradar.agent.addon.v1.TelemetrySource
	16, // 10: serviceradar.agent.addon.v1.TelemetryBatch.records:type_name -> serviceradar.agent.addon.v1.TelemetryRecord
	15, // 11: serviceradar.agent.addon.v1.TelemetryBatch.counters:type_name -> serviceradar.agent.addon.v1.TelemetryCounters
	17, // 12: serviceradar.agent.addon.v1.OtlpRelayFrame.batch:type_name -> serviceradar.agent.addon.v1.TelemetryBatch
	14, // 13: serviceradar.agent.addon.v1.MetricFeedFrame.source:type_name -> serviceradar.agent.addon.v1.TelemetrySource
	2,  // 14: serviceradar.agent.addon.v1.AddonService.Info:input_type -> serviceradar.agent.addon.v1.InfoRequest
	4,  // 15: serviceradar.agent.addon.v1.AddonService.Configure:input_type -> serviceradar.agent.addon.v1.ConfigureRequest
	6,  // 16: serviceradar.agent.addon.v1.AddonService.Health:input_type -> serviceradar.agent.addon.v1.HealthRequest
	8,  // 17: serviceradar.agent.addon.v1.AddonService.StreamTelemetry:input_type -> serviceradar.agent.addon.v1.StreamTelemetryRequest
	9,  // 18: serviceradar.agent.addon.v1.AddonService.StreamArtifacts:input_type -> serviceradar.agent.addon.v1.StreamArtifactsRequest
	19, // 19: serviceradar.agent.addon.v1.AddonService.RelayOtlp:input_type -> serviceradar.agent.addon.v1.OtlpRelayAck
	20, // 20: serviceradar.agent.addon.v1.AddonService.StreamMetricFeed:input_type -> serviceradar.agent.addon.v1.MetricFeedFrame
	10, // 21: serviceradar.agent.addon.v1.AddonService.RunCommand:input_type -> serviceradar.agent.addon.v1.RunCommandRequest
	3,  // 22: serviceradar.agent.addon.v1.AddonService.Info:output_type -> serviceradar.agent.addon.v1.InfoResponse
	5,  // 23: serviceradar.agent.addon.v1.AddonService.Configure:output_type -> serviceradar.agent.addon.v1.ConfigureResponse
	7,  // 24: serviceradar.agent.addon.v1.AddonService.Health:output_type -> serviceradar.agent.addon.v1.HealthResponse
	17, // 25: serviceradar.agent.addon.v1.AddonService.StreamTelemetry:output_type -> serviceradar.agent.addon.v1.TelemetryBatch
	13, // 26: serviceradar.agent.addon.v1.AddonService.StreamArtifacts:output_type -> serviceradar.agent.addon.v1.ArtifactUploadChunk
	18, // 27: serviceradar.agent.addon.v1.AddonService.RelayOtlp:output_type -> serviceradar.agent.addon.v1.OtlpRelayFrame
	21, // 28: serviceradar.agent.addon.v1.AddonService.StreamMetricFeed:output_type -> serviceradar.agent.addon.v1.MetricFeedAck
	11, // 29: serviceradar.agent.addon.v1.AddonService.RunCommand:output_type -> serviceradar.agent.addon.v1.RunCommandResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_agent_addon_v1_addon_proto_init() }
func file_agent_addon_v1_addon_proto_init() {
	if File_agent_addon_v1_addon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_addon_v1_addon_proto_rawDesc), len(file_agent_addon_v1_addon_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_addon_v1_addon_proto_goTypes,
		DependencyIndexes: file_agent_addon_v1_addon_proto_depIdxs,
		EnumInfos:         file_agent_addon_v1_addon_proto_enumTypes,
		MessageInfos:      file_agent_addon_v1_addon_proto_msgTypes,
	}.Build()
	File_agent_addon_v1_addon_proto = out.File
	file_agent_addon_v1_addon_proto_goTypes = nil
	file_agent_addon_v1_addon_proto_depIdxs = nil
}
