load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_library(
    name = "edge_onboarding",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(
        cargo_only = True,
        normal = True,
    ),
)

rust_test(
    name = "edge_onboarding_test",
    crate = ":edge_onboarding",
    deps = [
        "@crates//:tempfile",
    ],
)
