load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("//third_party/crates:defs.bzl", "all_crate_deps")

rust_library(
    name = "edge_onboarding",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = all_crate_deps(normal = True),
    visibility = ["//visibility:public"],
)

rust_test(
    name = "edge_onboarding_test",
    crate = ":edge_onboarding",
    deps = [
        "//third_party/crates:tempfile",
    ],
)
