load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "serviceradar-sample-addon_lib",
    srcs = ["main.go"],
    importpath = "github.com/carverauto/serviceradar/go/cmd/serviceradar-sample-addon",
    visibility = ["//visibility:private"],
    deps = [
        "//go/pkg/addon",
        "//go/pkg/addon/sdk",
    ],
)

go_binary(
    name = "serviceradar-sample-addon",
    embed = [":serviceradar-sample-addon_lib"],
    visibility = ["//visibility:public"],
)
