load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")
load("//third_party/crates:defs.bzl", "all_crate_deps", "crate_deps")

package(default_visibility = ["//visibility:public"])

genrule_proto_srcs = [
    "src/proto/monitoring.proto",
    "src/proto/rperf.proto",
]

cargo_build_script(
    name = "build_script",
    srcs = ["build.rs"],
    crate_root = "build.rs",
    deps = crate_deps([
        "tonic-prost-build",
        "which",
    ]),
    data = genrule_proto_srcs,
    tools = ["@bazel_tools//tools/proto:protoc"],
    build_script_env = {
        "PROTOC": "$(execpath @bazel_tools//tools/proto:protoc)",
    },
)

rust_library(
    name = "rperf_checker_lib",
    srcs = glob(["src/**/*.rs"], exclude = ["src/main.rs"]),
    crate_root = "src/lib.rs",
    crate_name = "serviceradar_rperf_checker",
    compile_data = [
        "config/default_template.json",
    ],
    deps = all_crate_deps(normal = True) + [
        ":build_script",
        "//rust/metric-proto:serviceradar_metric_proto",
    ],
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_binary(
    name = "rperf_checker",
    srcs = ["src/main.rs"],
    deps = [":rperf_checker_lib", "//rust/config-bootstrap:config_bootstrap"] + all_crate_deps(normal = True),
)

rust_test(
    name = "rperf_client_test",
    crate = ":rperf_checker_lib",
)
