[package]
name = "serviceradar-rperf-checker"
version = "1.0.30"
edition = "2024"

description = "gRPC plugin for rperf network performance testing tool"
authors = ["Michael Freeman <mfreeman451@gmail.com>"]
license = "Apache-2.0"

[dependencies]
chrono = "0.4"
tokio = { workspace = true}
prost = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
tonic-health ={ workspace = true }
tonic-reflection =  { workspace = true }
tonic = { workspace = true }
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
pem = "3"
rustls = "0.23"
spiffe = { version = "0.16", default-features = false, features = ["x509-source"] }
config-bootstrap = { path = "../config-bootstrap" }
serviceradar-metric-proto = { path = "../metric-proto" }

[build-dependencies]
tonic-build = { workspace = true }
which = "7.0"
