[package]
name = "serviceradar-rperf-checker"
version = "1.0.30"
description = "gRPC plugin for rperf network performance testing tool"
authors = ["Michael Freeman <mfreeman451@gmail.com>"]
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
config-bootstrap = { path = "../config-bootstrap" }
env_logger = "0.11"
log = "0.4"
pem = "3"
prost = { workspace = true }
rustls = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serviceradar-metric-proto = { path = "../metric-proto" }
spiffe = { version = "0.16", default-features = false, features = ["x509-source"] }
tokio = { workspace = true}
tonic = { workspace = true }
tonic-health ={ workspace = true }
tonic-reflection =  { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
which = "7.0"
