spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
        - --source=service
        - --source=ingress
        - --namespace=demo
        - --namespace=demo-staging
        - --annotation-filter=external-dns.alpha.kubernetes.io/hostname
        - --domain-filter=carverauto.dev
        - --domain-filter=serviceradar.cloud
        - --domain-filter=guided.dev
        - --domain-filter=slowburnin.net
        - --provider=cloudflare
        - --cloudflare-dns-records-per-page=5000
        - --log-level=info
        - --policy=upsert-only
        - --request-timeout=30s
        - --min-event-sync-interval=5s
        - --events
