defmodule ServiceRadarWebNGWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :serviceradar_web_ng

  # The session is stored in the cookie and both signed AND encrypted.
  # `:encryption_salt` was added during the platform-security-hardening
  # change so the cookie value is no longer plaintext-readable. The
  # encryption secret is derived from `SECRET_KEY_BASE`, so the cookie
  # is opaque to anyone without that secret. Deployments that flip on
  # the new hardening for the first time will sign every active
  # session out once; subsequent deploys are seamless.
  #
  # The salts have stable production defaults in `config/prod.exs` and
  # can be overridden at release-build time with `SESSION_SIGNING_SALT`
  # and `SESSION_ENCRYPTION_SALT` when operators intentionally need to
  # invalidate active sessions. `SECRET_KEY_BASE` remains the runtime
  # secret that protects cookie signing/encryption keys.
  #
  # `Secure` is gated by `SESSION_COOKIE_SECURE` (default true in prod
  # builds) so the cookie is only sent over HTTPS; dev keeps
  # `secure: false` so login works against `http://localhost`.
  # `SameSite=Lax` is the standard setting for apps that use an
  # OAuth/OIDC redirect login: the IdP (Authentik) bounces the browser
  # back to `/auth/oidc/callback` as a top-level cross-site GET, and
  # `Strict` would withhold the session cookie on that navigation,
  # dropping the `:oidc_state`/`:oidc_nonce`/`:oidc_code_verifier` we
  # stored at `/auth/oidc` and failing state validation with
  # `:invalid_state`. `Lax` still
  # withholds the cookie on cross-site subresource loads and POSTs, and
  # CSRF on state-changing requests is already covered by Phoenix's
  # `csrf_token`.
  @session_options [
    store: :cookie,
    key: "_serviceradar_web_ng_key",
    same_site: "Lax",
    http_only: true,
    signing_salt: Application.compile_env!(:serviceradar_web_ng, [:session, :signing_salt]),
    encryption_salt: Application.compile_env!(:serviceradar_web_ng, [:session, :encryption_salt]),
    secure: Application.compile_env(:serviceradar_web_ng, [:session, :secure], false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options, uri: true]],
    longpoll: [connect_info: [session: @session_options, uri: true]]

  socket "/socket", ServiceRadarWebNGWeb.UserSocket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :serviceradar_web_ng,
    gzip: not code_reloading?,
    only: ServiceRadarWebNGWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    # Check repo status using serviceradar_core (where Ash migrations live)
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :serviceradar_core
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug ServiceRadarWebNGWeb.Plugs.SafeParsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {ServiceRadarWebNGWeb.Api.RawBodyReader, :read_body, []},
    # Bumped from Plug's 8 MB default to fit the dashboard-package publish
    # multipart upload: a 50 MB renderer cap (`Storage.max_upload_bytes`)
    # plus the 256 KB manifest plus multipart framing overhead. The
    # DashboardPackagePublishController enforces strict per-part caps
    # before any DB write — this is just the outer envelope.
    length: 67_108_864

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ServiceRadarWebNGWeb.Plugs.RequireMigrations
  plug ServiceRadarWebNGWeb.Router
end
