apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceradar-rperf-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceradar-rperf-client
  template:
    metadata:
      labels:
        app: serviceradar-rperf-client
    spec:
      {{- include "serviceradar.imagePullSecrets" . | nindent 6 }}
      initContainers:
        - name: init-rperf-config
          image: busybox:1.36
          command: ['sh', '-c', 'mkdir -p /etc/serviceradar/checkers && cp /config/rperf.json /etc/serviceradar/checkers/rperf.json']
          volumeMounts:
            - name: serviceradar-config
              mountPath: /config
            - name: checkers-dir
              mountPath: /etc/serviceradar/checkers
      containers:
      - name: rperf-checker
        image: ghcr.io/carverauto/serviceradar-rperf-client:{{ .Values.image.tags.rperfClient | default "latest" }}
        ports:
        - containerPort: 50081
          name: grpc
        volumeMounts:
        - name: serviceradar-config
          mountPath: /etc/serviceradar
        - name: cert-data
          mountPath: /etc/serviceradar/certs
          readOnly: true
        - name: checkers-dir
          mountPath: /etc/serviceradar/checkers
        env:
        - name: RUST_LOG
          value: "info"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          tcpSocket:
            port: 50081
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 50081
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: serviceradar-config
        configMap:
          name: serviceradar-config
      - name: cert-data
        persistentVolumeClaim:
          claimName: serviceradar-cert-data
      - name: checkers-dir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: serviceradar-rperf-client
spec:
  selector:
    app: serviceradar-rperf-client
  ports:
  - name: grpc
    port: 50081
    targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: serviceradar-rperf
spec:
  selector:
    app: serviceradar-rperf-client
  ports:
  - name: grpc
    port: 50081
    targetPort: grpc
