apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceradar-snmp-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceradar-snmp-checker
  template:
    metadata:
      labels:
        app: serviceradar-snmp-checker
    spec:
      serviceAccountName: {{ .Values.spire.snmpCheckerServiceAccount | default "serviceradar-snmp-checker" }}
      {{- include "serviceradar.imagePullSecrets" . | nindent 6 }}
      initContainers:
        - name: init-checkers
          image: busybox:1.36
          command: ['sh', '-c', 'mkdir -p /etc/serviceradar/checkers && cp /config/snmp.json /etc/serviceradar/checkers/snmp.json']
          volumeMounts:
            - name: serviceradar-config
              mountPath: /config
            - name: checkers-dir
              mountPath: /etc/serviceradar/checkers
      containers:
      - name: snmp-checker
        image: ghcr.io/carverauto/serviceradar-snmp-checker:{{ .Values.image.tags.snmpChecker }}
        ports:
        - containerPort: 50054
          name: grpc
        volumeMounts:
        - name: serviceradar-config
          mountPath: /etc/serviceradar
        - name: cert-data
          mountPath: /etc/serviceradar/certs
          readOnly: true
        - name: checkers-dir
          mountPath: /etc/serviceradar/checkers
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        env:
        - name: SERVICERADAR_CONFIG_PATH
          value: "/etc/serviceradar/snmp.json"
        - name: SERVICERADAR_CLOUD_ADDR
          value: "serviceradar-core:50052"
        - name: SERVICERADAR_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: "300m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
      volumes:
      - name: serviceradar-config
        configMap:
          name: serviceradar-config
      - name: cert-data
        persistentVolumeClaim:
          claimName: serviceradar-cert-data
      - name: checkers-dir
        emptyDir: {}
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: serviceradar-snmp-checker
spec:
  selector:
    app: serviceradar-snmp-checker
  ports:
  - name: grpc
    port: 50054
    targetPort: grpc

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.spire.snmpCheckerServiceAccount | default "serviceradar-snmp-checker" }}
  labels:
    app.kubernetes.io/part-of: serviceradar
