/*
 * Copyright 2026 Carver Automation Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package agent

// Add-on config contract tests (fj#4383, OpenSpec
// refactor-addon-lifecycle-operability task 4.3).
//
// The fixtures under testdata/addonconfig_contract/ are the exact config_json
// bytes core's delivery path emits for representative add-on assignments
// (including documented compatibility-form inputs, already schema-coerced).
// They are generated by the Elixir suite:
//
//	cd elixir/serviceradar_core && mix serviceradar.gen.addon_contract_fixtures
//
// and kept fresh by test/serviceradar/edge/addon_config_contract_fixtures_test.exs.
// This file decodes them with the REAL agent/add-on decoders, so a type-shape
// drift between core's emitter and an agent-side decoder fails CI instead of
// permanently wedging config apply in production (the netprobe
// capture_interfaces outage).
//
// Coverage split (decoders live where the add-on is implemented):
//   - netprobe: agent-side decoder, this file.
//   - bumblebee-scan, scalibr-endpoint-inventory: Go binaries, decoded here
//     with their importable config packages after the agent's real staged
//     base-config merge (mergeAddonRuntimeConfig).
//   - anomaly-addon, otel-collector, workload-identity: Rust binaries; the
//     same fixtures are decoded by in-crate Rust tests
//     (rust/anomaly-addon, rust/otel-addon, rust/workload-identity).
//   - rdp-adapter: has NO config decoder (stdio wire protocol, schema with
//     zero properties); the contract is that core delivers no config bytes.

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/carverauto/serviceradar/go/pkg/agent/netprobe"
	"github.com/carverauto/serviceradar/go/pkg/bumblebee"
	"github.com/carverauto/serviceradar/go/pkg/scalibrinventory"
	netprobepb "github.com/carverauto/serviceradar/proto/agent/netprobe/v1"
)

const addonConfigContractFixtureDir = "testdata/addonconfig_contract"

func readAddonConfigContractFixture(t *testing.T, addonID string) []byte {
	t.Helper()

	data, err := os.ReadFile(filepath.Join(addonConfigContractFixtureDir, addonID+".json"))
	require.NoError(t, err,
		"missing contract fixture for %s — regenerate with "+
			"`cd elixir/serviceradar_core && mix serviceradar.gen.addon_contract_fixtures`", addonID)

	return data
}

// mergeContractFixtureOverStagedBase reproduces what applyStagedAddonRuntimeConfig
// does on the agent: the delivered config_json is shallow-merged over the
// add-on's staged base config file, and the add-on binary decodes the merged
// document. Uses the agent's real merge implementation.
func mergeContractFixtureOverStagedBase(t *testing.T, addonID, baseConfigPath string) string {
	t.Helper()

	base, err := os.ReadFile(baseConfigPath)
	require.NoError(t, err)

	merged, err := mergeAddonRuntimeConfig(base, readAddonConfigContractFixture(t, addonID))
	require.NoError(t, err)

	mergedPath := filepath.Join(t.TempDir(), addonID+".json")
	require.NoError(t, os.WriteFile(mergedPath, merged, 0o600))

	return mergedPath
}

func TestAddonConfigContract_Netprobe(t *testing.T) {
	// The agent itself decodes netprobe's add-on config_json
	// (push_loop_config.go) and forwards it over the netprobe IPC.
	cfg, err := netprobe.ApplyAddonConfigJSON(
		&netprobepb.VisibilityAgentConfig{},
		readAddonConfigContractFixture(t, "netprobe"),
	)
	require.NoError(t, err)

	// The decoder is lenient (unknown fields ignored), so assert the values
	// round-tripped instead of relying on decode failure alone.
	require.True(t, cfg.GetEnabled())
	require.Equal(t, []string{"ens18", "ens19"}, cfg.GetCaptureInterfaces())
	require.Equal(t, uint32(500), cfg.GetDefaultSampleIntervalMs())
	require.Equal(t, uint32(65536), cfg.GetFlowTableMaxEntries())
	require.Equal(t, uint32(30), cfg.GetProcessSnapshotIntervalS())
	require.Equal(t, uint32(1500), cfg.GetExternalFlowMatchWindowMs())
	require.True(t, cfg.GetFlowAttributionIpcBatch())
	require.False(t, cfg.GetEmitRawFlowAttributionEvents())

	// dpi and device_bindings are declared by config.schema.json and emitted by
	// the control plane, but the agent's addonConfig decoded neither until now --
	// so an operator setting them through the add-on surface had them silently
	// ignored, with nothing erroring because an absent field keeps its base
	// value. Asserted here so the whole path stays exercised end to end.
	require.True(t, cfg.GetDpi().GetEnabled())
	require.Equal(t, []string{"tls", "http"}, cfg.GetDpi().GetProtocols())

	bindings := cfg.GetDeviceBindings()
	require.Len(t, bindings, 1)
	require.Equal(t, "192.168.1.10", bindings[0].GetIp())
	require.Equal(t, "camera-profile", bindings[0].GetProfileId())
	require.Equal(t, uint32(500), bindings[0].GetSampleIntervalMs())
	require.True(t, bindings[0].GetFingerprint().GetTcp())
	require.True(t, bindings[0].GetFingerprint().GetTls())
	require.False(t, bindings[0].GetFingerprint().GetHttp())
	require.True(t, bindings[0].GetDpi().GetEnabled())
	require.Equal(t, []string{"dns"}, bindings[0].GetDpi().GetProtocols())
}

func TestAddonConfigContract_BumblebeeScan(t *testing.T) {
	// bumblebee.LoadConfig uses DisallowUnknownFields: any key core emits
	// that the binary's struct does not declare fails the decode.
	mergedPath := mergeContractFixtureOverStagedBase(
		t,
		"bumblebee-scan",
		filepath.Join("..", "..", "..", "addons", "bumblebee-scan", "bumblebee-scan.json"),
	)

	cfg, err := bumblebee.LoadConfig(mergedPath)
	require.NoError(t, err)

	require.True(t, cfg.Enabled)
	require.Equal(t, "agent-demo-01", cfg.AgentID)
	require.Equal(t, "snapshot-42", cfg.CatalogSnapshotRef)
	require.Equal(t, []string{"/opt/apps", "/srv/data"}, cfg.ExplicitRoots)
	require.Equal(t, []string{"/proc", "/sys"}, cfg.ExcludeRoots)
	require.Equal(t, []string{"npm", "pypi"}, cfg.Ecosystems)
	require.Equal(t, 500, cfg.MaxFindings)
	require.False(t, cfg.IncludeRoot)
}

func TestAddonConfigContract_ScalibrEndpointInventory(t *testing.T) {
	// scalibrinventory.LoadConfig also uses DisallowUnknownFields.
	mergedPath := mergeContractFixtureOverStagedBase(
		t,
		"scalibr-endpoint-inventory",
		filepath.Join(
			"..", "..", "..",
			"addons", "scalibr-endpoint-inventory", "scalibr-endpoint-inventory.json",
		),
	)

	cfg, err := scalibrinventory.LoadConfig(mergedPath)
	require.NoError(t, err)

	require.True(t, cfg.Enabled)
	require.Equal(t, "agent-demo-01", cfg.AgentID)
	require.Equal(t, []string{"os/dpkg", "os/rpm", "os/apk"}, cfg.ScaLibrPlugins)
	require.Equal(t, []string{"/"}, cfg.ScanRoots)
	require.Equal(t, "12h", cfg.Cadence)
	require.True(t, cfg.CollectPaths)
	require.Equal(t, 100000, cfg.MaxPackages)
}

func TestAddonConfigContract_RDPAdapterDeliversNoConfig(t *testing.T) {
	// rdp-adapter consumes no staged config (its schema declares zero
	// properties and the binary speaks a stdio wire protocol). The contract
	// is that core delivers no config bytes, which the agent's staged-config
	// apply skips entirely.
	fixture := readAddonConfigContractFixture(t, "rdp-adapter")
	require.Empty(t, bytes.TrimSpace(fixture))
}
