// ServiceRadar configuration rule set.
//
// Validation is DATA, not per-language code. A rule names a field, a predicate, an
// evaluation phase, an environment scope, and a stable violation code. Three
// implementations read this same committed file, so a constraint is added once and
// enforced everywhere without any implementation changing.
//
// The scaling argument, from the audit that motivated this: hand-written checks scale as
// (fields x languages) -- ~58 x 3 today. A rule set scales as (predicates x languages),
// ~8 x 3, and eight predicates can be tested exhaustively where 58 fields cannot.
//
// THE VOCABULARY IS CLOSED. A rule cannot express arbitrary logic; it selects one of the
// predicates below. That is deliberate. A general expression language (CEL) would need a
// mature interpreter in all three languages, and none exists for Elixir -- protovalidate
// has no Elixir implementation, and the only BEAM-reachable CEL is a pre-1.0 Gleam library
// last released in 2024 with zero recent downloads. Adding a predicate is an explicit,
// reviewed change to this file plus conformance vectors, which is the intended friction.
//
// Semantics -- totality, cascading, ordering, phase and scope interaction -- are specified
// in config/SEMANTICS.md. That document is normative; this file only carries the shapes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: config/proto/rules.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// When a rule can be evaluated.
//
// Some constraints are checkable against the committed file alone; others need secrets
// resolved and therefore cannot run at build time. Without this distinction the build-time
// validator would fail on rules it structurally cannot evaluate.
type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	// Evaluated against the configuration file alone. Build time and runtime.
	Phase_PHASE_CONFIG Phase = 1
	// Evaluated only against configuration resolved together with secrets. Runtime only.
	Phase_PHASE_RESOLVED Phase = 2
	// Evaluated in both, against whatever is available in that phase.
	Phase_PHASE_BOTH Phase = 3
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_CONFIG",
		2: "PHASE_RESOLVED",
		3: "PHASE_BOTH",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_CONFIG":      1,
		"PHASE_RESOLVED":    2,
		"PHASE_BOTH":        3,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_rules_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_config_proto_rules_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{0}
}

// Which environments a rule applies to.
//
// Needed because on-prem is multi-instance: an invariant such as "verified TLS everywhere
// except localhost" must state whether it ranges over kinds or over every instance. A rule
// with no scope would be ambiguous the moment a second customer instance exists.
type Scope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means every environment. Otherwise the rule applies only to these kinds.
	Kinds []EnvironmentKind `protobuf:"varint,1,rep,packed,name=kinds,proto3,enum=serviceradar.config.v1.EnvironmentKind" json:"kinds,omitempty"`
	// Kinds explicitly exempted, applied after `kinds`.
	ExceptKinds   []EnvironmentKind `protobuf:"varint,2,rep,packed,name=except_kinds,json=exceptKinds,proto3,enum=serviceradar.config.v1.EnvironmentKind" json:"except_kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_config_proto_rules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetKinds() []EnvironmentKind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *Scope) GetExceptKinds() []EnvironmentKind {
	if x != nil {
		return x.ExceptKinds
	}
	return nil
}

// A field must be present. Explicit presence, not a non-zero value.
type Required struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Required) Reset() {
	*x = Required{}
	mi := &file_config_proto_rules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Required) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Required) ProtoMessage() {}

func (x *Required) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Required.ProtoReflect.Descriptor instead.
func (*Required) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{1}
}

// A present string, bytes or repeated field must have non-zero length.
//
// Absence is NOT a violation of this predicate -- see the cascading rule in SEMANTICS.md.
// Pair with `Required` when both matter.
type NonEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonEmpty) Reset() {
	*x = NonEmpty{}
	mi := &file_config_proto_rules_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonEmpty) ProtoMessage() {}

func (x *NonEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonEmpty.ProtoReflect.Descriptor instead.
func (*NonEmpty) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{2}
}

// A present numeric field must lie within [min, max], inclusive at both ends.
type IntRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *int64                 `protobuf:"varint,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *int64                 `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntRange) Reset() {
	*x = IntRange{}
	mi := &file_config_proto_rules_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntRange) ProtoMessage() {}

func (x *IntRange) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntRange.ProtoReflect.Descriptor instead.
func (*IntRange) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{3}
}

func (x *IntRange) GetMin() int64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *IntRange) GetMax() int64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

// A present field's value must be a member of the permitted set.
//
// `enum_values` names enum value identifiers; `string_values` names string literals.
// Exactly one list is populated, determined by the field's type.
type OneOf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnumValues    []string               `protobuf:"bytes,1,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	StringValues  []string               `protobuf:"bytes,2,rep,name=string_values,json=stringValues,proto3" json:"string_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOf) Reset() {
	*x = OneOf{}
	mi := &file_config_proto_rules_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOf) ProtoMessage() {}

func (x *OneOf) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOf.ProtoReflect.Descriptor instead.
func (*OneOf) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{4}
}

func (x *OneOf) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *OneOf) GetStringValues() []string {
	if x != nil {
		return x.StringValues
	}
	return nil
}

// A present string field must match the regular expression.
//
// The pattern is RE2 syntax, which all three implementations support without backtracking
// and therefore without a pathological-input class.
type Matches struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       *string                `protobuf:"bytes,1,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matches) Reset() {
	*x = Matches{}
	mi := &file_config_proto_rules_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matches) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matches) ProtoMessage() {}

func (x *Matches) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matches.ProtoReflect.Descriptor instead.
func (*Matches) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{5}
}

func (x *Matches) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

// A field is required when another field holds a given value.
//
// The motivating case: `tls_server_name` is required when `tls_mode` is VERIFY_FULL,
// because the fixture certificate carries DNS SANs and no IP SANs.
type RequiredIf struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OtherFieldPath   *string                `protobuf:"bytes,1,opt,name=other_field_path,json=otherFieldPath,proto3,oneof" json:"other_field_path,omitempty"`
	OtherEnumValue   *string                `protobuf:"bytes,2,opt,name=other_enum_value,json=otherEnumValue,proto3,oneof" json:"other_enum_value,omitempty"`
	OtherStringValue *string                `protobuf:"bytes,3,opt,name=other_string_value,json=otherStringValue,proto3,oneof" json:"other_string_value,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequiredIf) Reset() {
	*x = RequiredIf{}
	mi := &file_config_proto_rules_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredIf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredIf) ProtoMessage() {}

func (x *RequiredIf) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredIf.ProtoReflect.Descriptor instead.
func (*RequiredIf) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{6}
}

func (x *RequiredIf) GetOtherFieldPath() string {
	if x != nil && x.OtherFieldPath != nil {
		return *x.OtherFieldPath
	}
	return ""
}

func (x *RequiredIf) GetOtherEnumValue() string {
	if x != nil && x.OtherEnumValue != nil {
		return *x.OtherEnumValue
	}
	return ""
}

func (x *RequiredIf) GetOtherStringValue() string {
	if x != nil && x.OtherStringValue != nil {
		return *x.OtherStringValue
	}
	return ""
}

// A present field must NOT hold the given value.
//
// The motivating case: rejecting an `*_UNSPECIFIED` enum sentinel, so an unset enum is an
// error rather than accidentally the first defined value.
type ForbiddenValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnumValue     *string                `protobuf:"bytes,1,opt,name=enum_value,json=enumValue,proto3,oneof" json:"enum_value,omitempty"`
	StringValue   *string                `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof" json:"string_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForbiddenValue) Reset() {
	*x = ForbiddenValue{}
	mi := &file_config_proto_rules_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForbiddenValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForbiddenValue) ProtoMessage() {}

func (x *ForbiddenValue) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForbiddenValue.ProtoReflect.Descriptor instead.
func (*ForbiddenValue) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{7}
}

func (x *ForbiddenValue) GetEnumValue() string {
	if x != nil && x.EnumValue != nil {
		return *x.EnumValue
	}
	return ""
}

func (x *ForbiddenValue) GetStringValue() string {
	if x != nil && x.StringValue != nil {
		return *x.StringValue
	}
	return ""
}

// A field must be ABSENT when another field holds one of the given values.
//
// The trigger is a SET, unlike RequiredIf's single value. The forbidding side almost always
// enumerates the COMPLEMENT of one permitted value, and writing one rule per excluded value
// is precisely how a newly added enum value silently becomes permitted. The meta-rule checks
// that a RequiredIf/ForbiddenIf pair keyed on the same enum covers every value of it.
//
// The motivating case: `instance` names an on-prem deployment, so it is required when the
// kind is ONPREM and must be absent otherwise -- the half that previously had no predicate,
// leaving the proto's "must be absent otherwise" unenforceable.
type ForbiddenIf struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OtherFieldPath    *string                `protobuf:"bytes,1,opt,name=other_field_path,json=otherFieldPath,proto3,oneof" json:"other_field_path,omitempty"`
	OtherEnumValues   []string               `protobuf:"bytes,2,rep,name=other_enum_values,json=otherEnumValues,proto3" json:"other_enum_values,omitempty"`
	OtherStringValues []string               `protobuf:"bytes,3,rep,name=other_string_values,json=otherStringValues,proto3" json:"other_string_values,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ForbiddenIf) Reset() {
	*x = ForbiddenIf{}
	mi := &file_config_proto_rules_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForbiddenIf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForbiddenIf) ProtoMessage() {}

func (x *ForbiddenIf) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForbiddenIf.ProtoReflect.Descriptor instead.
func (*ForbiddenIf) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{8}
}

func (x *ForbiddenIf) GetOtherFieldPath() string {
	if x != nil && x.OtherFieldPath != nil {
		return *x.OtherFieldPath
	}
	return ""
}

func (x *ForbiddenIf) GetOtherEnumValues() []string {
	if x != nil {
		return x.OtherEnumValues
	}
	return nil
}

func (x *ForbiddenIf) GetOtherStringValues() []string {
	if x != nil {
		return x.OtherStringValues
	}
	return nil
}

// The field must hold the same value in every environment within scope.
//
// Evaluated across instances rather than within one, so it runs only in the build-time
// validator, which sees them all.
type EqualAcrossEnvs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EqualAcrossEnvs) Reset() {
	*x = EqualAcrossEnvs{}
	mi := &file_config_proto_rules_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EqualAcrossEnvs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EqualAcrossEnvs) ProtoMessage() {}

func (x *EqualAcrossEnvs) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EqualAcrossEnvs.ProtoReflect.Descriptor instead.
func (*EqualAcrossEnvs) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{9}
}

// One rule.
//
// The predicate is a oneof rather than an enum plus a separate parameter message, so a
// predicate and its parameters cannot disagree -- an entire class of malformed rule is
// unrepresentable.
type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dotted path from the root message, e.g. "database.tls_server_name".
	FieldPath *string `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3,oneof" json:"field_path,omitempty"`
	// Stable identifier for this violation, e.g. "DATABASE_TLS_SERVER_NAME_REQUIRED".
	// Conformance vectors assert this code, not merely that validation rejected the input,
	// so three implementations cannot agree on rejection while disagreeing on why.
	Code  *string `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Phase *Phase  `protobuf:"varint,3,opt,name=phase,proto3,enum=serviceradar.config.v1.Phase,oneof" json:"phase,omitempty"`
	Scope *Scope  `protobuf:"bytes,4,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	// Human-readable explanation, surfaced with the violation.
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Types that are valid to be assigned to Predicate:
	//
	//	*Rule_Required
	//	*Rule_NonEmpty
	//	*Rule_IntRange
	//	*Rule_OneOf
	//	*Rule_Matches
	//	*Rule_RequiredIf
	//	*Rule_ForbiddenValue
	//	*Rule_EqualAcrossEnvs
	//	*Rule_ForbiddenIf
	Predicate     isRule_Predicate `protobuf_oneof:"predicate"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_config_proto_rules_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{10}
}

func (x *Rule) GetFieldPath() string {
	if x != nil && x.FieldPath != nil {
		return *x.FieldPath
	}
	return ""
}

func (x *Rule) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *Rule) GetPhase() Phase {
	if x != nil && x.Phase != nil {
		return *x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *Rule) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Rule) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Rule) GetPredicate() isRule_Predicate {
	if x != nil {
		return x.Predicate
	}
	return nil
}

func (x *Rule) GetRequired() *Required {
	if x != nil {
		if x, ok := x.Predicate.(*Rule_Required); ok {
			return x.Required
		}
	}
	return nil
}

func (x *Rule) GetNonEmpty() *NonEmpty {
	if x != nil {
		if x, ok := x.Predicate.(*Rule_NonEmpty); ok {
			return x.NonEmpty
		}
	}
	return nil
}

func (x *Rule) GetIntRange() *IntRange {
	if x != nil {
		if x, ok := x.Predicate.(*Rule_IntRange); ok {
			return x.IntRange
		}
	}
	return nil
}

func (x *Rule) GetOneOf() *OneOf {
	if x != nil {
		if x, ok := x.Predicate.(*Rule_OneOf); ok {
			return x.OneOf
		}
	}
	return nil
}

func (x *Rule) GetMatches() *Matches {
	if x != nil {
		if x, ok := x.Predicate.(*Rule_Matches); ok {
			return x.Matches
		}
	}
	return nil
}

func (x *Rule) GetRequiredIf() *RequiredIf {
	if x != nil {
		if x, ok := x.Predicate.(*Rule_RequiredIf); ok {
			return x.RequiredIf
		}
	}
	return nil
}

func (x *Rule) GetForbiddenValue() *ForbiddenValue {
	if x != nil {
		if x, ok := x.Predicate.(*Rule_ForbiddenValue); ok {
			return x.ForbiddenValue
		}
	}
	return nil
}

func (x *Rule) GetEqualAcrossEnvs() *EqualAcrossEnvs {
	if x != nil {
		if x, ok := x.Predicate.(*Rule_EqualAcrossEnvs); ok {
			return x.EqualAcrossEnvs
		}
	}
	return nil
}

func (x *Rule) GetForbiddenIf() *ForbiddenIf {
	if x != nil {
		if x, ok := x.Predicate.(*Rule_ForbiddenIf); ok {
			return x.ForbiddenIf
		}
	}
	return nil
}

type isRule_Predicate interface {
	isRule_Predicate()
}

type Rule_Required struct {
	Required *Required `protobuf:"bytes,10,opt,name=required,proto3,oneof"`
}

type Rule_NonEmpty struct {
	NonEmpty *NonEmpty `protobuf:"bytes,11,opt,name=non_empty,json=nonEmpty,proto3,oneof"`
}

type Rule_IntRange struct {
	IntRange *IntRange `protobuf:"bytes,12,opt,name=int_range,json=intRange,proto3,oneof"`
}

type Rule_OneOf struct {
	OneOf *OneOf `protobuf:"bytes,13,opt,name=one_of,json=oneOf,proto3,oneof"`
}

type Rule_Matches struct {
	Matches *Matches `protobuf:"bytes,14,opt,name=matches,proto3,oneof"`
}

type Rule_RequiredIf struct {
	RequiredIf *RequiredIf `protobuf:"bytes,15,opt,name=required_if,json=requiredIf,proto3,oneof"`
}

type Rule_ForbiddenValue struct {
	ForbiddenValue *ForbiddenValue `protobuf:"bytes,16,opt,name=forbidden_value,json=forbiddenValue,proto3,oneof"`
}

type Rule_EqualAcrossEnvs struct {
	EqualAcrossEnvs *EqualAcrossEnvs `protobuf:"bytes,17,opt,name=equal_across_envs,json=equalAcrossEnvs,proto3,oneof"`
}

type Rule_ForbiddenIf struct {
	ForbiddenIf *ForbiddenIf `protobuf:"bytes,18,opt,name=forbidden_if,json=forbiddenIf,proto3,oneof"`
}

func (*Rule_Required) isRule_Predicate() {}

func (*Rule_NonEmpty) isRule_Predicate() {}

func (*Rule_IntRange) isRule_Predicate() {}

func (*Rule_OneOf) isRule_Predicate() {}

func (*Rule_Matches) isRule_Predicate() {}

func (*Rule_RequiredIf) isRule_Predicate() {}

func (*Rule_ForbiddenValue) isRule_Predicate() {}

func (*Rule_EqualAcrossEnvs) isRule_Predicate() {}

func (*Rule_ForbiddenIf) isRule_Predicate() {}

// The committed rule set.
type RuleSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSet) Reset() {
	*x = RuleSet{}
	mi := &file_config_proto_rules_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSet) ProtoMessage() {}

func (x *RuleSet) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSet.ProtoReflect.Descriptor instead.
func (*RuleSet) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{11}
}

func (x *RuleSet) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// A violation a fixture is expected to produce.
//
// Identity, not merely rejection: three implementations can reject the same input for three
// different reasons and a bare accept/reject assertion would stay green. Vectors compare
// (code, field_path).
type ExpectedViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *string                `protobuf:"bytes,1,opt,name=code,proto3,oneof" json:"code,omitempty"`
	FieldPath     *string                `protobuf:"bytes,2,opt,name=field_path,json=fieldPath,proto3,oneof" json:"field_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpectedViolation) Reset() {
	*x = ExpectedViolation{}
	mi := &file_config_proto_rules_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpectedViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpectedViolation) ProtoMessage() {}

func (x *ExpectedViolation) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpectedViolation.ProtoReflect.Descriptor instead.
func (*ExpectedViolation) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{12}
}

func (x *ExpectedViolation) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *ExpectedViolation) GetFieldPath() string {
	if x != nil && x.FieldPath != nil {
		return *x.FieldPath
	}
	return ""
}

// One conformance case.
//
// Serves both roles in this design: the NEGATIVE FIXTURE that makes deleting a rule fail a
// test (SEMANTICS.md section 8), and the CONFORMANCE VECTOR that all three implementations
// must reproduce (section 10). They are the same artifact, so a rule cannot gain a fixture
// without gaining a vector.
type Fixture struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Phase       *Phase                 `protobuf:"varint,3,opt,name=phase,proto3,enum=serviceradar.config.v1.Phase,oneof" json:"phase,omitempty"`
	Instance    *EnvironmentConfig     `protobuf:"bytes,4,opt,name=instance,proto3,oneof" json:"instance,omitempty"`
	// Empty means the instance must validate cleanly.
	ExpectedViolations []*ExpectedViolation `protobuf:"bytes,5,rep,name=expected_violations,json=expectedViolations,proto3" json:"expected_violations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Fixture) Reset() {
	*x = Fixture{}
	mi := &file_config_proto_rules_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fixture) ProtoMessage() {}

func (x *Fixture) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fixture.ProtoReflect.Descriptor instead.
func (*Fixture) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{13}
}

func (x *Fixture) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Fixture) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Fixture) GetPhase() Phase {
	if x != nil && x.Phase != nil {
		return *x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *Fixture) GetInstance() *EnvironmentConfig {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *Fixture) GetExpectedViolations() []*ExpectedViolation {
	if x != nil {
		return x.ExpectedViolations
	}
	return nil
}

type FixtureSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fixtures      []*Fixture             `protobuf:"bytes,1,rep,name=fixtures,proto3" json:"fixtures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixtureSet) Reset() {
	*x = FixtureSet{}
	mi := &file_config_proto_rules_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureSet) ProtoMessage() {}

func (x *FixtureSet) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_rules_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureSet.ProtoReflect.Descriptor instead.
func (*FixtureSet) Descriptor() ([]byte, []int) {
	return file_config_proto_rules_proto_rawDescGZIP(), []int{14}
}

func (x *FixtureSet) GetFixtures() []*Fixture {
	if x != nil {
		return x.Fixtures
	}
	return nil
}

var File_config_proto_rules_proto protoreflect.FileDescriptor

const file_config_proto_rules_proto_rawDesc = "" +
	"\n" +
	"\x18config/proto/rules.proto\x12\x16serviceradar.config.v1\x1a\x19config/proto/config.proto\"\x92\x01\n" +
	"\x05Scope\x12=\n" +
	"\x05kinds\x18\x01 \x03(\x0e2'.serviceradar.config.v1.EnvironmentKindR\x05kinds\x12J\n" +
	"\fexcept_kinds\x18\x02 \x03(\x0e2'.serviceradar.config.v1.EnvironmentKindR\vexceptKinds\"\n" +
	"\n" +
	"\bRequired\"\n" +
	"\n" +
	"\bNonEmpty\"H\n" +
	"\bIntRange\x12\x15\n" +
	"\x03min\x18\x01 \x01(\x03H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x03H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"M\n" +
	"\x05OneOf\x12\x1f\n" +
	"\venum_values\x18\x01 \x03(\tR\n" +
	"enumValues\x12#\n" +
	"\rstring_values\x18\x02 \x03(\tR\fstringValues\"4\n" +
	"\aMatches\x12\x1d\n" +
	"\apattern\x18\x01 \x01(\tH\x00R\apattern\x88\x01\x01B\n" +
	"\n" +
	"\b_pattern\"\xde\x01\n" +
	"\n" +
	"RequiredIf\x12-\n" +
	"\x10other_field_path\x18\x01 \x01(\tH\x00R\x0eotherFieldPath\x88\x01\x01\x12-\n" +
	"\x10other_enum_value\x18\x02 \x01(\tH\x01R\x0eotherEnumValue\x88\x01\x01\x121\n" +
	"\x12other_string_value\x18\x03 \x01(\tH\x02R\x10otherStringValue\x88\x01\x01B\x13\n" +
	"\x11_other_field_pathB\x13\n" +
	"\x11_other_enum_valueB\x15\n" +
	"\x13_other_string_value\"|\n" +
	"\x0eForbiddenValue\x12\"\n" +
	"\n" +
	"enum_value\x18\x01 \x01(\tH\x00R\tenumValue\x88\x01\x01\x12&\n" +
	"\fstring_value\x18\x02 \x01(\tH\x01R\vstringValue\x88\x01\x01B\r\n" +
	"\v_enum_valueB\x0f\n" +
	"\r_string_value\"\xad\x01\n" +
	"\vForbiddenIf\x12-\n" +
	"\x10other_field_path\x18\x01 \x01(\tH\x00R\x0eotherFieldPath\x88\x01\x01\x12*\n" +
	"\x11other_enum_values\x18\x02 \x03(\tR\x0fotherEnumValues\x12.\n" +
	"\x13other_string_values\x18\x03 \x03(\tR\x11otherStringValuesB\x13\n" +
	"\x11_other_field_path\"\x11\n" +
	"\x0fEqualAcrossEnvs\"\x99\a\n" +
	"\x04Rule\x12\"\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tH\x01R\tfieldPath\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tH\x02R\x04code\x88\x01\x01\x128\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x1d.serviceradar.config.v1.PhaseH\x03R\x05phase\x88\x01\x01\x128\n" +
	"\x05scope\x18\x04 \x01(\v2\x1d.serviceradar.config.v1.ScopeH\x04R\x05scope\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x05R\vdescription\x88\x01\x01\x12>\n" +
	"\brequired\x18\n" +
	" \x01(\v2 .serviceradar.config.v1.RequiredH\x00R\brequired\x12?\n" +
	"\tnon_empty\x18\v \x01(\v2 .serviceradar.config.v1.NonEmptyH\x00R\bnonEmpty\x12?\n" +
	"\tint_range\x18\f \x01(\v2 .serviceradar.config.v1.IntRangeH\x00R\bintRange\x126\n" +
	"\x06one_of\x18\r \x01(\v2\x1d.serviceradar.config.v1.OneOfH\x00R\x05oneOf\x12;\n" +
	"\amatches\x18\x0e \x01(\v2\x1f.serviceradar.config.v1.MatchesH\x00R\amatches\x12E\n" +
	"\vrequired_if\x18\x0f \x01(\v2\".serviceradar.config.v1.RequiredIfH\x00R\n" +
	"requiredIf\x12Q\n" +
	"\x0fforbidden_value\x18\x10 \x01(\v2&.serviceradar.config.v1.ForbiddenValueH\x00R\x0eforbiddenValue\x12U\n" +
	"\x11equal_across_envs\x18\x11 \x01(\v2'.serviceradar.config.v1.EqualAcrossEnvsH\x00R\x0fequalAcrossEnvs\x12H\n" +
	"\fforbidden_if\x18\x12 \x01(\v2#.serviceradar.config.v1.ForbiddenIfH\x00R\vforbiddenIfB\v\n" +
	"\tpredicateB\r\n" +
	"\v_field_pathB\a\n" +
	"\x05_codeB\b\n" +
	"\x06_phaseB\b\n" +
	"\x06_scopeB\x0e\n" +
	"\f_description\"=\n" +
	"\aRuleSet\x122\n" +
	"\x05rules\x18\x01 \x03(\v2\x1c.serviceradar.config.v1.RuleR\x05rules\"h\n" +
	"\x11ExpectedViolation\x12\x17\n" +
	"\x04code\x18\x01 \x01(\tH\x00R\x04code\x88\x01\x01\x12\"\n" +
	"\n" +
	"field_path\x18\x02 \x01(\tH\x01R\tfieldPath\x88\x01\x01B\a\n" +
	"\x05_codeB\r\n" +
	"\v_field_path\"\xdb\x02\n" +
	"\aFixture\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x128\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x1d.serviceradar.config.v1.PhaseH\x02R\x05phase\x88\x01\x01\x12J\n" +
	"\binstance\x18\x04 \x01(\v2).serviceradar.config.v1.EnvironmentConfigH\x03R\binstance\x88\x01\x01\x12Z\n" +
	"\x13expected_violations\x18\x05 \x03(\v2).serviceradar.config.v1.ExpectedViolationR\x12expectedViolationsB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_phaseB\v\n" +
	"\t_instance\"I\n" +
	"\n" +
	"FixtureSet\x12;\n" +
	"\bfixtures\x18\x01 \x03(\v2\x1f.serviceradar.config.v1.FixtureR\bfixtures*T\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPHASE_CONFIG\x10\x01\x12\x12\n" +
	"\x0ePHASE_RESOLVED\x10\x02\x12\x0e\n" +
	"\n" +
	"PHASE_BOTH\x10\x03B:Z8github.com/carverauto/serviceradar/config/proto;configpbb\x06proto3"

var (
	file_config_proto_rules_proto_rawDescOnce sync.Once
	file_config_proto_rules_proto_rawDescData []byte
)

func file_config_proto_rules_proto_rawDescGZIP() []byte {
	file_config_proto_rules_proto_rawDescOnce.Do(func() {
		file_config_proto_rules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rules_proto_rawDesc), len(file_config_proto_rules_proto_rawDesc)))
	})
	return file_config_proto_rules_proto_rawDescData
}

var file_config_proto_rules_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_proto_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_config_proto_rules_proto_goTypes = []any{
	(Phase)(0),                // 0: serviceradar.config.v1.Phase
	(*Scope)(nil),             // 1: serviceradar.config.v1.Scope
	(*Required)(nil),          // 2: serviceradar.config.v1.Required
	(*NonEmpty)(nil),          // 3: serviceradar.config.v1.NonEmpty
	(*IntRange)(nil),          // 4: serviceradar.config.v1.IntRange
	(*OneOf)(nil),             // 5: serviceradar.config.v1.OneOf
	(*Matches)(nil),           // 6: serviceradar.config.v1.Matches
	(*RequiredIf)(nil),        // 7: serviceradar.config.v1.RequiredIf
	(*ForbiddenValue)(nil),    // 8: serviceradar.config.v1.ForbiddenValue
	(*ForbiddenIf)(nil),       // 9: serviceradar.config.v1.ForbiddenIf
	(*EqualAcrossEnvs)(nil),   // 10: serviceradar.config.v1.EqualAcrossEnvs
	(*Rule)(nil),              // 11: serviceradar.config.v1.Rule
	(*RuleSet)(nil),           // 12: serviceradar.config.v1.RuleSet
	(*ExpectedViolation)(nil), // 13: serviceradar.config.v1.ExpectedViolation
	(*Fixture)(nil),           // 14: serviceradar.config.v1.Fixture
	(*FixtureSet)(nil),        // 15: serviceradar.config.v1.FixtureSet
	(EnvironmentKind)(0),      // 16: serviceradar.config.v1.EnvironmentKind
	(*EnvironmentConfig)(nil), // 17: serviceradar.config.v1.EnvironmentConfig
}
var file_config_proto_rules_proto_depIdxs = []int32{
	16, // 0: serviceradar.config.v1.Scope.kinds:type_name -> serviceradar.config.v1.EnvironmentKind
	16, // 1: serviceradar.config.v1.Scope.except_kinds:type_name -> serviceradar.config.v1.EnvironmentKind
	0,  // 2: serviceradar.config.v1.Rule.phase:type_name -> serviceradar.config.v1.Phase
	1,  // 3: serviceradar.config.v1.Rule.scope:type_name -> serviceradar.config.v1.Scope
	2,  // 4: serviceradar.config.v1.Rule.required:type_name -> serviceradar.config.v1.Required
	3,  // 5: serviceradar.config.v1.Rule.non_empty:type_name -> serviceradar.config.v1.NonEmpty
	4,  // 6: serviceradar.config.v1.Rule.int_range:type_name -> serviceradar.config.v1.IntRange
	5,  // 7: serviceradar.config.v1.Rule.one_of:type_name -> serviceradar.config.v1.OneOf
	6,  // 8: serviceradar.config.v1.Rule.matches:type_name -> serviceradar.config.v1.Matches
	7,  // 9: serviceradar.config.v1.Rule.required_if:type_name -> serviceradar.config.v1.RequiredIf
	8,  // 10: serviceradar.config.v1.Rule.forbidden_value:type_name -> serviceradar.config.v1.ForbiddenValue
	10, // 11: serviceradar.config.v1.Rule.equal_across_envs:type_name -> serviceradar.config.v1.EqualAcrossEnvs
	9,  // 12: serviceradar.config.v1.Rule.forbidden_if:type_name -> serviceradar.config.v1.ForbiddenIf
	11, // 13: serviceradar.config.v1.RuleSet.rules:type_name -> serviceradar.config.v1.Rule
	0,  // 14: serviceradar.config.v1.Fixture.phase:type_name -> serviceradar.config.v1.Phase
	17, // 15: serviceradar.config.v1.Fixture.instance:type_name -> serviceradar.config.v1.EnvironmentConfig
	13, // 16: serviceradar.config.v1.Fixture.expected_violations:type_name -> serviceradar.config.v1.ExpectedViolation
	14, // 17: serviceradar.config.v1.FixtureSet.fixtures:type_name -> serviceradar.config.v1.Fixture
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_config_proto_rules_proto_init() }
func file_config_proto_rules_proto_init() {
	if File_config_proto_rules_proto != nil {
		return
	}
	file_config_proto_config_proto_init()
	file_config_proto_rules_proto_msgTypes[3].OneofWrappers = []any{}
	file_config_proto_rules_proto_msgTypes[5].OneofWrappers = []any{}
	file_config_proto_rules_proto_msgTypes[6].OneofWrappers = []any{}
	file_config_proto_rules_proto_msgTypes[7].OneofWrappers = []any{}
	file_config_proto_rules_proto_msgTypes[8].OneofWrappers = []any{}
	file_config_proto_rules_proto_msgTypes[10].OneofWrappers = []any{
		(*Rule_Required)(nil),
		(*Rule_NonEmpty)(nil),
		(*Rule_IntRange)(nil),
		(*Rule_OneOf)(nil),
		(*Rule_Matches)(nil),
		(*Rule_RequiredIf)(nil),
		(*Rule_ForbiddenValue)(nil),
		(*Rule_EqualAcrossEnvs)(nil),
		(*Rule_ForbiddenIf)(nil),
	}
	file_config_proto_rules_proto_msgTypes[12].OneofWrappers = []any{}
	file_config_proto_rules_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rules_proto_rawDesc), len(file_config_proto_rules_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_rules_proto_goTypes,
		DependencyIndexes: file_config_proto_rules_proto_depIdxs,
		EnumInfos:         file_config_proto_rules_proto_enumTypes,
		MessageInfos:      file_config_proto_rules_proto_msgTypes,
	}.Build()
	File_config_proto_rules_proto = out.File
	file_config_proto_rules_proto_goTypes = nil
	file_config_proto_rules_proto_depIdxs = nil
}
