[package]
name = "rperf-grpc"
version = "0.1.0"
edition = "2021"
description = "gRPC plugin for rperf network performance testing tool"
authors = ["Your Name <your.email@example.com>"]
license = "Apache-2.0"

[dependencies]
rperf = { path = "/Users/mfreeman/src/rperf" }

tonic = "0.12.3"
prost = "0.13.5"
tokio = { version = "1.28", features = ["rt-multi-thread", "macros", "sync", "time", "signal"] }
futures = "0.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11.7"
clap = { version = "4.5.32", features = ["derive"] }
anyhow = "1.0"

[build-dependencies]
tonic-build = "0.12.3"