//
// Copyright 2026 Carver Automation Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: desktop_media.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DesktopMediaService_OpenDesktopMediaSession_FullMethodName  = "/desktopmedia.DesktopMediaService/OpenDesktopMediaSession"
	DesktopMediaService_StreamDesktopMedia_FullMethodName       = "/desktopmedia.DesktopMediaService/StreamDesktopMedia"
	DesktopMediaService_Heartbeat_FullMethodName                = "/desktopmedia.DesktopMediaService/Heartbeat"
	DesktopMediaService_CloseDesktopMediaSession_FullMethodName = "/desktopmedia.DesktopMediaService/CloseDesktopMediaSession"
)

// DesktopMediaServiceClient is the client API for DesktopMediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DesktopMediaService carries high-volume graphical desktop updates outside
// the generic remote-access control stream.
type DesktopMediaServiceClient interface {
	// OpenDesktopMediaSession reserves an authenticated, route-bound desktop
	// media session for a previously approved desktop control session.
	OpenDesktopMediaSession(ctx context.Context, in *OpenDesktopMediaSessionRequest, opts ...grpc.CallOption) (*OpenDesktopMediaSessionResponse, error)
	// StreamDesktopMedia carries screen/cursor/update chunks from the agent and
	// credit, quality, pause/resume, and close acknowledgements from the gateway.
	StreamDesktopMedia(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DesktopMediaClientMessage, DesktopMediaServerMessage], error)
	// Heartbeat renews the desktop media lease and reports edge-side progress.
	Heartbeat(ctx context.Context, in *DesktopMediaHeartbeat, opts ...grpc.CallOption) (*DesktopMediaHeartbeatAck, error)
	// CloseDesktopMediaSession explicitly closes an active or pending media session.
	CloseDesktopMediaSession(ctx context.Context, in *CloseDesktopMediaSessionRequest, opts ...grpc.CallOption) (*CloseDesktopMediaSessionResponse, error)
}

type desktopMediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDesktopMediaServiceClient(cc grpc.ClientConnInterface) DesktopMediaServiceClient {
	return &desktopMediaServiceClient{cc}
}

func (c *desktopMediaServiceClient) OpenDesktopMediaSession(ctx context.Context, in *OpenDesktopMediaSessionRequest, opts ...grpc.CallOption) (*OpenDesktopMediaSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenDesktopMediaSessionResponse)
	err := c.cc.Invoke(ctx, DesktopMediaService_OpenDesktopMediaSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopMediaServiceClient) StreamDesktopMedia(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DesktopMediaClientMessage, DesktopMediaServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DesktopMediaService_ServiceDesc.Streams[0], DesktopMediaService_StreamDesktopMedia_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DesktopMediaClientMessage, DesktopMediaServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopMediaService_StreamDesktopMediaClient = grpc.BidiStreamingClient[DesktopMediaClientMessage, DesktopMediaServerMessage]

func (c *desktopMediaServiceClient) Heartbeat(ctx context.Context, in *DesktopMediaHeartbeat, opts ...grpc.CallOption) (*DesktopMediaHeartbeatAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesktopMediaHeartbeatAck)
	err := c.cc.Invoke(ctx, DesktopMediaService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopMediaServiceClient) CloseDesktopMediaSession(ctx context.Context, in *CloseDesktopMediaSessionRequest, opts ...grpc.CallOption) (*CloseDesktopMediaSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseDesktopMediaSessionResponse)
	err := c.cc.Invoke(ctx, DesktopMediaService_CloseDesktopMediaSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesktopMediaServiceServer is the server API for DesktopMediaService service.
// All implementations must embed UnimplementedDesktopMediaServiceServer
// for forward compatibility.
//
// DesktopMediaService carries high-volume graphical desktop updates outside
// the generic remote-access control stream.
type DesktopMediaServiceServer interface {
	// OpenDesktopMediaSession reserves an authenticated, route-bound desktop
	// media session for a previously approved desktop control session.
	OpenDesktopMediaSession(context.Context, *OpenDesktopMediaSessionRequest) (*OpenDesktopMediaSessionResponse, error)
	// StreamDesktopMedia carries screen/cursor/update chunks from the agent and
	// credit, quality, pause/resume, and close acknowledgements from the gateway.
	StreamDesktopMedia(grpc.BidiStreamingServer[DesktopMediaClientMessage, DesktopMediaServerMessage]) error
	// Heartbeat renews the desktop media lease and reports edge-side progress.
	Heartbeat(context.Context, *DesktopMediaHeartbeat) (*DesktopMediaHeartbeatAck, error)
	// CloseDesktopMediaSession explicitly closes an active or pending media session.
	CloseDesktopMediaSession(context.Context, *CloseDesktopMediaSessionRequest) (*CloseDesktopMediaSessionResponse, error)
	mustEmbedUnimplementedDesktopMediaServiceServer()
}

// UnimplementedDesktopMediaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDesktopMediaServiceServer struct{}

func (UnimplementedDesktopMediaServiceServer) OpenDesktopMediaSession(context.Context, *OpenDesktopMediaSessionRequest) (*OpenDesktopMediaSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenDesktopMediaSession not implemented")
}
func (UnimplementedDesktopMediaServiceServer) StreamDesktopMedia(grpc.BidiStreamingServer[DesktopMediaClientMessage, DesktopMediaServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamDesktopMedia not implemented")
}
func (UnimplementedDesktopMediaServiceServer) Heartbeat(context.Context, *DesktopMediaHeartbeat) (*DesktopMediaHeartbeatAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDesktopMediaServiceServer) CloseDesktopMediaSession(context.Context, *CloseDesktopMediaSessionRequest) (*CloseDesktopMediaSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseDesktopMediaSession not implemented")
}
func (UnimplementedDesktopMediaServiceServer) mustEmbedUnimplementedDesktopMediaServiceServer() {}
func (UnimplementedDesktopMediaServiceServer) testEmbeddedByValue()                             {}

// UnsafeDesktopMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DesktopMediaServiceServer will
// result in compilation errors.
type UnsafeDesktopMediaServiceServer interface {
	mustEmbedUnimplementedDesktopMediaServiceServer()
}

func RegisterDesktopMediaServiceServer(s grpc.ServiceRegistrar, srv DesktopMediaServiceServer) {
	// If the following call pancis, it indicates UnimplementedDesktopMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DesktopMediaService_ServiceDesc, srv)
}

func _DesktopMediaService_OpenDesktopMediaSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenDesktopMediaSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopMediaServiceServer).OpenDesktopMediaSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopMediaService_OpenDesktopMediaSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopMediaServiceServer).OpenDesktopMediaSession(ctx, req.(*OpenDesktopMediaSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopMediaService_StreamDesktopMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DesktopMediaServiceServer).StreamDesktopMedia(&grpc.GenericServerStream[DesktopMediaClientMessage, DesktopMediaServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopMediaService_StreamDesktopMediaServer = grpc.BidiStreamingServer[DesktopMediaClientMessage, DesktopMediaServerMessage]

func _DesktopMediaService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopMediaHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopMediaServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopMediaService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopMediaServiceServer).Heartbeat(ctx, req.(*DesktopMediaHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopMediaService_CloseDesktopMediaSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseDesktopMediaSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopMediaServiceServer).CloseDesktopMediaSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopMediaService_CloseDesktopMediaSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopMediaServiceServer).CloseDesktopMediaSession(ctx, req.(*CloseDesktopMediaSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DesktopMediaService_ServiceDesc is the grpc.ServiceDesc for DesktopMediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DesktopMediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "desktopmedia.DesktopMediaService",
	HandlerType: (*DesktopMediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenDesktopMediaSession",
			Handler:    _DesktopMediaService_OpenDesktopMediaSession_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _DesktopMediaService_Heartbeat_Handler,
		},
		{
			MethodName: "CloseDesktopMediaSession",
			Handler:    _DesktopMediaService_CloseDesktopMediaSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDesktopMedia",
			Handler:       _DesktopMediaService_StreamDesktopMedia_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "desktop_media.proto",
}
