//
// Copyright 2025 Carver Automation Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.14.0
// source: nats_account.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserCredentialType specifies what the credentials will be used for.
type UserCredentialType int32

const (
	UserCredentialType_USER_CREDENTIAL_TYPE_UNSPECIFIED UserCredentialType = 0
	UserCredentialType_USER_CREDENTIAL_TYPE_COLLECTOR   UserCredentialType = 1 // For edge collectors (flowgger, trapd, etc.)
	UserCredentialType_USER_CREDENTIAL_TYPE_SERVICE     UserCredentialType = 2 // For internal services
	UserCredentialType_USER_CREDENTIAL_TYPE_ADMIN       UserCredentialType = 3 // For tenant admin access (limited)
)

// Enum value maps for UserCredentialType.
var (
	UserCredentialType_name = map[int32]string{
		0: "USER_CREDENTIAL_TYPE_UNSPECIFIED",
		1: "USER_CREDENTIAL_TYPE_COLLECTOR",
		2: "USER_CREDENTIAL_TYPE_SERVICE",
		3: "USER_CREDENTIAL_TYPE_ADMIN",
	}
	UserCredentialType_value = map[string]int32{
		"USER_CREDENTIAL_TYPE_UNSPECIFIED": 0,
		"USER_CREDENTIAL_TYPE_COLLECTOR":   1,
		"USER_CREDENTIAL_TYPE_SERVICE":     2,
		"USER_CREDENTIAL_TYPE_ADMIN":       3,
	}
)

func (x UserCredentialType) Enum() *UserCredentialType {
	p := new(UserCredentialType)
	*p = x
	return p
}

func (x UserCredentialType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserCredentialType) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_account_proto_enumTypes[0].Descriptor()
}

func (UserCredentialType) Type() protoreflect.EnumType {
	return &file_nats_account_proto_enumTypes[0]
}

func (x UserCredentialType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserCredentialType.Descriptor instead.
func (UserCredentialType) EnumDescriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{0}
}

// AccountLimits defines resource constraints for a NATS account.
type AccountLimits struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxConnections       int64                  `protobuf:"varint,1,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`                     // Maximum concurrent connections (0 = unlimited)
	MaxSubscriptions     int64                  `protobuf:"varint,2,opt,name=max_subscriptions,json=maxSubscriptions,proto3" json:"max_subscriptions,omitempty"`               // Maximum subscriptions per connection (0 = unlimited)
	MaxPayloadBytes      int64                  `protobuf:"varint,3,opt,name=max_payload_bytes,json=maxPayloadBytes,proto3" json:"max_payload_bytes,omitempty"`                // Maximum message payload size in bytes (0 = default 1MB)
	MaxDataBytes         int64                  `protobuf:"varint,4,opt,name=max_data_bytes,json=maxDataBytes,proto3" json:"max_data_bytes,omitempty"`                         // Maximum data throughput in bytes/sec (0 = unlimited)
	MaxExports           int64                  `protobuf:"varint,5,opt,name=max_exports,json=maxExports,proto3" json:"max_exports,omitempty"`                                 // Maximum number of exports (0 = unlimited)
	MaxImports           int64                  `protobuf:"varint,6,opt,name=max_imports,json=maxImports,proto3" json:"max_imports,omitempty"`                                 // Maximum number of imports (0 = unlimited)
	AllowWildcardExports bool                   `protobuf:"varint,7,opt,name=allow_wildcard_exports,json=allowWildcardExports,proto3" json:"allow_wildcard_exports,omitempty"` // Whether wildcard exports are allowed
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AccountLimits) Reset() {
	*x = AccountLimits{}
	mi := &file_nats_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLimits) ProtoMessage() {}

func (x *AccountLimits) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLimits.ProtoReflect.Descriptor instead.
func (*AccountLimits) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountLimits) GetMaxConnections() int64 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *AccountLimits) GetMaxSubscriptions() int64 {
	if x != nil {
		return x.MaxSubscriptions
	}
	return 0
}

func (x *AccountLimits) GetMaxPayloadBytes() int64 {
	if x != nil {
		return x.MaxPayloadBytes
	}
	return 0
}

func (x *AccountLimits) GetMaxDataBytes() int64 {
	if x != nil {
		return x.MaxDataBytes
	}
	return 0
}

func (x *AccountLimits) GetMaxExports() int64 {
	if x != nil {
		return x.MaxExports
	}
	return 0
}

func (x *AccountLimits) GetMaxImports() int64 {
	if x != nil {
		return x.MaxImports
	}
	return 0
}

func (x *AccountLimits) GetAllowWildcardExports() bool {
	if x != nil {
		return x.AllowWildcardExports
	}
	return false
}

// SubjectMapping defines how subjects are transformed for tenant isolation.
type SubjectMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // Source subject pattern (e.g., "logs.snmp")
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`     // Destination subject pattern (e.g., "{{tenant}}.logs.snmp")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectMapping) Reset() {
	*x = SubjectMapping{}
	mi := &file_nats_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectMapping) ProtoMessage() {}

func (x *SubjectMapping) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectMapping.ProtoReflect.Descriptor instead.
func (*SubjectMapping) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{1}
}

func (x *SubjectMapping) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SubjectMapping) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// StreamExport defines a stream export subject for cross-account consumption.
type StreamExport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"` // Subject to export (e.g., "acme.logs.>")
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // Optional export name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExport) Reset() {
	*x = StreamExport{}
	mi := &file_nats_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExport) ProtoMessage() {}

func (x *StreamExport) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExport.ProtoReflect.Descriptor instead.
func (*StreamExport) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{2}
}

func (x *StreamExport) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *StreamExport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// StreamImport defines a stream import from another account.
type StreamImport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Subject          string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`                                             // Subject to import (e.g., "acme.logs.>")
	AccountPublicKey string                 `protobuf:"bytes,2,opt,name=account_public_key,json=accountPublicKey,proto3" json:"account_public_key,omitempty"` // Exporting account public key
	LocalSubject     string                 `protobuf:"bytes,3,opt,name=local_subject,json=localSubject,proto3" json:"local_subject,omitempty"`               // Optional local subject (defaults to subject)
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                                   // Optional import name
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamImport) Reset() {
	*x = StreamImport{}
	mi := &file_nats_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamImport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamImport) ProtoMessage() {}

func (x *StreamImport) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamImport.ProtoReflect.Descriptor instead.
func (*StreamImport) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{3}
}

func (x *StreamImport) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *StreamImport) GetAccountPublicKey() string {
	if x != nil {
		return x.AccountPublicKey
	}
	return ""
}

func (x *StreamImport) GetLocalSubject() string {
	if x != nil {
		return x.LocalSubject
	}
	return ""
}

func (x *StreamImport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreateTenantAccountRequest is the request to create a new tenant NATS account.
type CreateTenantAccountRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug      string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`                // Unique tenant identifier (e.g., "acme-corp")
	Limits          *AccountLimits         `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`                                          // Optional resource limits
	SubjectMappings []*SubjectMapping      `protobuf:"bytes,3,rep,name=subject_mappings,json=subjectMappings,proto3" json:"subject_mappings,omitempty"` // Optional custom subject mappings
	Exports         []*StreamExport        `protobuf:"bytes,4,rep,name=exports,proto3" json:"exports,omitempty"`                                        // Optional stream exports (defaults applied server-side)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTenantAccountRequest) Reset() {
	*x = CreateTenantAccountRequest{}
	mi := &file_nats_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantAccountRequest) ProtoMessage() {}

func (x *CreateTenantAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantAccountRequest) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTenantAccountRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *CreateTenantAccountRequest) GetLimits() *AccountLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *CreateTenantAccountRequest) GetSubjectMappings() []*SubjectMapping {
	if x != nil {
		return x.SubjectMappings
	}
	return nil
}

func (x *CreateTenantAccountRequest) GetExports() []*StreamExport {
	if x != nil {
		return x.Exports
	}
	return nil
}

// CreateTenantAccountResponse returns the generated account credentials.
// The account_seed should be stored encrypted by the caller (Elixir/AshCloak).
type CreateTenantAccountResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountPublicKey string                 `protobuf:"bytes,1,opt,name=account_public_key,json=accountPublicKey,proto3" json:"account_public_key,omitempty"` // The account's public NKey (starts with 'A')
	AccountSeed      string                 `protobuf:"bytes,2,opt,name=account_seed,json=accountSeed,proto3" json:"account_seed,omitempty"`                  // The account's private seed (starts with 'SA') - STORE ENCRYPTED
	AccountJwt       string                 `protobuf:"bytes,3,opt,name=account_jwt,json=accountJwt,proto3" json:"account_jwt,omitempty"`                     // The signed account JWT
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTenantAccountResponse) Reset() {
	*x = CreateTenantAccountResponse{}
	mi := &file_nats_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantAccountResponse) ProtoMessage() {}

func (x *CreateTenantAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantAccountResponse) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTenantAccountResponse) GetAccountPublicKey() string {
	if x != nil {
		return x.AccountPublicKey
	}
	return ""
}

func (x *CreateTenantAccountResponse) GetAccountSeed() string {
	if x != nil {
		return x.AccountSeed
	}
	return ""
}

func (x *CreateTenantAccountResponse) GetAccountJwt() string {
	if x != nil {
		return x.AccountJwt
	}
	return ""
}

// UserPermissions defines publish/subscribe permissions for a user.
type UserPermissions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PublishAllow   []string               `protobuf:"bytes,1,rep,name=publish_allow,json=publishAllow,proto3" json:"publish_allow,omitempty"`        // Subjects the user can publish to
	PublishDeny    []string               `protobuf:"bytes,2,rep,name=publish_deny,json=publishDeny,proto3" json:"publish_deny,omitempty"`           // Subjects the user cannot publish to
	SubscribeAllow []string               `protobuf:"bytes,3,rep,name=subscribe_allow,json=subscribeAllow,proto3" json:"subscribe_allow,omitempty"`  // Subjects the user can subscribe to
	SubscribeDeny  []string               `protobuf:"bytes,4,rep,name=subscribe_deny,json=subscribeDeny,proto3" json:"subscribe_deny,omitempty"`     // Subjects the user cannot subscribe to
	AllowResponses bool                   `protobuf:"varint,5,opt,name=allow_responses,json=allowResponses,proto3" json:"allow_responses,omitempty"` // Whether the user can send responses
	MaxResponses   int32                  `protobuf:"varint,6,opt,name=max_responses,json=maxResponses,proto3" json:"max_responses,omitempty"`       // Maximum number of responses (0 = unlimited)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserPermissions) Reset() {
	*x = UserPermissions{}
	mi := &file_nats_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPermissions) ProtoMessage() {}

func (x *UserPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPermissions.ProtoReflect.Descriptor instead.
func (*UserPermissions) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{6}
}

func (x *UserPermissions) GetPublishAllow() []string {
	if x != nil {
		return x.PublishAllow
	}
	return nil
}

func (x *UserPermissions) GetPublishDeny() []string {
	if x != nil {
		return x.PublishDeny
	}
	return nil
}

func (x *UserPermissions) GetSubscribeAllow() []string {
	if x != nil {
		return x.SubscribeAllow
	}
	return nil
}

func (x *UserPermissions) GetSubscribeDeny() []string {
	if x != nil {
		return x.SubscribeDeny
	}
	return nil
}

func (x *UserPermissions) GetAllowResponses() bool {
	if x != nil {
		return x.AllowResponses
	}
	return false
}

func (x *UserPermissions) GetMaxResponses() int32 {
	if x != nil {
		return x.MaxResponses
	}
	return 0
}

// GenerateUserCredentialsRequest is the request to create user credentials.
type GenerateUserCredentialsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug        string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`                                            // Tenant the user belongs to
	AccountSeed       string                 `protobuf:"bytes,2,opt,name=account_seed,json=accountSeed,proto3" json:"account_seed,omitempty"`                                         // Account's private seed for signing (from Elixir storage)
	UserName          string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                                                  // Human-readable user identifier
	CredentialType    UserCredentialType     `protobuf:"varint,4,opt,name=credential_type,json=credentialType,proto3,enum=proto.UserCredentialType" json:"credential_type,omitempty"` // Type of credentials to generate
	Permissions       *UserPermissions       `protobuf:"bytes,5,opt,name=permissions,proto3" json:"permissions,omitempty"`                                                            // Optional custom permissions (defaults based on type)
	ExpirationSeconds int64                  `protobuf:"varint,6,opt,name=expiration_seconds,json=expirationSeconds,proto3" json:"expiration_seconds,omitempty"`                      // Credential expiration in seconds (0 = no expiration)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateUserCredentialsRequest) Reset() {
	*x = GenerateUserCredentialsRequest{}
	mi := &file_nats_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUserCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUserCredentialsRequest) ProtoMessage() {}

func (x *GenerateUserCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUserCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GenerateUserCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateUserCredentialsRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *GenerateUserCredentialsRequest) GetAccountSeed() string {
	if x != nil {
		return x.AccountSeed
	}
	return ""
}

func (x *GenerateUserCredentialsRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GenerateUserCredentialsRequest) GetCredentialType() UserCredentialType {
	if x != nil {
		return x.CredentialType
	}
	return UserCredentialType_USER_CREDENTIAL_TYPE_UNSPECIFIED
}

func (x *GenerateUserCredentialsRequest) GetPermissions() *UserPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GenerateUserCredentialsRequest) GetExpirationSeconds() int64 {
	if x != nil {
		return x.ExpirationSeconds
	}
	return 0
}

// GenerateUserCredentialsResponse contains the generated credentials.
type GenerateUserCredentialsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserPublicKey    string                 `protobuf:"bytes,1,opt,name=user_public_key,json=userPublicKey,proto3" json:"user_public_key,omitempty"`          // The user's public NKey (starts with 'U')
	UserJwt          string                 `protobuf:"bytes,2,opt,name=user_jwt,json=userJwt,proto3" json:"user_jwt,omitempty"`                              // The signed user JWT
	CredsFileContent string                 `protobuf:"bytes,3,opt,name=creds_file_content,json=credsFileContent,proto3" json:"creds_file_content,omitempty"` // Complete .creds file content (JWT + seed)
	ExpiresAtUnix    int64                  `protobuf:"varint,4,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`         // Unix timestamp when credentials expire (0 = never)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateUserCredentialsResponse) Reset() {
	*x = GenerateUserCredentialsResponse{}
	mi := &file_nats_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUserCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUserCredentialsResponse) ProtoMessage() {}

func (x *GenerateUserCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUserCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GenerateUserCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateUserCredentialsResponse) GetUserPublicKey() string {
	if x != nil {
		return x.UserPublicKey
	}
	return ""
}

func (x *GenerateUserCredentialsResponse) GetUserJwt() string {
	if x != nil {
		return x.UserJwt
	}
	return ""
}

func (x *GenerateUserCredentialsResponse) GetCredsFileContent() string {
	if x != nil {
		return x.CredsFileContent
	}
	return ""
}

func (x *GenerateUserCredentialsResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

// SignAccountJWTRequest is used to regenerate an account JWT with updated claims.
type SignAccountJWTRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug      string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`                  // Tenant identifier (used as account name)
	AccountSeed     string                 `protobuf:"bytes,2,opt,name=account_seed,json=accountSeed,proto3" json:"account_seed,omitempty"`               // Account's private seed (from Elixir storage)
	Limits          *AccountLimits         `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`                                            // Current resource limits
	SubjectMappings []*SubjectMapping      `protobuf:"bytes,4,rep,name=subject_mappings,json=subjectMappings,proto3" json:"subject_mappings,omitempty"`   // Current subject mappings
	RevokedUserKeys []string               `protobuf:"bytes,5,rep,name=revoked_user_keys,json=revokedUserKeys,proto3" json:"revoked_user_keys,omitempty"` // Public keys of revoked users
	Exports         []*StreamExport        `protobuf:"bytes,6,rep,name=exports,proto3" json:"exports,omitempty"`                                          // Optional stream exports (defaults applied server-side)
	Imports         []*StreamImport        `protobuf:"bytes,7,rep,name=imports,proto3" json:"imports,omitempty"`                                          // Stream imports from tenant accounts
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignAccountJWTRequest) Reset() {
	*x = SignAccountJWTRequest{}
	mi := &file_nats_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignAccountJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignAccountJWTRequest) ProtoMessage() {}

func (x *SignAccountJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignAccountJWTRequest.ProtoReflect.Descriptor instead.
func (*SignAccountJWTRequest) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{9}
}

func (x *SignAccountJWTRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *SignAccountJWTRequest) GetAccountSeed() string {
	if x != nil {
		return x.AccountSeed
	}
	return ""
}

func (x *SignAccountJWTRequest) GetLimits() *AccountLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *SignAccountJWTRequest) GetSubjectMappings() []*SubjectMapping {
	if x != nil {
		return x.SubjectMappings
	}
	return nil
}

func (x *SignAccountJWTRequest) GetRevokedUserKeys() []string {
	if x != nil {
		return x.RevokedUserKeys
	}
	return nil
}

func (x *SignAccountJWTRequest) GetExports() []*StreamExport {
	if x != nil {
		return x.Exports
	}
	return nil
}

func (x *SignAccountJWTRequest) GetImports() []*StreamImport {
	if x != nil {
		return x.Imports
	}
	return nil
}

// SignAccountJWTResponse returns the newly signed account JWT.
type SignAccountJWTResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountPublicKey string                 `protobuf:"bytes,1,opt,name=account_public_key,json=accountPublicKey,proto3" json:"account_public_key,omitempty"` // The account's public NKey
	AccountJwt       string                 `protobuf:"bytes,2,opt,name=account_jwt,json=accountJwt,proto3" json:"account_jwt,omitempty"`                     // The newly signed account JWT
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignAccountJWTResponse) Reset() {
	*x = SignAccountJWTResponse{}
	mi := &file_nats_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignAccountJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignAccountJWTResponse) ProtoMessage() {}

func (x *SignAccountJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignAccountJWTResponse.ProtoReflect.Descriptor instead.
func (*SignAccountJWTResponse) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{10}
}

func (x *SignAccountJWTResponse) GetAccountPublicKey() string {
	if x != nil {
		return x.AccountPublicKey
	}
	return ""
}

func (x *SignAccountJWTResponse) GetAccountJwt() string {
	if x != nil {
		return x.AccountJwt
	}
	return ""
}

// BootstrapOperatorRequest is used to initialize the NATS operator.
type BootstrapOperatorRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OperatorName          string                 `protobuf:"bytes,1,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`                               // Name for the operator (e.g., "serviceradar")
	ExistingOperatorSeed  string                 `protobuf:"bytes,2,opt,name=existing_operator_seed,json=existingOperatorSeed,proto3" json:"existing_operator_seed,omitempty"`     // Optional: import existing seed instead of generating
	GenerateSystemAccount bool                   `protobuf:"varint,3,opt,name=generate_system_account,json=generateSystemAccount,proto3" json:"generate_system_account,omitempty"` // Whether to generate the system account
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BootstrapOperatorRequest) Reset() {
	*x = BootstrapOperatorRequest{}
	mi := &file_nats_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapOperatorRequest) ProtoMessage() {}

func (x *BootstrapOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapOperatorRequest.ProtoReflect.Descriptor instead.
func (*BootstrapOperatorRequest) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{11}
}

func (x *BootstrapOperatorRequest) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *BootstrapOperatorRequest) GetExistingOperatorSeed() string {
	if x != nil {
		return x.ExistingOperatorSeed
	}
	return ""
}

func (x *BootstrapOperatorRequest) GetGenerateSystemAccount() bool {
	if x != nil {
		return x.GenerateSystemAccount
	}
	return false
}

// BootstrapOperatorResponse returns the operator credentials.
// Seeds are only returned if newly generated (not when importing existing).
type BootstrapOperatorResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	OperatorPublicKey      string                 `protobuf:"bytes,1,opt,name=operator_public_key,json=operatorPublicKey,proto3" json:"operator_public_key,omitempty"`                  // The operator's public NKey (starts with 'O')
	OperatorSeed           string                 `protobuf:"bytes,2,opt,name=operator_seed,json=operatorSeed,proto3" json:"operator_seed,omitempty"`                                   // The operator's private seed - only if newly generated
	OperatorJwt            string                 `protobuf:"bytes,3,opt,name=operator_jwt,json=operatorJwt,proto3" json:"operator_jwt,omitempty"`                                      // The signed operator JWT
	SystemAccountPublicKey string                 `protobuf:"bytes,4,opt,name=system_account_public_key,json=systemAccountPublicKey,proto3" json:"system_account_public_key,omitempty"` // System account public key (if generated)
	SystemAccountSeed      string                 `protobuf:"bytes,5,opt,name=system_account_seed,json=systemAccountSeed,proto3" json:"system_account_seed,omitempty"`                  // System account seed - only if newly generated
	SystemAccountJwt       string                 `protobuf:"bytes,6,opt,name=system_account_jwt,json=systemAccountJwt,proto3" json:"system_account_jwt,omitempty"`                     // Signed system account JWT (if generated)
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BootstrapOperatorResponse) Reset() {
	*x = BootstrapOperatorResponse{}
	mi := &file_nats_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapOperatorResponse) ProtoMessage() {}

func (x *BootstrapOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapOperatorResponse.ProtoReflect.Descriptor instead.
func (*BootstrapOperatorResponse) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{12}
}

func (x *BootstrapOperatorResponse) GetOperatorPublicKey() string {
	if x != nil {
		return x.OperatorPublicKey
	}
	return ""
}

func (x *BootstrapOperatorResponse) GetOperatorSeed() string {
	if x != nil {
		return x.OperatorSeed
	}
	return ""
}

func (x *BootstrapOperatorResponse) GetOperatorJwt() string {
	if x != nil {
		return x.OperatorJwt
	}
	return ""
}

func (x *BootstrapOperatorResponse) GetSystemAccountPublicKey() string {
	if x != nil {
		return x.SystemAccountPublicKey
	}
	return ""
}

func (x *BootstrapOperatorResponse) GetSystemAccountSeed() string {
	if x != nil {
		return x.SystemAccountSeed
	}
	return ""
}

func (x *BootstrapOperatorResponse) GetSystemAccountJwt() string {
	if x != nil {
		return x.SystemAccountJwt
	}
	return ""
}

// GetOperatorInfoRequest retrieves current operator status.
type GetOperatorInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperatorInfoRequest) Reset() {
	*x = GetOperatorInfoRequest{}
	mi := &file_nats_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperatorInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperatorInfoRequest) ProtoMessage() {}

func (x *GetOperatorInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperatorInfoRequest.ProtoReflect.Descriptor instead.
func (*GetOperatorInfoRequest) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{13}
}

// GetOperatorInfoResponse returns the operator's current state.
type GetOperatorInfoResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	OperatorPublicKey      string                 `protobuf:"bytes,1,opt,name=operator_public_key,json=operatorPublicKey,proto3" json:"operator_public_key,omitempty"`                  // The operator's public NKey
	OperatorName           string                 `protobuf:"bytes,2,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`                                   // The operator's name
	IsInitialized          bool                   `protobuf:"varint,3,opt,name=is_initialized,json=isInitialized,proto3" json:"is_initialized,omitempty"`                               // Whether the operator is ready for use
	SystemAccountPublicKey string                 `protobuf:"bytes,4,opt,name=system_account_public_key,json=systemAccountPublicKey,proto3" json:"system_account_public_key,omitempty"` // System account public key (if exists)
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetOperatorInfoResponse) Reset() {
	*x = GetOperatorInfoResponse{}
	mi := &file_nats_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperatorInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperatorInfoResponse) ProtoMessage() {}

func (x *GetOperatorInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperatorInfoResponse.ProtoReflect.Descriptor instead.
func (*GetOperatorInfoResponse) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{14}
}

func (x *GetOperatorInfoResponse) GetOperatorPublicKey() string {
	if x != nil {
		return x.OperatorPublicKey
	}
	return ""
}

func (x *GetOperatorInfoResponse) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *GetOperatorInfoResponse) GetIsInitialized() bool {
	if x != nil {
		return x.IsInitialized
	}
	return false
}

func (x *GetOperatorInfoResponse) GetSystemAccountPublicKey() string {
	if x != nil {
		return x.SystemAccountPublicKey
	}
	return ""
}

// PushAccountJWTRequest is the request to push an account JWT to the NATS resolver.
type PushAccountJWTRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountPublicKey string                 `protobuf:"bytes,1,opt,name=account_public_key,json=accountPublicKey,proto3" json:"account_public_key,omitempty"` // The account's public NKey (starts with 'A')
	AccountJwt       string                 `protobuf:"bytes,2,opt,name=account_jwt,json=accountJwt,proto3" json:"account_jwt,omitempty"`                     // The signed account JWT to push
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PushAccountJWTRequest) Reset() {
	*x = PushAccountJWTRequest{}
	mi := &file_nats_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAccountJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAccountJWTRequest) ProtoMessage() {}

func (x *PushAccountJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAccountJWTRequest.ProtoReflect.Descriptor instead.
func (*PushAccountJWTRequest) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{15}
}

func (x *PushAccountJWTRequest) GetAccountPublicKey() string {
	if x != nil {
		return x.AccountPublicKey
	}
	return ""
}

func (x *PushAccountJWTRequest) GetAccountJwt() string {
	if x != nil {
		return x.AccountJwt
	}
	return ""
}

// PushAccountJWTResponse confirms the JWT was pushed to the resolver.
type PushAccountJWTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether the push was successful
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Status message or error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAccountJWTResponse) Reset() {
	*x = PushAccountJWTResponse{}
	mi := &file_nats_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAccountJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAccountJWTResponse) ProtoMessage() {}

func (x *PushAccountJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nats_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAccountJWTResponse.ProtoReflect.Descriptor instead.
func (*PushAccountJWTResponse) Descriptor() ([]byte, []int) {
	return file_nats_account_proto_rawDescGZIP(), []int{16}
}

func (x *PushAccountJWTResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushAccountJWTResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_nats_account_proto protoreflect.FileDescriptor

const file_nats_account_proto_rawDesc = "" +
	"\n" +
	"\x12nats_account.proto\x12\x05proto\"\xaf\x02\n" +
	"\rAccountLimits\x12'\n" +
	"\x0fmax_connections\x18\x01 \x01(\x03R\x0emaxConnections\x12+\n" +
	"\x11max_subscriptions\x18\x02 \x01(\x03R\x10maxSubscriptions\x12*\n" +
	"\x11max_payload_bytes\x18\x03 \x01(\x03R\x0fmaxPayloadBytes\x12$\n" +
	"\x0emax_data_bytes\x18\x04 \x01(\x03R\fmaxDataBytes\x12\x1f\n" +
	"\vmax_exports\x18\x05 \x01(\x03R\n" +
	"maxExports\x12\x1f\n" +
	"\vmax_imports\x18\x06 \x01(\x03R\n" +
	"maxImports\x124\n" +
	"\x16allow_wildcard_exports\x18\a \x01(\bR\x14allowWildcardExports\"4\n" +
	"\x0eSubjectMapping\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"<\n" +
	"\fStreamExport\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x01\n" +
	"\fStreamImport\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12,\n" +
	"\x12account_public_key\x18\x02 \x01(\tR\x10accountPublicKey\x12#\n" +
	"\rlocal_subject\x18\x03 \x01(\tR\flocalSubject\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xdc\x01\n" +
	"\x1aCreateTenantAccountRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12,\n" +
	"\x06limits\x18\x02 \x01(\v2\x14.proto.AccountLimitsR\x06limits\x12@\n" +
	"\x10subject_mappings\x18\x03 \x03(\v2\x15.proto.SubjectMappingR\x0fsubjectMappings\x12-\n" +
	"\aexports\x18\x04 \x03(\v2\x13.proto.StreamExportR\aexports\"\x8f\x01\n" +
	"\x1bCreateTenantAccountResponse\x12,\n" +
	"\x12account_public_key\x18\x01 \x01(\tR\x10accountPublicKey\x12!\n" +
	"\faccount_seed\x18\x02 \x01(\tR\vaccountSeed\x12\x1f\n" +
	"\vaccount_jwt\x18\x03 \x01(\tR\n" +
	"accountJwt\"\xf7\x01\n" +
	"\x0fUserPermissions\x12#\n" +
	"\rpublish_allow\x18\x01 \x03(\tR\fpublishAllow\x12!\n" +
	"\fpublish_deny\x18\x02 \x03(\tR\vpublishDeny\x12'\n" +
	"\x0fsubscribe_allow\x18\x03 \x03(\tR\x0esubscribeAllow\x12%\n" +
	"\x0esubscribe_deny\x18\x04 \x03(\tR\rsubscribeDeny\x12'\n" +
	"\x0fallow_responses\x18\x05 \x01(\bR\x0eallowResponses\x12#\n" +
	"\rmax_responses\x18\x06 \x01(\x05R\fmaxResponses\"\xae\x02\n" +
	"\x1eGenerateUserCredentialsRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12!\n" +
	"\faccount_seed\x18\x02 \x01(\tR\vaccountSeed\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12B\n" +
	"\x0fcredential_type\x18\x04 \x01(\x0e2\x19.proto.UserCredentialTypeR\x0ecredentialType\x128\n" +
	"\vpermissions\x18\x05 \x01(\v2\x16.proto.UserPermissionsR\vpermissions\x12-\n" +
	"\x12expiration_seconds\x18\x06 \x01(\x03R\x11expirationSeconds\"\xba\x01\n" +
	"\x1fGenerateUserCredentialsResponse\x12&\n" +
	"\x0fuser_public_key\x18\x01 \x01(\tR\ruserPublicKey\x12\x19\n" +
	"\buser_jwt\x18\x02 \x01(\tR\auserJwt\x12,\n" +
	"\x12creds_file_content\x18\x03 \x01(\tR\x10credsFileContent\x12&\n" +
	"\x0fexpires_at_unix\x18\x04 \x01(\x03R\rexpiresAtUnix\"\xd5\x02\n" +
	"\x15SignAccountJWTRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12!\n" +
	"\faccount_seed\x18\x02 \x01(\tR\vaccountSeed\x12,\n" +
	"\x06limits\x18\x03 \x01(\v2\x14.proto.AccountLimitsR\x06limits\x12@\n" +
	"\x10subject_mappings\x18\x04 \x03(\v2\x15.proto.SubjectMappingR\x0fsubjectMappings\x12*\n" +
	"\x11revoked_user_keys\x18\x05 \x03(\tR\x0frevokedUserKeys\x12-\n" +
	"\aexports\x18\x06 \x03(\v2\x13.proto.StreamExportR\aexports\x12-\n" +
	"\aimports\x18\a \x03(\v2\x13.proto.StreamImportR\aimports\"g\n" +
	"\x16SignAccountJWTResponse\x12,\n" +
	"\x12account_public_key\x18\x01 \x01(\tR\x10accountPublicKey\x12\x1f\n" +
	"\vaccount_jwt\x18\x02 \x01(\tR\n" +
	"accountJwt\"\xad\x01\n" +
	"\x18BootstrapOperatorRequest\x12#\n" +
	"\roperator_name\x18\x01 \x01(\tR\foperatorName\x124\n" +
	"\x16existing_operator_seed\x18\x02 \x01(\tR\x14existingOperatorSeed\x126\n" +
	"\x17generate_system_account\x18\x03 \x01(\bR\x15generateSystemAccount\"\xac\x02\n" +
	"\x19BootstrapOperatorResponse\x12.\n" +
	"\x13operator_public_key\x18\x01 \x01(\tR\x11operatorPublicKey\x12#\n" +
	"\roperator_seed\x18\x02 \x01(\tR\foperatorSeed\x12!\n" +
	"\foperator_jwt\x18\x03 \x01(\tR\voperatorJwt\x129\n" +
	"\x19system_account_public_key\x18\x04 \x01(\tR\x16systemAccountPublicKey\x12.\n" +
	"\x13system_account_seed\x18\x05 \x01(\tR\x11systemAccountSeed\x12,\n" +
	"\x12system_account_jwt\x18\x06 \x01(\tR\x10systemAccountJwt\"\x18\n" +
	"\x16GetOperatorInfoRequest\"\xd0\x01\n" +
	"\x17GetOperatorInfoResponse\x12.\n" +
	"\x13operator_public_key\x18\x01 \x01(\tR\x11operatorPublicKey\x12#\n" +
	"\roperator_name\x18\x02 \x01(\tR\foperatorName\x12%\n" +
	"\x0eis_initialized\x18\x03 \x01(\bR\risInitialized\x129\n" +
	"\x19system_account_public_key\x18\x04 \x01(\tR\x16systemAccountPublicKey\"f\n" +
	"\x15PushAccountJWTRequest\x12,\n" +
	"\x12account_public_key\x18\x01 \x01(\tR\x10accountPublicKey\x12\x1f\n" +
	"\vaccount_jwt\x18\x02 \x01(\tR\n" +
	"accountJwt\"L\n" +
	"\x16PushAccountJWTResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xa0\x01\n" +
	"\x12UserCredentialType\x12$\n" +
	" USER_CREDENTIAL_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eUSER_CREDENTIAL_TYPE_COLLECTOR\x10\x01\x12 \n" +
	"\x1cUSER_CREDENTIAL_TYPE_SERVICE\x10\x02\x12\x1e\n" +
	"\x1aUSER_CREDENTIAL_TYPE_ADMIN\x10\x032\xb0\x04\n" +
	"\x12NATSAccountService\x12X\n" +
	"\x11BootstrapOperator\x12\x1f.proto.BootstrapOperatorRequest\x1a .proto.BootstrapOperatorResponse\"\x00\x12R\n" +
	"\x0fGetOperatorInfo\x12\x1d.proto.GetOperatorInfoRequest\x1a\x1e.proto.GetOperatorInfoResponse\"\x00\x12^\n" +
	"\x13CreateTenantAccount\x12!.proto.CreateTenantAccountRequest\x1a\".proto.CreateTenantAccountResponse\"\x00\x12j\n" +
	"\x17GenerateUserCredentials\x12%.proto.GenerateUserCredentialsRequest\x1a&.proto.GenerateUserCredentialsResponse\"\x00\x12O\n" +
	"\x0eSignAccountJWT\x12\x1c.proto.SignAccountJWTRequest\x1a\x1d.proto.SignAccountJWTResponse\"\x00\x12O\n" +
	"\x0ePushAccountJWT\x12\x1c.proto.PushAccountJWTRequest\x1a\x1d.proto.PushAccountJWTResponse\"\x00B*Z(github.com/carverauto/serviceradar/protob\x06proto3"

var (
	file_nats_account_proto_rawDescOnce sync.Once
	file_nats_account_proto_rawDescData []byte
)

func file_nats_account_proto_rawDescGZIP() []byte {
	file_nats_account_proto_rawDescOnce.Do(func() {
		file_nats_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nats_account_proto_rawDesc), len(file_nats_account_proto_rawDesc)))
	})
	return file_nats_account_proto_rawDescData
}

var file_nats_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nats_account_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_nats_account_proto_goTypes = []any{
	(UserCredentialType)(0),                 // 0: proto.UserCredentialType
	(*AccountLimits)(nil),                   // 1: proto.AccountLimits
	(*SubjectMapping)(nil),                  // 2: proto.SubjectMapping
	(*StreamExport)(nil),                    // 3: proto.StreamExport
	(*StreamImport)(nil),                    // 4: proto.StreamImport
	(*CreateTenantAccountRequest)(nil),      // 5: proto.CreateTenantAccountRequest
	(*CreateTenantAccountResponse)(nil),     // 6: proto.CreateTenantAccountResponse
	(*UserPermissions)(nil),                 // 7: proto.UserPermissions
	(*GenerateUserCredentialsRequest)(nil),  // 8: proto.GenerateUserCredentialsRequest
	(*GenerateUserCredentialsResponse)(nil), // 9: proto.GenerateUserCredentialsResponse
	(*SignAccountJWTRequest)(nil),           // 10: proto.SignAccountJWTRequest
	(*SignAccountJWTResponse)(nil),          // 11: proto.SignAccountJWTResponse
	(*BootstrapOperatorRequest)(nil),        // 12: proto.BootstrapOperatorRequest
	(*BootstrapOperatorResponse)(nil),       // 13: proto.BootstrapOperatorResponse
	(*GetOperatorInfoRequest)(nil),          // 14: proto.GetOperatorInfoRequest
	(*GetOperatorInfoResponse)(nil),         // 15: proto.GetOperatorInfoResponse
	(*PushAccountJWTRequest)(nil),           // 16: proto.PushAccountJWTRequest
	(*PushAccountJWTResponse)(nil),          // 17: proto.PushAccountJWTResponse
}
var file_nats_account_proto_depIdxs = []int32{
	1,  // 0: proto.CreateTenantAccountRequest.limits:type_name -> proto.AccountLimits
	2,  // 1: proto.CreateTenantAccountRequest.subject_mappings:type_name -> proto.SubjectMapping
	3,  // 2: proto.CreateTenantAccountRequest.exports:type_name -> proto.StreamExport
	0,  // 3: proto.GenerateUserCredentialsRequest.credential_type:type_name -> proto.UserCredentialType
	7,  // 4: proto.GenerateUserCredentialsRequest.permissions:type_name -> proto.UserPermissions
	1,  // 5: proto.SignAccountJWTRequest.limits:type_name -> proto.AccountLimits
	2,  // 6: proto.SignAccountJWTRequest.subject_mappings:type_name -> proto.SubjectMapping
	3,  // 7: proto.SignAccountJWTRequest.exports:type_name -> proto.StreamExport
	4,  // 8: proto.SignAccountJWTRequest.imports:type_name -> proto.StreamImport
	12, // 9: proto.NATSAccountService.BootstrapOperator:input_type -> proto.BootstrapOperatorRequest
	14, // 10: proto.NATSAccountService.GetOperatorInfo:input_type -> proto.GetOperatorInfoRequest
	5,  // 11: proto.NATSAccountService.CreateTenantAccount:input_type -> proto.CreateTenantAccountRequest
	8,  // 12: proto.NATSAccountService.GenerateUserCredentials:input_type -> proto.GenerateUserCredentialsRequest
	10, // 13: proto.NATSAccountService.SignAccountJWT:input_type -> proto.SignAccountJWTRequest
	16, // 14: proto.NATSAccountService.PushAccountJWT:input_type -> proto.PushAccountJWTRequest
	13, // 15: proto.NATSAccountService.BootstrapOperator:output_type -> proto.BootstrapOperatorResponse
	15, // 16: proto.NATSAccountService.GetOperatorInfo:output_type -> proto.GetOperatorInfoResponse
	6,  // 17: proto.NATSAccountService.CreateTenantAccount:output_type -> proto.CreateTenantAccountResponse
	9,  // 18: proto.NATSAccountService.GenerateUserCredentials:output_type -> proto.GenerateUserCredentialsResponse
	11, // 19: proto.NATSAccountService.SignAccountJWT:output_type -> proto.SignAccountJWTResponse
	17, // 20: proto.NATSAccountService.PushAccountJWT:output_type -> proto.PushAccountJWTResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_nats_account_proto_init() }
func file_nats_account_proto_init() {
	if File_nats_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nats_account_proto_rawDesc), len(file_nats_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nats_account_proto_goTypes,
		DependencyIndexes: file_nats_account_proto_depIdxs,
		EnumInfos:         file_nats_account_proto_enumTypes,
		MessageInfos:      file_nats_account_proto_msgTypes,
	}.Build()
	File_nats_account_proto = out.File
	file_nats_account_proto_goTypes = nil
	file_nats_account_proto_depIdxs = nil
}
