[package]
name = "db-event-writer"
version = "0.1.0"
edition = "2021"
authors = ["ServiceRadar Team"]
description = "NATS JetStream consumer that writes CloudEvents to ClickHouse"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
async-nats = "0.42"
clap = { version = "4.3", features = ["derive", "env"] }
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.44", features = ["full"] }
clickhouse = "0.13"
futures = "0.3"
