load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rs//rs:rust_binary.bzl", "rust_binary")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "log-collector",
    srcs = glob(["src/**/*.rs"]),
    crate_features = [
        "syslog",
        "otel",
    ],
    crate_root = "src/main.rs",
    deps = all_crate_deps(
        cargo_only = True,
        normal = True,
    ) + [
        "//rust/config-bootstrap:config_bootstrap",
        "//rust/flowgger:flowgger_lib",
        "//rust/otel:otel_lib",
    ],
)

rust_test(
    name = "log_collector_test",
    crate = ":log-collector",
    crate_features = [
        "syslog",
        "otel",
    ],
)
