helm:
  parameters:
  - name: global.imageTag
    value: v1.4.68
    forcestring: true
  - name: image.name
    value: registry.carverauto.dev/serviceradar/serviceradar-web-ng
    forcestring: true
  - name: core.migrations.expectedVersion
    value: "20260915000000"
    forcestring: true
  - name: image.digests.core
    value: sha256:0b540bbb7c99968154fd6a3990e445b03f49b3cf25a475c491fe350833e13d57
    forcestring: true
  - name: image.digests.webNg
    value: sha256:682582bb662914fdd7d29317df0373876f87881939bc4ab66a1408a4ca9ffe17
    forcestring: true
