helm:
  parameters:
  - name: global.imageTag
    value: v1.4.68
    forcestring: true
  - name: image.name
    value: registry.carverauto.dev/serviceradar/serviceradar-web-ng
    forcestring: true
  - name: core.migrations.expectedVersion
    value: "20260915000000"
    forcestring: true
  - name: image.digests.core
    value: sha256:caa21eedb9b30deceea0c6fe0d9e655c83651bb8ba7ffa430fb95013520e22c1
    forcestring: true
  - name: image.digests.webNg
    value: sha256:5d120bffcbca4ac65a82c264547e484b7f41963d3c30e22ed3a3df0a59ad8e5a
    forcestring: true
