helm:
  parameters:
  - name: global.imageTag
    value: sha-751c788c28773bef8680a337c95f406cdf3f6e5c
    forcestring: true
  - name: image.name
    value: registry.carverauto.dev/serviceradar/serviceradar-web-ng
    forcestring: true
