# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secrets.yaml
  - serviceradar-proton.yaml
  - serviceradar-nats.yaml
  - serviceradar-core.yaml
  - serviceradar-web.yaml
  - serviceradar-nginx.yaml
  - serviceradar-agent.yaml
  - serviceradar-poller.yaml
  - serviceradar-snmp-checker.yaml

commonLabels:
  app.kubernetes.io/part-of: serviceradar