# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceradar-proton.yaml
- serviceradar-nats.yaml
- serviceradar-core.yaml
- serviceradar-web.yaml
- serviceradar-agent.yaml
- serviceradar-poller.yaml
- serviceradar-snmp-checker.yaml
- cert-scripts-configmap.yaml
- cert-generator-job.yaml
# Note: configmap.yaml removed - now created dynamically by deploy.sh with proper bcrypt hash

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: serviceradar
