apiVersion: v1
kind: ConfigMap
metadata:
  name: poller-nested-spire-config
  namespace: demo
data:
  upstream-agent.conf: |
    agent {
      data_dir = "/run/spire/nested/upstream-agent"
      log_level = "INFO"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = "/run/spire/nested/upstream/agent.sock"
      trust_domain = "carverauto.dev"
      insecure_bootstrap = true
      retry_bootstrap = true
    }

    plugins {
      NodeAttestor "join_token" {
        plugin_data {}
      }

      KeyManager "memory" {
        plugin_data {}
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = true
          node_name_env = "MY_NODE_NAME"
        }
      }

      WorkloadAttestor "unix" {
        plugin_data {}
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "18080"
      live_path = "/live"
      ready_path = "/ready"
    }

  downstream-agent.conf: |
    agent {
      data_dir = "/run/spire/nested/downstream-agent"
      log_level = "INFO"
      server_address = "127.0.0.1"
      server_port = "8083"
      socket_path = "/run/spire/nested/workload/agent.sock"
      trust_domain = "carverauto.dev"
      insecure_bootstrap = true
      retry_bootstrap = true
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "carverauto-cluster"
        }
      }

      KeyManager "memory" {
        plugin_data {}
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = true
          node_name_env = "MY_NODE_NAME"
        }
      }

      WorkloadAttestor "unix" {
        plugin_data {}
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "18081"
      live_path = "/live"
      ready_path = "/ready"
    }

  server.conf: |
    server {
      bind_address = "0.0.0.0"
      bind_port = "8083"
      socket_path = "/run/spire/nested/server/api.sock"
      trust_domain = "carverauto.dev"
      data_dir = "/run/spire/nested/server"
      log_level = "INFO"
      ca_key_type = "rsa-2048"

      ca_subject = {
        country = ["US"],
        organization = ["Carver Automation Corporation"],
        common_name = "carverauto.dev",
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "sqlite3"
          connection_string = "/run/spire/nested/server/datastore.sqlite3"
        }
      }

      KeyManager "disk" {
        plugin_data {
          keys_path = "/run/spire/nested/server/keys.json"
        }
      }

      NodeAttestor "k8s_psat" {
        plugin_data {
          clusters = {
            "carverauto-cluster" = {
              service_account_allow_list = ["demo:serviceradar-poller"]
            }
          }
        }
      }

      UpstreamAuthority "spire" {
        plugin_data {
          server_address = "spire-server"
          server_port = "8081"
          workload_api_socket = "/run/spire/nested/upstream/agent.sock"
        }
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "18082"
      live_path = "/live"
      ready_path = "/ready"
    }
