# base/serviceradar-snmp-checker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceradar-snmp-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceradar-snmp-checker
  template:
    metadata:
      labels:
        app: serviceradar-snmp-checker
    spec:
      imagePullSecrets:
        - name: ghcr-io-cred
      containers:
      - name: snmp-checker
        image: ghcr.io/carverauto/serviceradar-snmp-checker:latest
        volumeMounts:
        - name: serviceradar-config
          mountPath: /etc/serviceradar
        env:
        - name: SERVICERADAR_CONFIG_PATH
          value: "/etc/serviceradar/snmp-checker.json"
        - name: SERVICERADAR_CLOUD_ADDR
          value: "serviceradar-cloud:50051"
        - name: SERVICERADAR_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: "300m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
      volumes:
      - name: serviceradar-config
        configMap:
          name: serviceradar-config
