# base/serviceradar-kong.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceradar-kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceradar-kong
  template:
    metadata:
      labels:
        app: serviceradar-kong
    spec:
      initContainers:
      - name: render-kong-config
        image: ghcr.io/carverauto/serviceradar-kong-config:latest
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          set -e
          mkdir -p /opt/kong
          for i in $(seq 1 60); do
            if /usr/local/bin/serviceradar-cli render-kong \
              --jwks http://serviceradar-core:8090/auth/jwks.json \
              --service http://serviceradar-core:8090 \
              --path /api \
              --srql-service http://serviceradar-srql:8080 \
              --srql-path /api/query \
              --out /opt/kong/kong.yml; then
              exit 0
            fi
            echo "render-kong failed, retrying in 5s ($i/60)"
            sleep 5
          done
          echo "render-kong did not succeed after 60 attempts"
          exit 1
        volumeMounts:
        - name: kong-config
          mountPath: /opt/kong
      containers:
      - name: kong
        image: kong:3.7
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: /opt/kong/kong.yml
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        - name: KONG_NGINX_DAEMON
          value: "off"
        - name: KONG_LOG_LEVEL
          value: info
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8443
          name: proxy-ssl
        - containerPort: 8001
          name: admin
        volumeMounts:
        - name: kong-config
          mountPath: /opt/kong
        readinessProbe:
          httpGet:
            path: /
            port: admin
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: admin
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      volumes:
      - name: kong-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: serviceradar-kong
spec:
  selector:
    app: serviceradar-kong
  ports:
  - name: proxy
    port: 8000
    targetPort: proxy
  - name: proxy-ssl
    port: 8443
    targetPort: proxy-ssl
  - name: admin
    port: 8001
    targetPort: admin
