# base/serviceradar-nats.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceradar-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceradar-nats
      app.kubernetes.io/part-of: serviceradar
  template:
    metadata:
      labels:
        app: serviceradar-nats
        app.kubernetes.io/part-of: serviceradar
    spec:
      containers:
      - name: nats
        image: nats:latest
        imagePullPolicy: Always
        command: ["/nats-server", "--config", "/etc/nats/nats-server.conf", "--jetstream"]
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitoring
        - containerPort: 6222
          name: cluster
        volumeMounts:
        - name: nats-data
          mountPath: /data
        - name: serviceradar-config
          mountPath: /etc/nats/nats-server.conf
          subPath: nats.conf
        - name: cert-data
          mountPath: /etc/serviceradar/certs
          readOnly: true
        resources:
          limits:
            cpu: "2"
            memory: "16Gi"
          requests:
            cpu: "1"
            memory: "8Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: nats-data
        persistentVolumeClaim:
          claimName: serviceradar-nats-data
      - name: serviceradar-config
        configMap:
          name: serviceradar-config
      - name: cert-data
        persistentVolumeClaim:
          claimName: serviceradar-cert-data
---
apiVersion: v1
kind: Service
metadata:
  name: serviceradar-nats
spec:
  selector:
    app: serviceradar-nats
  ports:
  - name: client
    port: 4222
    targetPort: client
  - name: monitoring
    port: 8222
    targetPort: monitoring
  - name: cluster
    port: 6222
    targetPort: cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serviceradar-nats-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
