# base/serviceradar-core.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceradar-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceradar-core
  template:
    metadata:
      labels:
        app: serviceradar-core
    spec:
      imagePullSecrets:
        - name: ghcr-io-cred
      initContainers:
      # Wait for Proton to be ready
      - name: wait-for-proton
        image: busybox:1.36
        command: ['sh', '-c']
        args:
          - |
            echo "Waiting for Proton to be ready..."
            until nc -z serviceradar-proton 8123; do
              echo "Proton not ready, waiting..."
              sleep 5
            done
            echo "Proton is ready!"
      # Copy certificates
      - name: copy-certs
        image: busybox:1.36
        command: ['sh', '-c']
        args:
          - |
            echo "Copying certificates..."
            while [ ! -f /proton-certs/root.pem ]; do
              echo "Certificates not found, waiting..."
              sleep 5
            done
            cp -r /proton-certs/* /etc/serviceradar/certs/
        volumeMounts:
        - name: proton-certs
          mountPath: /proton-certs
          readOnly: true
        - name: cert-data
          mountPath: /etc/serviceradar/certs
      containers:
      - name: core
        image: ghcr.io/carverauto/serviceradar-core:latest
        ports:
        - containerPort: 8090
          name: http
        - containerPort: 50052
          name: grpc
        - containerPort: 9090
          name: metrics
        volumeMounts:
        - name: serviceradar-config
          mountPath: /etc/serviceradar/config
        - name: cert-data
          mountPath: /etc/serviceradar/certs
          readOnly: true
        - name: credentials
          mountPath: /etc/serviceradar/credentials
        - name: core-data
          mountPath: /var/lib/serviceradar
        env:
        - name: CONFIG_SOURCE
          value: "file"
        - name: CONFIG_PATH
          value: "/etc/serviceradar/config/core.json"
        - name: WAIT_FOR_PROTON
          value: "true"
        - name: INIT_DB
          value: "true"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: serviceradar-secrets
              key: jwt-secret
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: serviceradar-secrets
              key: api-key
        - name: PROTON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: serviceradar-secrets
              key: proton-password
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: serviceradar-secrets
              key: admin-password
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/status
            port: 8090
            httpHeaders:
            - name: X-API-Key
              value: "$(API_KEY)"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/status
            port: 8090
            httpHeaders:
            - name: X-API-Key
              value: "$(API_KEY)"
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: serviceradar-config
        configMap:
          name: serviceradar-config
      - name: cert-data
        emptyDir: {}
      - name: proton-certs
        persistentVolumeClaim:
          claimName: serviceradar-certs-pvc
      - name: credentials
        emptyDir: {}
      - name: core-data
        persistentVolumeClaim:
          claimName: serviceradar-core-data
---
apiVersion: v1
kind: Service
metadata:
  name: serviceradar-core
spec:
  selector:
    app: serviceradar-core
  ports:
  - name: http
    port: 8090
    targetPort: http
  - name: grpc
    port: 50052
    targetPort: grpc
  - name: metrics
    port: 9090
    targetPort: metrics
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serviceradar-core-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi