defmodule ServiceRadar.Repo.Migrations.UpdateLogsOtelSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:logs) do
      remove :tags
      remove :metadata
      remove :facility
      remove :category
      remove :agent_id
      remove :poller_id
      remove :uid
      remove :source_type
      remove :source
      remove :short_message
      remove :message
      remove :severity_name
      remove :severity
      add :trace_id, :text
      add :span_id, :text
      add :severity_text, :text
      add :severity_number, :bigint
      add :body, :text
      add :service_name, :text
      add :service_version, :text
      add :service_instance, :text
      add :scope_name, :text
      add :scope_version, :text
      add :attributes, :map, default: %{}
      add :resource_attributes, :map, default: %{}
    end

    drop_if_exists unique_index(:logs, [:tenant_id, :timestamp, :source, :message],
                     name: "logs_unique_log_index"
                   )
  end

  def down do
    create unique_index(:logs, [:tenant_id, :timestamp, :source, :message],
             name: "logs_unique_log_index"
           )

    alter table(:logs) do
      remove :resource_attributes
      remove :attributes
      remove :scope_version
      remove :scope_name
      remove :service_instance
      remove :service_version
      remove :service_name
      remove :body
      remove :severity_number
      remove :severity_text
      remove :span_id
      remove :trace_id
      add :severity, :bigint, default: 1
      add :severity_name, :text
      add :message, :text
      add :short_message, :text
      add :source, :text
      add :source_type, :text
      add :uid, :text
      add :poller_id, :text
      add :agent_id, :text
      add :category, :text
      add :facility, :bigint
      add :metadata, :map, default: %{}
      add :tags, {:array, :text}, default: []
    end
  end
end
