defmodule ServiceRadar.Repo.Migrations.AddOtelMetrics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  

  def up do
    create table(:otel_metrics, primary_key: false) do
add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
add :timestamp, :utc_datetime, null: false
add :metric_name, :text
add :metric_type, :text
add :value, :float
add :service_name, :text
add :service_version, :text
add :service_instance, :text
add :scope_name, :text
add :scope_version, :text
add :attributes, :map, default: %{}
add :resource_attributes, :map, default: %{}
add :tenant_id, :uuid, null: false
end

  end

  def down do
    drop table(:otel_metrics)

  end
end
