defmodule ServiceRadar.Repo.Migrations.AddTenantMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      add :owner_id,
          references(:ng_users,
            column: :id,
            name: "tenants_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:tenant_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"
      add :joined_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "tenant_memberships_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :user_id,
          references(:ng_users,
            column: :id,
            name: "tenant_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tenant_memberships, [:tenant_id, :user_id],
             name: "tenant_memberships_unique_membership_index"
           )
  end

  def down do
    drop_if_exists unique_index(:tenant_memberships, [:tenant_id, :user_id],
                     name: "tenant_memberships_unique_membership_index"
                   )

    drop constraint(:tenant_memberships, "tenant_memberships_tenant_id_fkey")

    drop constraint(:tenant_memberships, "tenant_memberships_user_id_fkey")

    drop table(:tenant_memberships)

    drop constraint(:tenants, "tenants_owner_id_fkey")

    alter table(:tenants) do
      remove :owner_id
    end
  end
end
