defmodule ServiceRadar.Repo.Migrations.AddPluginDisplayContract do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plugin_packages, prefix: "platform") do
      add :display_contract, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:plugin_packages, prefix: "platform") do
      remove :display_contract
    end
  end
end
