defmodule ServiceRadar.Repo.Migrations.AddCompositeCheckRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS platform")

    create table(:composite_check_rules, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false, default: 0
      add :match, :map, null: false, default: %{}
      add :verdict, :text, null: false
      add :verdict_label, :text, null: false
      add :verdict_description, :text
      add :status, :text, null: false, default: "unknown"
      add :catch_all, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :check_id,
          references(:composite_checks,
            column: :id,
            name: "composite_check_rules_check_id_fkey",
            type: :uuid,
            prefix: "platform",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:composite_check_rules, [:check_id, :position],
             name: "composite_check_rules_check_position_idx",
             prefix: "platform"
           )
  end

  def down do
    drop constraint(:composite_check_rules, "composite_check_rules_check_id_fkey",
           prefix: "platform"
         )

    drop_if_exists index(:composite_check_rules, [:check_id, :position],
                     name: "composite_check_rules_check_position_idx",
                     prefix: "platform"
                   )

    drop table(:composite_check_rules, prefix: "platform")
  end
end
