defmodule ServiceRadar.Inventory.Identity.Mac do
  @moduledoc """
  MAC address normalization, validation and confidence classification.

  All MAC identifier values in the system are atomic, validated 12-hex-char
  strings produced by this module. Multi-value source fields are split;
  malformed values never become identifiers.
  """

  import Bitwise

  @doc """
  Normalize and validate a MAC address field.

  The field may carry multiple delimited values (Armis emits comma-joined
  MAC histories); the first valid MAC is returned. A valid MAC is exactly
  12 hex characters after stripping `:`/`-`/`.` separators. Anything else
  (malformed values, multi-MAC blobs with no valid entry) returns `nil` and
  must never become an identifier.
  """
  @spec normalize_mac(String.t() | nil) :: String.t() | nil
  def normalize_mac(nil), do: nil

  def normalize_mac(mac) when is_binary(mac) do
    mac
    |> normalize_mac_list()
    |> List.first()
  end

  def normalize_mac(_), do: nil

  @mac_value_pattern ~r/^[0-9A-F]{12}$/

  @doc """
  Normalize a raw MAC field into a list of valid atomic MAC values.

  Splits multi-value fields (comma/semicolon/whitespace delimited), strips
  separators, uppercases, validates each entry to exactly 12 hex characters,
  and dedupes preserving order. Invalid entries are dropped.
  """
  @spec normalize_mac_list(String.t() | nil) :: [String.t()]
  def normalize_mac_list(nil), do: []

  def normalize_mac_list(raw) when is_binary(raw) do
    raw
    |> String.split(~r/[,;\s]+/, trim: true)
    |> Enum.map(&normalize_single_mac/1)
    |> Enum.reject(&is_nil/1)
    |> Enum.uniq()
  end

  def normalize_mac_list(_), do: []

  defp normalize_single_mac(value) do
    normalized =
      value
      |> String.trim()
      |> String.upcase()
      |> String.replace(":", "")
      |> String.replace("-", "")
      |> String.replace(".", "")

    if Regex.match?(@mac_value_pattern, normalized), do: normalized
  end

  @doc """
  Check if a MAC address is locally administered (IEEE bit 1 of the first octet).

  Locally-administered MACs are generated by virtualization, Docker, overlay networks,
  etc. and are not globally unique. They should be registered with medium confidence.

  ## Examples

      iex> IdentityReconciler.locally_administered_mac?("0EEA1432D278")
      true

      iex> IdentityReconciler.locally_administered_mac?("0CEA1432D278")
      false

      iex> IdentityReconciler.locally_administered_mac?("F692BF75C722")
      true

      iex> IdentityReconciler.locally_administered_mac?("F492BF75C722")
      true
  """
  @spec locally_administered_mac?(String.t() | nil) :: boolean()
  def locally_administered_mac?(nil), do: false

  def locally_administered_mac?(mac) do
    normalized = normalize_mac(mac)

    case normalized do
      nil ->
        false

      normalized when byte_size(normalized) >= 2 ->
        {first_byte, _} = Integer.parse(String.slice(normalized, 0, 2), 16)
        band(first_byte, 0x02) != 0

      _ ->
        false
    end
  end

  @doc """
  The set of universally-administered (globally-unique, hardware-anchor) MACs
  from a raw MAC field or a list of them.

  Comma/semicolon/whitespace blobs are normalized to atomic 12-hex MACs first
  (`normalize_mac_list/1`), then locally-administered MACs (virtual/Docker/overlay
  NICs — not hardware anchors) are dropped. This is the exact hardware-identity
  unit the ingest-time distinct-MAC veto (`BatchResolver`) resolves on; reuse it
  for detection/grouping so an un-merge cannot drift from prevention.
  """
  @spec universal_macs([String.t()] | String.t() | nil) :: MapSet.t()
  def universal_macs(values) when is_list(values) do
    values
    |> Enum.flat_map(&normalize_mac_list/1)
    |> Enum.reject(&locally_administered_mac?/1)
    |> MapSet.new()
  end

  def universal_macs(value) when is_binary(value), do: universal_macs([value])
  def universal_macs(_), do: MapSet.new()

  @doc """
  True when two universal-MAC sets are both non-empty and disjoint — the
  distinct-hardware condition the ingest-time veto fires on.
  """
  @spec distinct_hardware?(MapSet.t(), MapSet.t()) :: boolean()
  def distinct_hardware?(%MapSet{} = a, %MapSet{} = b) do
    MapSet.size(a) > 0 and MapSet.size(b) > 0 and MapSet.disjoint?(a, b)
  end

  @doc """
  Return the appropriate confidence level for a MAC address.
  Locally-administered MACs get :medium, globally-unique MACs get :strong.
  """
  @spec mac_confidence(String.t() | nil) :: :strong | :medium
  def mac_confidence(mac) do
    if locally_administered_mac?(mac), do: :medium, else: :strong
  end
end
