defmodule ServiceRadarWebNGWeb.SpatialLive.Index do
  @moduledoc false
  use ServiceRadarWebNGWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
     socket
     |> assign(:page_title, "FieldSurvey Data Viewer")
     |> assign(:current_path, "/spatial")}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <Layouts.app flash={@flash} current_scope={@current_scope} srql={%{page_path: @current_path}}>
      <div class="sr-spatial-page mx-auto max-w-7xl p-6 space-y-6">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <h1 class="sr-spatial-title">Spatial Surveys</h1>
            <p class="sr-spatial-subtitle">
              RoomPlan floor geometry and LiDAR-derived artifacts generated by the iOS FieldSurvey app.
            </p>
          </div>

          <.link navigate={~p"/spatial/field-surveys"} class="btn btn-sm btn-primary">
            <.icon name="hero-map" class="size-4" /> FieldSurvey Review
          </.link>
        </div>

        <.ui_panel
          class="sr-spatial-panel"
          header_class="sr-spatial-panel-header"
          body_class="sr-spatial-panel-body"
        >
          <:header>
            <div class="text-sm font-semibold">FieldSurvey Room Scan</div>
          </:header>
          <div class="sr-spatial-stage relative">
            <div class="sr-spatial-empty-state is-static-spatial-empty">
              <strong>No room scan artifacts yet</strong>
              <span>
                FieldSurvey uploads will appear here once RoomPlan floorplan artifacts are ingested.
              </span>
            </div>

            <canvas
              id="spatial-survey-map"
              phx-hook="SpatialSurveyMap"
              phx-update="ignore"
              data-api-url={~p"/api/spatial/scene"}
              class="sr-spatial-canvas"
            >
            </canvas>

            <div class="sr-spatial-legend absolute bottom-4 left-4 z-20 pointer-events-auto flex gap-2 rounded px-3 py-2 text-xs shadow-md">
              <div class="flex items-center gap-1">
                <span class="inline-block w-3 h-3 rounded-full bg-info opacity-80"></span>
                <span>RoomPlan walls</span>
              </div>
              <div class="flex items-center gap-1 ml-4">
                <span class="text-base-content/50">
                  Drag to Pan | Scroll to Zoom | Option+Drag to Orbit
                </span>
              </div>
            </div>
          </div>
        </.ui_panel>
      </div>
    </Layouts.app>
    """
  end
end
