defmodule ServiceRadarWebNGWeb.SpatialLive.Index do
  use ServiceRadarWebNGWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
     socket
     |> assign(:page_title, "FieldSurvey Data Viewer")
     |> assign(:current_path, "/spatial")}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <Layouts.app flash={@flash} current_scope={@current_scope} srql={%{page_path: @current_path}}>
      <div class="mx-auto max-w-7xl p-6 space-y-6">
        <.header>
          Spatial Surveys
          <:subtitle>
            3D Hexagon Density Maps and USDZ-derived Point Clouds generated by iOS FieldSurvey App.
          </:subtitle>
        </.header>

        <.ui_panel>
          <:header>
            <div class="text-sm font-semibold">FieldSurvey 3D Render</div>
          </:header>
          <div class="relative">
            <canvas
              id="spatial-survey-map"
              phx-hook="SpatialSurveyMap"
              phx-update="ignore"
              data-api-url={~p"/api/spatial/samples"}
              class="h-[75vh] min-h-[600px] w-full rounded-lg border border-base-200 bg-base-200/20"
            >
            </canvas>

            <div class="absolute bottom-4 left-4 z-20 pointer-events-auto flex gap-2 rounded bg-base-100/90 px-3 py-2 text-xs shadow-md border border-base-300">
              <div class="flex items-center gap-1">
                <span class="inline-block w-3 h-3 rounded-full bg-info opacity-80"></span>
                <span>Strong Signal</span>
              </div>
              <div class="flex items-center gap-1 ml-2">
                <span class="inline-block w-3 h-3 rounded-full bg-error opacity-80"></span>
                <span>Weak Signal</span>
              </div>
              <div class="flex items-center gap-1 ml-4">
                <span class="text-base-content/50">
                  Drag to Pan | Scroll to Zoom | Option+Drag to Orbit
                </span>
              </div>
            </div>
          </div>
        </.ui_panel>
      </div>
    </Layouts.app>
    """
  end
end
