# flowgger.toml

[input]
type = "udp"
listen = "0.0.0.0:514"
format = "rfc3164"

[output]
type = "nats"
format = "gelf"
framing = "noop" # NATS output handles its own framing

# NATS JetStream specific settings
nats_url = "nats://127.0.0.1:4222"
nats_subject = "events.syslog"
nats_stream = "events" # Optional: defaults to "FLOWGGER"
nats_timeout = 30000 # Optional: ACK timeout in ms, defaults to 30000
nats_tls_ca_file = "/Users/mfreeman/src/flowgger-tls-test/ca.pem"
nats_tls_cert = "/Users/mfreeman/src/flowgger-tls-test/client-cert.pem"
nats_tls_key = "/Users/mfreeman/src/flowgger-tls-test/client-key.pem"
