"""Component packaging metadata."""

PACKAGES = {
    "core": {
        "package_name": "serviceradar-core",
        "description": "ServiceRadar Core API service",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd", "jq"],
        "rpm_requires": ["systemd", "jq"],
        "binary": {
            "target": "//cmd/core:core",
            "dest": "/usr/local/bin/serviceradar-core",
        },
        "files": [
            {
                "src": "config/core.json",
                "dest": "/etc/serviceradar/core.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
            {
                "src": "config/api.env",
                "dest": "/etc/serviceradar/api.env",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
                "allow_empty": True,
            },
        ],
        "directories": [
            {"path": "/var/lib/serviceradar", "mode": "0755"},
        ],
        "systemd": {
            "src": "systemd/serviceradar-core.service",
            "dest": "/lib/systemd/system/serviceradar-core.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/core.json",
            "/etc/serviceradar/api.env",
        ],
    },
    "agent": {
        "package_name": "serviceradar-agent",
        "description": "ServiceRadar Agent Service",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd", "libcap"],
        "binary": {
            "target": "//cmd/agent:agent",
            "dest": "/usr/local/bin/serviceradar-agent",
        },
        "files": [
            {
                "src": "config/agent.json",
                "dest": "/etc/serviceradar/agent.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
            {
                "src": "config/checkers/sweep/sweep.json",
                "dest": "/etc/serviceradar/checkers/sweep/sweep.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
                "allow_empty": True,
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-agent.service",
            "dest": "/lib/systemd/system/serviceradar-agent.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/agent.json",
            "/etc/serviceradar/checkers/sweep/sweep.json",
        ],
    },
    "poller": {
        "package_name": "serviceradar-poller",
        "description": "ServiceRadar Poller Service",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/poller:poller",
            "dest": "/usr/local/bin/serviceradar-poller",
        },
        "files": [
            {
                "src": "config/poller.json",
                "dest": "/etc/serviceradar/poller.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
                "allow_empty": True,
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-poller.service",
            "dest": "/lib/systemd/system/serviceradar-poller.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/poller.json",
        ],
    },
    "mapper": {
        "package_name": "serviceradar-mapper",
        "description": "ServiceRadar Mapper Service",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/mapper:mapper",
            "dest": "/usr/local/bin/serviceradar-mapper",
        },
        "files": [
            {
                "src": "config/mapper.json",
                "dest": "/etc/serviceradar/mapper.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
                "allow_empty": True,
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-mapper.service",
            "dest": "/lib/systemd/system/serviceradar-mapper.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/mapper.json",
        ],
    },
    "kv": {
        "package_name": "serviceradar-kv",
        "description": "ServiceRadar Key/Value Service",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/kv:kv",
            "dest": "/usr/local/bin/serviceradar-kv",
        },
        "files": [
            {
                "src": "config/kv.json",
                "dest": "/etc/serviceradar/kv.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-kv.service",
            "dest": "/lib/systemd/system/serviceradar-kv.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/kv.json",
        ],
    },
    "sync": {
        "package_name": "serviceradar-sync",
        "description": "ServiceRadar Sync Service",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/sync:sync",
            "dest": "/usr/local/bin/serviceradar-sync",
        },
        "files": [
            {
                "src": "config/sync.json",
                "dest": "/etc/serviceradar/sync.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-sync.service",
            "dest": "/lib/systemd/system/serviceradar-sync.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/sync.json",
        ],
    },
    "event-writer": {
        "package_name": "serviceradar-event-writer",
        "description": "ServiceRadar DB Event Writer Service",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd", "jq"],
        "rpm_requires": ["systemd", "jq"],
        "binary": {
            "target": "//cmd/consumers/db-event-writer:db-event-writer",
            "dest": "/usr/local/bin/serviceradar-event-writer",
        },
        "files": [
            {
                "src": "config/db-event-writer.json",
                "dest": "/etc/serviceradar/consumers/db-event-writer.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-event-writer.service",
            "dest": "/lib/systemd/system/serviceradar-event-writer.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/consumers/db-event-writer.json",
        ],
    },
    "faker": {
        "package_name": "serviceradar-faker",
        "description": "ServiceRadar Faker Service",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/faker:faker",
            "dest": "/usr/local/bin/serviceradar-faker",
        },
        "files": [
            {
                "src": "config/faker.json",
                "dest": "/etc/serviceradar/faker.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-faker.service",
            "dest": "/lib/systemd/system/serviceradar-faker.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/faker.json",
        ],
    },
    "dusk-checker": {
        "package_name": "serviceradar-dusk-checker",
        "description": "ServiceRadar Dusk Checker",
        "maintainer": "Carver Automation Corporation <support@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/checkers/dusk:dusk",
            "dest": "/usr/local/bin/serviceradar-dusk-checker",
        },
        "files": [
            {
                "src": "config/dusk.json",
                "dest": "/etc/serviceradar/checkers/dusk.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-dusk-checker.service",
            "dest": "/lib/systemd/system/serviceradar-dusk-checker.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/checkers/dusk.json",
        ],
    },
    "snmp-checker": {
        "package_name": "serviceradar-snmp-checker",
        "description": "ServiceRadar SNMP Checker",
        "maintainer": "Carver Automation Corporation <support@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/checkers/snmp:snmp",
            "dest": "/usr/local/bin/serviceradar-snmp-checker",
        },
        "systemd": {
            "src": "systemd/serviceradar-snmp-checker.service",
            "dest": "/lib/systemd/system/serviceradar-snmp-checker.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
    },
    "trapd": {
        "package_name": "serviceradar-trapd",
        "description": "ServiceRadar SNMP trap receiver service",
        "maintainer": "Carver Automation Corporation <support@carverauto.dev>",
        "architecture": "amd64",
        "section": "net",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/trapd:trapd",
            "dest": "/usr/local/bin/serviceradar-trapd",
        },
        "files": [
            {
                "src": "config/trapd.json",
                "dest": "/etc/serviceradar/trapd.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-trapd.service",
            "dest": "/lib/systemd/system/serviceradar-trapd.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/trapd.json",
        ],
    },
    "flowgger": {
        "package_name": "serviceradar-flowgger",
        "description": "ServiceRadar Flowgger log collector",
        "maintainer": "Carver Automation Corporation <support@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/flowgger:flowgger",
            "dest": "/usr/local/bin/serviceradar-flowgger",
        },
        "files": [
            {
                "src": "config/flowgger.toml",
                "dest": "/etc/serviceradar/flowgger.toml",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-flowgger.service",
            "dest": "/lib/systemd/system/serviceradar-flowgger.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/flowgger.toml",
        ],
    },
    "kong": {
        "package_name": "serviceradar-kong",
        "description": "Wrapper package bundling Kong Gateway OSS for air-gapped installs",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "net",
        "priority": "optional",
        "deb_depends": ["systemd", "ca-certificates", "serviceradar-cli"],
        "rpm_requires": ["systemd", "ca-certificates", "serviceradar-cli"],
        "files": [
            {
                "src": "config/kong.conf",
                "dest": "/etc/kong/kong.conf",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
            {
                "src": "scripts/kong-wrapper.sh",
                "dest": "/usr/share/serviceradar-kong/scripts/kong-wrapper.sh",
                "mode": "0755",
            },
        ],
        "trees": [
            {
                "patterns": ["vendor/**"],
                "strip_prefix": "vendor",
                "dest": "/usr/share/serviceradar-kong/vendor",
                "allow_empty": True,
            },
        ],
        "directories": [
            {"path": "/usr/share/serviceradar-kong", "mode": "0755"},
            {"path": "/usr/share/serviceradar-kong/scripts", "mode": "0755"},
        ],
        "systemd": {
            "src": "systemd/serviceradar-kong.service",
            "dest": "/lib/systemd/system/serviceradar-kong.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
    },
    "nats": {
        "package_name": "serviceradar-nats",
        "description": "ServiceRadar NATS JetStream service",
        "maintainer": "Carver Automation Corporation <support@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "files": [
            {
                "src": "@nats_server_linux_amd64//:nats_server",
                "dest": "/usr/bin/nats-server",
                "mode": "0755",
            },
            {
                "src": "config/nats-server.conf",
                "dest": "/etc/nats/nats-server.conf",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
            {
                "src": "config/nats-cloud.conf",
                "dest": "/etc/nats/templates/nats-cloud.conf",
                "mode": "0644",
            },
            {
                "src": "config/nats-leaf.conf",
                "dest": "/etc/nats/templates/nats-leaf.conf",
                "mode": "0644",
            },
        ],
        "directories": [
            {"path": "/etc/nats/templates", "mode": "0755"},
            {"path": "/var/lib/nats", "mode": "0755"},
            {"path": "/var/lib/nats/jetstream", "mode": "0755"},
            {"path": "/var/log/nats", "mode": "0755"},
        ],
        "systemd": {
            "src": "systemd/serviceradar-nats.service",
            "dest": "/lib/systemd/system/serviceradar-nats.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/nats/nats-server.conf",
        ],
    },
    "proton": {
        "package_name": "serviceradar-proton",
        "description": "ServiceRadar Proton Server (Stream Processing Engine)",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "database",
        "priority": "optional",
        "deb_depends": ["systemd", "libcap2-bin", "serviceradar-cli"],
        "rpm_requires": ["systemd", "libcap"],
        "files": [
            {
                "src": "@timeplus_proton_linux_x86_64//file:file",
                "dest": "/usr/bin/proton",
                "mode": "0755",
            },
            {
                "src": "//packaging/proton/config:config.yaml",
                "dest": "/usr/share/serviceradar-proton/config.yaml",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
            {
                "src": "//packaging/proton/config:users.yaml",
                "dest": "/usr/share/serviceradar-proton/users.yaml",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
            {
                "src": "//packaging/proton/config:grok-patterns",
                "dest": "/usr/share/serviceradar-proton/grok-patterns",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "directories": [
            {"path": "/var/lib/proton", "mode": "0755"},
            {"path": "/var/lib/proton/tmp", "mode": "0755"},
            {"path": "/var/lib/proton/checkpoint", "mode": "0755"},
            {"path": "/var/lib/proton/nativelog", "mode": "0755"},
            {"path": "/var/lib/proton/nativelog/meta", "mode": "0755"},
            {"path": "/var/lib/proton/nativelog/log", "mode": "0755"},
            {"path": "/var/lib/proton/user_files", "mode": "0755"},
            {"path": "/var/log/proton-server", "mode": "0755"},
            {"path": "/etc/proton-server", "mode": "0755"},
            {"path": "/usr/share/serviceradar-proton", "mode": "0755"},
        ],
        "systemd": {
            "src": "systemd/serviceradar-proton.service",
            "dest": "/lib/systemd/system/serviceradar-proton.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/usr/share/serviceradar-proton/config.yaml",
            "/usr/share/serviceradar-proton/users.yaml",
            "/usr/share/serviceradar-proton/grok-patterns",
        ],
    },
    "zen": {
        "package_name": "serviceradar-zen",
        "description": "ServiceRadar Zen consumer",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/consumers/zen:zen",
            "dest": "/usr/local/bin/serviceradar-zen",
        },
        "files": [
            {
                "src": "config/zen-consumer.json",
                "dest": "/etc/serviceradar/zen-consumer.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
            {
                "src": "rules/cef_severity.json",
                "dest": "/usr/share/serviceradar-zen/rules/cef_severity.json",
                "mode": "0644",
            },
            {
                "src": "rules/passthrough.json",
                "dest": "/usr/share/serviceradar-zen/rules/passthrough.json",
                "mode": "0644",
            },
            {
                "src": "rules/strip_full_message.json",
                "dest": "/usr/share/serviceradar-zen/rules/strip_full_message.json",
                "mode": "0644",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-zen.service",
            "dest": "/lib/systemd/system/serviceradar-zen.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/zen-consumer.json",
        ],
    },
    "rperf": {
        "package_name": "serviceradar-rperf",
        "description": "ServiceRadar RPerf network performance server",
        "maintainer": "Carver Automation Corporation <support@carverauto.dev>",
        "architecture": "amd64",
        "section": "net",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "@rust_crates_rperf_checker//:rperf",
            "dest": "/usr/local/bin/serviceradar-rperf",
        },
        "files": [
            {
                "src": "config/rperf/rperf.conf",
                "dest": "/etc/serviceradar/rperf/rperf.conf",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-rperf.service",
            "dest": "/lib/systemd/system/serviceradar-rperf.service",
        },
        "directories": [
            {"path": "/var/log/rperf", "mode": "0755"},
            {"path": "/etc/serviceradar/rperf", "mode": "0755"},
        ],
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/rperf/rperf.conf",
        ],
    },
    "rperf-checker": {
        "package_name": "serviceradar-rperf-checker",
        "description": "ServiceRadar RPerf network performance checker",
        "maintainer": "Carver Automation Corporation <support@carverauto.dev>",
        "architecture": "amd64",
        "section": "net",
        "priority": "optional",
        "deb_depends": ["systemd"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/checkers/rperf-client:rperf_checker",
            "dest": "/usr/local/bin/serviceradar-rperf-checker",
        },
        "files": [
            {
                "src": "config/checkers/rperf.json",
                "dest": "/etc/serviceradar/checkers/rperf.json.example",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-rperf-checker.service",
            "dest": "/lib/systemd/system/serviceradar-rperf-checker.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/checkers/rperf.json.example",
        ],
    },
    "profiler": {
        "package_name": "serviceradar-profiler",
        "description": "ServiceRadar Profiler agent",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": [],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/ebpf/profiler:profiler",
            "dest": "/usr/local/bin/serviceradar-profiler",
        },
        "files": [
            {
                "src": "config/profiler.toml",
                "dest": "/etc/serviceradar/profiler.toml",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-profiler.service",
            "dest": "/lib/systemd/system/serviceradar-profiler.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/profiler.toml",
        ],
    },
    "sysmon": {
        "package_name": "serviceradar-sysmon-checker",
        "description": "ServiceRadar System Monitor checker",
        "maintainer": "Carver Automation Corporation <support@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd", "libssl-dev", "ca-certificates"],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/checkers/sysmon:sysmon",
            "dest": "/usr/local/bin/serviceradar-sysmon-checker",
        },
        "files": [
            {
                "src": "config/checkers/sysmon.json.example",
                "dest": "/etc/serviceradar/checkers/sysmon.json.example",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-sysmon-checker.service",
            "dest": "/lib/systemd/system/serviceradar-sysmon-checker.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/checkers/sysmon.json.example",
        ],
    },
    "web": {
        "package_name": "serviceradar-web",
        "description": "ServiceRadar web dashboard",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": ["systemd", "nginx"],
        "rpm_requires": ["systemd", "nginx"],
        "files": [
            {
                "src": "config/web.json",
                "dest": "/etc/serviceradar/web.json",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
            {
                "src": "config/nginx.conf",
                "dest": "/etc/nginx/conf.d/serviceradar-web.conf",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
            {
                "src": "//packaging/web:bundle_root",
                "dest": "/usr/local/share/serviceradar-web/",
            },
            {
                "src": "//packaging/web:bundle_next",
                "dest": "/usr/local/share/serviceradar-web/.next/",
            },
            {
                "src": "//web:public_flat",
                "dest": "/usr/local/share/serviceradar-web/public/",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-web.service",
            "dest": "/lib/systemd/system/serviceradar-web.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/web.json",
            "/etc/nginx/conf.d/serviceradar-web.conf",
        ],
    },
    "cli": {
        "package_name": "serviceradar-cli",
        "description": "ServiceRadar CLI tool",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": [],
        "rpm_requires": [],
        "binary": {
            "target": "//cmd/cli:cli",
            "dest": "/usr/local/bin/serviceradar",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
    },
    "srql": {
        "package_name": "serviceradar-srql",
        "description": "ServiceRadar SRQL OCaml query service",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "net",
        "priority": "optional",
        "deb_depends": ["systemd", "ca-certificates", "curl", "libev4", "libgmp10", "liblz4-1", "libzstd1", "libssl3"],
        "rpm_requires": ["systemd", "ca-certificates", "curl", "libev", "gmp", "lz4", "zstd", "openssl"],
        "binary": {
            "target": "//ocaml/srql:srql_server",
            "dest": "/usr/local/bin/serviceradar-srql",
        },
        "files": [
            {
                "src": "config/srql.env",
                "dest": "/etc/serviceradar/srql.env",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-srql.service",
            "dest": "/lib/systemd/system/serviceradar-srql.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/prerm.sh",
        "conffiles": [
            "/etc/serviceradar/srql.env",
        ],
    },
    "otel": {
        "package_name": "serviceradar-otel",
        "description": "ServiceRadar OTEL Collector",
        "maintainer": "Michael Freeman <mfreeman@carverauto.dev>",
        "architecture": "amd64",
        "section": "utils",
        "priority": "optional",
        "deb_depends": [],
        "rpm_requires": ["systemd"],
        "binary": {
            "target": "//cmd/otel:otel",
            "dest": "/usr/local/bin/serviceradar-otel",
        },
        "files": [
            {
                "src": "config/otel.toml",
                "dest": "/etc/serviceradar/otel.toml",
                "mode": "0644",
                "rpm_filetag": "config(noreplace)",
            },
        ],
        "systemd": {
            "src": "systemd/serviceradar-otel.service",
            "dest": "/lib/systemd/system/serviceradar-otel.service",
        },
        "postinst": "scripts/postinstall.sh",
        "prerm": "scripts/preremove.sh",
        "conffiles": [
            "/etc/serviceradar/otel.toml",
        ],
    },
}
