[package]
name = "kvutil"
version = "0.1.0"
edition = "2021"

[lib]
name = "kvutil"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tonic = { workspace = true }
prost = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio-stream = { workspace = true }
toml = "0.8"

[build-dependencies]
tonic-build = { workspace = true }
