[package]
name = "kvutil"
version = "0.1.0"
edition = "2021"

[lib]
name = "kvutil"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = { version = "0.12", features = ["tls"] }
prost = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio-stream = "0.1"
toml = "0.8"

[build-dependencies]
tonic-build = "0.12"
