[package]
name = "kvutil"
version = "0.1.0"
edition = "2024"


[lib]
name = "kvutil"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
pem = { workspace = true }
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
spiffe = { workspace = true, features = ["x509-source"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tokio-stream = { workspace = true }
toml = { workspace = true }
tonic = { workspace = true, features = ["tls-ring"] }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
