exports_files([
    "addon.yaml",
    "config.schema.json",
    "display/dns_activity.display.json",
    "schemas/dns_activity.schema.json",
])

filegroup(
    name = "powerdns_manifest",
    srcs = [
        "addon.yaml",
        "config.schema.json",
        "display/dns_activity.display.json",
        "schemas/dns_activity.schema.json",
    ],
    visibility = ["//visibility:public"],
)
