// Module for handling flame graph data format and utilities

use crate::ebpf_profiler::ProfileStackTrace;
use std::collections::HashMap;
use std::str::FromStr;
use inferno::flamegraph;
use anyhow::Result;

pub struct FlameGraphFormatter {
    traces: Vec<ProfileStackTrace>,
}

impl FlameGraphFormatter {
    pub fn new(traces: Vec<ProfileStackTrace>) -> Self {
        Self { traces }
    }

    /// Convert stack traces to folded stack format suitable for flame graph generation
    pub fn to_folded_format(&self) -> String {
        let mut output = String::new();
        
        for trace in &self.traces {
            output.push_str(&trace.to_folded_format());
            output.push('\n');
        }
        
        output
    }

    /// Generate metadata header for the flame graph data
    pub fn generate_metadata(&self, pid: i32, duration_seconds: i32) -> String {
        let total_samples: u64 = self.traces.iter().map(|t| t.count).sum();
        let unique_stacks = self.traces.len();
        
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        format!(
            "# ServiceRadar eBPF Profiler Results\n\
             # PID: {}\n\
             # Duration: {}s\n\
             # Timestamp: {}\n\
             # Total samples: {}\n\
             # Unique stacks: {}\n\
             # Generated by: ServiceRadar eBPF Profiler v{}\n\n",
            pid,
            duration_seconds,
            timestamp,
            total_samples,
            unique_stacks,
            env!("CARGO_PKG_VERSION")
        )
    }

    /// Generate complete flame graph data with header and folded stacks
    pub fn generate_complete_output(&self, pid: i32, duration_seconds: i32) -> Vec<u8> {
        let metadata = self.generate_metadata(pid, duration_seconds);
        let folded_data = self.to_folded_format();
        
        let mut result = metadata.into_bytes();
        result.extend_from_slice(folded_data.as_bytes());
        result
    }

    /// Aggregate traces by function to show top consumers
    pub fn get_function_statistics(&self) -> Vec<FunctionStats> {
        let mut function_counts: HashMap<String, u64> = HashMap::new();
        
        // Count occurrences of each function across all stack traces
        for trace in &self.traces {
            for frame in &trace.frames {
                *function_counts.entry(frame.clone()).or_insert(0) += trace.count;
            }
        }
        
        // Convert to sorted list
        let mut stats: Vec<FunctionStats> = function_counts
            .into_iter()
            .map(|(function, count)| FunctionStats { function, count })
            .collect();
        
        stats.sort_by(|a, b| b.count.cmp(&a.count));
        stats
    }

    /// Generate interactive HTML flamegraph (like Brendan Gregg's)
    pub fn generate_flamegraph_html(&self, title: &str) -> Result<String> {
        let folded_data = self.to_folded_format();
        
        let mut svg_output = Vec::new();
        let mut options = flamegraph::Options::default();
        
        // Configure the flamegraph to look like Brendan Gregg's style
        options.title = title.to_string();
        options.subtitle = Some("ServiceRadar eBPF Profiler".to_string());
        options.min_width = 0.01; // Show smaller functions
        options.font_type = "Verdana".to_string();
        options.font_size = 12;
        options.colors = flamegraph::color::Palette::from_str("hot").unwrap_or_default();
        options.bgcolors = Some(flamegraph::color::BackgroundColor::Blue);
        options.hash = true; // Consistent colors
        
        // Generate SVG flamegraph
        flamegraph::from_reader(&mut options, folded_data.as_bytes(), &mut svg_output)?;
        
        let svg_content = String::from_utf8(svg_output)?;
        
        // Wrap in HTML with interactivity
        let html = format!(r#"
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{}</title>
    <style>
        body {{
            margin: 0;
            padding: 20px;
            font-family: Verdana, sans-serif;
            background-color: #f5f5f5;
        }}
        .flamegraph-container {{
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            padding: 20px;
            overflow: auto;
        }}
        .controls {{
            margin-bottom: 15px;
            padding: 10px;
            background: #eeeeee;
            border-radius: 4px;
        }}
        button {{
            padding: 5px 10px;
            margin-right: 10px;
            background: #007acc;
            color: white;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }}
        button:hover {{
            background: #005999;
        }}
        .info {{
            margin-top: 15px;
            padding: 10px;
            background: #e8f4f8;
            border-left: 4px solid #007acc;
            border-radius: 0 4px 4px 0;
        }}
    </style>
</head>
<body>
    <div class="flamegraph-container">
        <div class="controls">
            <button onclick="resetZoom()">Reset Zoom</button>
            <button onclick="searchFunction()">Search</button>
            <span id="details" style="margin-left: 20px; font-weight: bold;"></span>
        </div>
        <div id="flamegraph">
            {}
        </div>
        <div class="info">
            <h3>How to use:</h3>
            <ul>
                <li><strong>Click</strong> on any rectangle to zoom into that function</li>
                <li><strong>Reset Zoom</strong> to return to full view</li>
                <li><strong>Hover</strong> over rectangles to see details</li>
                <li><strong>Width</strong> represents time spent in function (including children)</li>
                <li><strong>Colors</strong> are consistent - same function = same color</li>
            </ul>
        </div>
    </div>

    <script>
        // Enhanced interactivity for the flamegraph
        let originalViewBox = null;
        let currentZoom = null;
        
        // Initialize flamegraph interactivity
        document.addEventListener('DOMContentLoaded', function() {{
            const svg = document.querySelector('svg');
            if (svg) {{
                originalViewBox = svg.getAttribute('viewBox');
                setupFlameGraphInteractivity();
            }}
        }});
        
        function setupFlameGraphInteractivity() {{
            const rects = document.querySelectorAll('svg rect');
            const texts = document.querySelectorAll('svg text');
            
            // Add click handlers to rectangles for zooming
            rects.forEach(function(rect) {{
                rect.style.cursor = 'pointer';
                rect.addEventListener('click', function() {{
                    zoomToElement(rect);
                }});
                
                rect.addEventListener('mouseenter', function() {{
                    showDetails(rect);
                }});
                
                rect.addEventListener('mouseleave', function() {{
                    hideDetails();
                }});
            }});
            
            // Add click handlers to text elements too
            texts.forEach(function(text) {{
                text.style.cursor = 'pointer';
                text.addEventListener('click', function() {{
                    const rect = text.previousElementSibling;
                    if (rect && rect.tagName === 'rect') {{
                        zoomToElement(rect);
                    }}
                }});
            }});
        }}
        
        function zoomToElement(element) {{
            const svg = document.querySelector('svg');
            const rect = element.getBBox();
            const padding = 10;
            
            const newViewBox = `${{rect.x - padding}} ${{rect.y - padding}} ${{rect.width + 2*padding}} ${{rect.height + 2*padding}}`;
            svg.setAttribute('viewBox', newViewBox);
            currentZoom = newViewBox;
            
            // Update details
            const funcName = element.getAttribute('data-function') || 'Unknown Function';
            const samples = element.getAttribute('data-samples') || '0';
            document.getElementById('details').textContent = `Zoomed: ${{funcName}} (${{samples}} samples)`;
        }}
        
        function resetZoom() {{
            const svg = document.querySelector('svg');
            if (originalViewBox) {{
                svg.setAttribute('viewBox', originalViewBox);
                currentZoom = null;
                document.getElementById('details').textContent = '';
            }}
        }}
        
        function showDetails(element) {{
            const funcName = element.getAttribute('data-function') || 'Unknown Function';
            const samples = element.getAttribute('data-samples') || '0';
            const percentage = element.getAttribute('data-percentage') || '0.0';
            document.getElementById('details').textContent = `${{funcName}}: ${{samples}} samples (${{percentage}}%)`;
        }}
        
        function hideDetails() {{
            if (!currentZoom) {{
                document.getElementById('details').textContent = '';
            }}
        }}
        
        function searchFunction() {{
            const term = prompt('Enter function name to search:');
            if (!term) return;
            
            const rects = document.querySelectorAll('svg rect');
            const texts = document.querySelectorAll('svg text');
            
            // Reset highlights
            rects.forEach(r => r.style.stroke = '');
            
            // Highlight matching functions
            let found = false;
            texts.forEach(function(text) {{
                if (text.textContent.toLowerCase().includes(term.toLowerCase())) {{
                    const rect = text.previousElementSibling;
                    if (rect && rect.tagName === 'rect') {{
                        rect.style.stroke = '#ff0000';
                        rect.style.strokeWidth = '2';
                        found = true;
                    }}
                }}
            }});
            
            if (!found) {{
                alert(`No functions found matching: ${{term}}`);
            }}
        }}
    </script>
</body>
</html>"#, title, svg_content);

        Ok(html)
    }
    
    /// Save flamegraph as HTML file
    pub fn save_flamegraph_html(&self, path: &str, title: &str) -> Result<()> {
        let html = self.generate_flamegraph_html(title)?;
        std::fs::write(path, html)?;
        Ok(())
    }

    /// Get summary statistics about the profiling session
    pub fn get_summary(&self) -> ProfilingSummary {
        let total_samples: u64 = self.traces.iter().map(|t| t.count).sum();
        let unique_stacks = self.traces.len();
        
        let max_depth = self.traces
            .iter()
            .map(|t| t.frames.len())
            .max()
            .unwrap_or(0);
        
        let avg_depth = if unique_stacks > 0 {
            self.traces.iter().map(|t| t.frames.len()).sum::<usize>() as f64 / unique_stacks as f64
        } else {
            0.0
        };

        ProfilingSummary {
            total_samples,
            unique_stacks,
            max_stack_depth: max_depth,
            avg_stack_depth: avg_depth,
            top_functions: self.get_function_statistics().into_iter().take(10).collect(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct FunctionStats {
    pub function: String,
    pub count: u64,
}

#[derive(Debug)]
pub struct ProfilingSummary {
    pub total_samples: u64,
    pub unique_stacks: usize,
    pub max_stack_depth: usize,
    pub avg_stack_depth: f64,
    pub top_functions: Vec<FunctionStats>,
}

impl ProfilingSummary {
    pub fn to_string(&self) -> String {
        let mut output = String::new();
        output.push_str(&format!("Profiling Summary:\n"));
        output.push_str(&format!("  Total samples: {}\n", self.total_samples));
        output.push_str(&format!("  Unique stacks: {}\n", self.unique_stacks));
        output.push_str(&format!("  Max stack depth: {}\n", self.max_stack_depth));
        output.push_str(&format!("  Avg stack depth: {:.1}\n", self.avg_stack_depth));
        output.push_str(&format!("  Top functions:\n"));
        
        for (i, func) in self.top_functions.iter().enumerate() {
            let percentage = if self.total_samples > 0 {
                (func.count as f64 / self.total_samples as f64) * 100.0
            } else {
                0.0
            };
            output.push_str(&format!(
                "    {}: {} ({} samples, {:.1}%)\n",
                i + 1, func.function, func.count, percentage
            ));
        }
        
        output
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_traces() -> Vec<ProfileStackTrace> {
        vec![
            ProfileStackTrace {
                frames: vec!["main".to_string(), "foo".to_string(), "bar".to_string()],
                count: 10,
            },
            ProfileStackTrace {
                frames: vec!["main".to_string(), "foo".to_string(), "baz".to_string()],
                count: 20,
            },
            ProfileStackTrace {
                frames: vec!["main".to_string(), "other".to_string()],
                count: 5,
            },
        ]
    }

    #[test]
    fn test_flame_graph_formatter_creation() {
        let traces = create_test_traces();
        let formatter = FlameGraphFormatter::new(traces);
        assert_eq!(formatter.traces.len(), 3);
    }

    #[test]
    fn test_to_folded_format() {
        let traces = create_test_traces();
        let formatter = FlameGraphFormatter::new(traces);
        let folded = formatter.to_folded_format();
        
        assert!(folded.contains("main;foo;bar 10"));
        assert!(folded.contains("main;foo;baz 20"));
        assert!(folded.contains("main;other 5"));
    }

    #[test]
    fn test_generate_metadata() {
        let traces = create_test_traces();
        let formatter = FlameGraphFormatter::new(traces);
        let metadata = formatter.generate_metadata(123, 10);
        
        assert!(metadata.contains("# PID: 123"));
        assert!(metadata.contains("# Duration: 10s"));
        assert!(metadata.contains("# Total samples: 35")); // 10 + 20 + 5
        assert!(metadata.contains("# Unique stacks: 3"));
        assert!(metadata.contains("ServiceRadar eBPF Profiler"));
    }

    #[test]
    fn test_generate_complete_output() {
        let traces = create_test_traces();
        let formatter = FlameGraphFormatter::new(traces);
        let output = formatter.generate_complete_output(123, 10);
        let output_str = String::from_utf8(output).unwrap();
        
        // Should contain both metadata and folded data
        assert!(output_str.contains("# PID: 123"));
        assert!(output_str.contains("main;foo;bar 10"));
    }

    #[test]
    fn test_function_statistics() {
        let traces = create_test_traces();
        let formatter = FlameGraphFormatter::new(traces);
        let stats = formatter.get_function_statistics();
        
        // main appears in all traces: 10 + 20 + 5 = 35
        // foo appears in first two traces: 10 + 20 = 30
        // bar appears in first trace: 10
        // baz appears in second trace: 20
        // other appears in third trace: 5
        
        assert_eq!(stats.len(), 5);
        assert_eq!(stats[0].function, "main");
        assert_eq!(stats[0].count, 35);
        assert_eq!(stats[1].function, "foo");
        assert_eq!(stats[1].count, 30);
    }

    #[test]
    fn test_profiling_summary() {
        let traces = create_test_traces();
        let formatter = FlameGraphFormatter::new(traces);
        let summary = formatter.get_summary();
        
        assert_eq!(summary.total_samples, 35);
        assert_eq!(summary.unique_stacks, 3);
        assert_eq!(summary.max_stack_depth, 3); // main;foo;bar has 3 frames
        assert_eq!(summary.avg_stack_depth, (3 + 3 + 2) as f64 / 3.0); // (3+3+2)/3 = 2.67
        assert_eq!(summary.top_functions.len(), 5);
    }

    #[test]
    fn test_summary_to_string() {
        let traces = create_test_traces();
        let formatter = FlameGraphFormatter::new(traces);
        let summary = formatter.get_summary();
        let summary_str = summary.to_string();
        
        assert!(summary_str.contains("Total samples: 35"));
        assert!(summary_str.contains("Unique stacks: 3"));
        assert!(summary_str.contains("Max stack depth: 3"));
        assert!(summary_str.contains("Top functions:"));
        assert!(summary_str.contains("main"));
    }

    #[test]
    fn test_empty_traces() {
        let traces = vec![];
        let formatter = FlameGraphFormatter::new(traces);
        let summary = formatter.get_summary();
        
        assert_eq!(summary.total_samples, 0);
        assert_eq!(summary.unique_stacks, 0);
        assert_eq!(summary.max_stack_depth, 0);
        assert_eq!(summary.avg_stack_depth, 0.0);
        assert!(summary.top_functions.is_empty());
    }
}