defmodule ServiceRadarWebNGWeb.SRQL.Catalog do
  @moduledoc false

  @wifi_site_filter_fields [
    "source_id",
    "site_code",
    "iata",
    "name",
    "site_name",
    "site_type",
    "region",
    "latitude",
    "lat",
    "longitude",
    "lon",
    "lng",
    "ap_count",
    "up_count",
    "down_count",
    "wlc_count",
    "server_group",
    "cluster",
    "aaa_profile",
    "all_server_groups",
    "controller_names",
    "controllers"
  ]

  @wifi_site_numeric_fields [
    "latitude",
    "lat",
    "longitude",
    "lon",
    "lng",
    "ap_count",
    "up_count",
    "down_count",
    "wlc_count"
  ]

  @wifi_device_filter_fields [
    "id",
    "source_id",
    "batch_id",
    "device_uid",
    "site_code",
    "iata",
    "site_name",
    "region",
    "latitude",
    "lat",
    "longitude",
    "lon",
    "lng",
    "name",
    "hostname",
    "host",
    "mac",
    "serial",
    "ip",
    "status",
    "model"
  ]

  @wifi_device_numeric_fields ["latitude", "lat", "longitude", "lon", "lng"]

  @entities [
    %{
      id: "agents",
      label: "Agents",
      route: "/agents",
      default_time: "",
      default_sort_field: "last_seen",
      default_sort_dir: "desc",
      default_filter_field: "uid",
      filter_fields: [
        "uid",
        "name",
        "gateway_id",
        "version",
        "desired_version",
        "release_rollout_state",
        "last_update_error",
        "vendor_name",
        "ip",
        "type_id",
        "capabilities",
        "config_source"
      ],
      array_fields: ["capabilities"],
      downsample: false
    },
    %{
      id: "devices",
      label: "Devices",
      route: "/devices",
      default_time: "",
      default_sort_field: "last_seen",
      default_sort_dir: "desc",
      default_filter_field: "hostname",
      filter_fields: [
        "hostname",
        "ip",
        "mac",
        "uid",
        "gateway_id",
        "agent_id",
        "is_available",
        "is_managed",
        "is_compliant",
        "is_trusted",
        "type_id",
        "type",
        "vendor_name",
        "discovery_sources",
        "tags",
        "include_deleted"
      ],
      boolean_fields: [
        "is_available",
        "is_managed",
        "is_compliant",
        "is_trusted",
        "include_deleted"
      ],
      # Fields backed by array columns - builder will always use list syntax for these
      array_fields: ["discovery_sources", "tags"],
      # Fields that support GROUP BY in stats queries (stats:count() as count by <field>)
      stats_fields: ["type", "vendor_name", "risk_level", "is_available", "gateway_id"],
      downsample: false
    },
    %{
      id: "gateways",
      label: "Gateways",
      route: "/gateways",
      default_time: "",
      default_sort_field: "last_seen",
      default_sort_dir: "desc",
      default_filter_field: "id",
      filter_fields: ["id", "status", "component_id", "registration_source", "is_healthy"],
      boolean_fields: ["is_healthy"],
      downsample: false
    },
    %{
      id: "events",
      label: "Events",
      route: "/events",
      default_time: "last_7d",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "message",
      filter_fields: [
        "activity_name",
        "activity_id",
        "class_uid",
        "category_uid",
        "type_uid",
        "severity",
        "severity_id",
        "log_level",
        "log_name",
        "log_provider",
        "status",
        "status_id",
        "status_code",
        "status_detail",
        "trace_id",
        "span_id",
        "message",
        "short_message"
      ],
      downsample: false
    },
    %{
      id: "bmp_events",
      label: "BMP Events",
      route: "/observability",
      default_time: "last_24h",
      default_sort_field: "time",
      default_sort_dir: "desc",
      default_filter_field: "router_ip",
      filter_fields: [
        "event_type",
        "severity_id",
        "router_id",
        "router_ip",
        "peer_ip",
        "peer_asn",
        "local_asn",
        "prefix",
        "message"
      ],
      downsample: false
    },
    %{
      id: "field_survey_sessions",
      label: "FieldSurvey Sessions",
      route: "/spatial/field-surveys",
      default_time: "",
      default_sort_field: "updated_at",
      default_sort_dir: "desc",
      default_filter_field: "site_id",
      filter_fields: [
        "session_id",
        "user_id",
        "site_id",
        "site_name",
        "building_id",
        "building_name",
        "floor_id",
        "floor_name",
        "floor_index",
        "tags",
        "has_floorplan"
      ],
      array_fields: ["tags"],
      boolean_fields: ["has_floorplan"],
      downsample: false
    },
    %{
      id: "field_survey_rasters",
      label: "FieldSurvey Rasters",
      route: "/spatial/field-surveys",
      default_time: "",
      default_sort_field: "generated_at",
      default_sort_dir: "desc",
      default_filter_field: "site_id",
      filter_fields: [
        "raster_id",
        "session_id",
        "user_id",
        "overlay_type",
        "selector_type",
        "selector_value",
        "site_id",
        "site_name",
        "building_id",
        "building_name",
        "floor_id",
        "floor_name",
        "floor_index",
        "tags",
        "has_floorplan"
      ],
      array_fields: ["tags"],
      boolean_fields: ["has_floorplan"],
      downsample: false
    },
    %{
      id: "field_survey_artifacts",
      label: "FieldSurvey Artifacts",
      route: "/spatial/wifi-map",
      default_time: "",
      default_sort_field: "uploaded_at",
      default_sort_dir: "desc",
      default_filter_field: "artifact_type",
      filter_fields: [
        "artifact_id",
        "session_id",
        "user_id",
        "artifact_type",
        "content_type",
        "object_key",
        "sha256",
        "site_id",
        "site_name",
        "building_id",
        "building_name",
        "floor_id",
        "floor_name",
        "floor_index",
        "tags"
      ],
      array_fields: ["tags"],
      downsample: false
    },
    %{
      id: "field_survey_rf_observations",
      label: "FieldSurvey RF Observations",
      route: "/spatial/field-surveys",
      default_time: "last_1h",
      default_sort_field: "captured_at",
      default_sort_dir: "desc",
      default_filter_field: "bssid",
      filter_fields: [
        "id",
        "session_id",
        "sidekick_id",
        "radio_id",
        "interface_name",
        "bssid",
        "ssid",
        "frame_type",
        "frequency_mhz",
        "channel",
        "rssi_dbm",
        "noise_floor_dbm",
        "snr_db"
      ],
      downsample: false
    },
    %{
      id: "field_survey_pose_samples",
      label: "FieldSurvey Pose Samples",
      route: "/spatial/field-surveys",
      default_time: "last_1h",
      default_sort_field: "captured_at",
      default_sort_dir: "desc",
      default_filter_field: "session_id",
      filter_fields: [
        "id",
        "session_id",
        "scanner_device_id",
        "tracking_quality",
        "x",
        "y",
        "z"
      ],
      downsample: false
    },
    %{
      id: "field_survey_rf_pose_matches",
      label: "FieldSurvey RF/Pose Matches",
      route: "/spatial/field-surveys",
      default_time: "last_1h",
      default_sort_field: "rf_captured_at",
      default_sort_dir: "desc",
      default_filter_field: "bssid",
      filter_fields: [
        "rf_observation_id",
        "pose_sample_id",
        "session_id",
        "sidekick_id",
        "radio_id",
        "interface_name",
        "bssid",
        "ssid",
        "frame_type",
        "frequency_mhz",
        "channel",
        "rssi_dbm",
        "pose_offset_nanos",
        "scanner_device_id",
        "tracking_quality"
      ],
      downsample: false
    },
    %{
      id: "field_survey_spectrum_observations",
      label: "FieldSurvey Spectrum Observations",
      route: "/spatial/field-surveys",
      default_time: "last_1h",
      default_sort_field: "captured_at",
      default_sort_dir: "desc",
      default_filter_field: "sdr_id",
      filter_fields: [
        "id",
        "session_id",
        "sidekick_id",
        "sdr_id",
        "device_kind",
        "serial_number",
        "sweep_id",
        "start_frequency_hz",
        "stop_frequency_hz",
        "sample_count"
      ],
      downsample: false
    },
    %{
      id: "wifi_sites",
      label: "WiFi Sites",
      route: "/spatial/wifi-map",
      default_time: "",
      default_sort_field: "collection_timestamp",
      default_sort_dir: "desc",
      default_filter_field: "site_code",
      filter_fields: @wifi_site_filter_fields,
      numeric_fields: @wifi_site_numeric_fields,
      array_fields: ["all_server_groups", "controller_names", "controllers"],
      downsample: false
    },
    %{
      id: "wifi_site_snapshots",
      label: "WiFi Site Snapshots",
      route: "/spatial/wifi-map",
      default_time: "last_24h",
      default_sort_field: "collection_timestamp",
      default_sort_dir: "desc",
      default_filter_field: "site_code",
      filter_fields: [
        "id",
        "source_id",
        "batch_id",
        "site_code",
        "iata",
        "ap_count",
        "up_count",
        "down_count",
        "wlc_count",
        "server_group",
        "cluster",
        "aaa_profile",
        "all_server_groups",
        "controller_names",
        "controllers"
      ],
      numeric_fields: ["ap_count", "up_count", "down_count", "wlc_count"],
      array_fields: ["all_server_groups", "controller_names", "controllers"],
      downsample: false
    },
    %{
      id: "wifi_aps",
      label: "WiFi Access Points",
      route: "/spatial/wifi-map",
      default_time: "last_24h",
      default_sort_field: "collection_timestamp",
      default_sort_dir: "desc",
      default_filter_field: "hostname",
      filter_fields: @wifi_device_filter_fields ++ ["vendor_name", "vendor"],
      numeric_fields: @wifi_device_numeric_fields,
      downsample: false
    },
    %{
      id: "wifi_controllers",
      label: "WiFi Controllers",
      route: "/spatial/wifi-map",
      default_time: "last_24h",
      default_sort_field: "collection_timestamp",
      default_sort_dir: "desc",
      default_filter_field: "hostname",
      filter_fields: @wifi_device_filter_fields ++ ["aos_version", "base_mac", "psu_status"],
      numeric_fields: @wifi_device_numeric_fields,
      downsample: false
    },
    %{
      id: "wifi_radius_groups",
      label: "WiFi RADIUS Groups",
      route: "/spatial/wifi-map",
      default_time: "last_24h",
      default_sort_field: "collection_timestamp",
      default_sort_dir: "desc",
      default_filter_field: "server_group",
      filter_fields: [
        "id",
        "source_id",
        "batch_id",
        "controller_device_uid",
        "site_code",
        "iata",
        "site_name",
        "region",
        "latitude",
        "lat",
        "longitude",
        "lon",
        "lng",
        "controller_alias",
        "controller",
        "aaa_profile",
        "server_group",
        "cluster",
        "all_server_groups",
        "status"
      ],
      numeric_fields: @wifi_device_numeric_fields,
      array_fields: ["all_server_groups"],
      downsample: false
    },
    %{
      id: "wifi_fleet_history",
      label: "WiFi Fleet History",
      route: "/spatial/wifi-map",
      default_time: "",
      default_sort_field: "build_date",
      default_sort_dir: "desc",
      default_filter_field: "build_date",
      filter_fields: [
        "source_id",
        "batch_id",
        "build_date",
        "date",
        "ap_total",
        "count_2xx",
        "count_3xx",
        "count_4xx",
        "count_5xx",
        "count_6xx",
        "count_7xx",
        "count_other",
        "count_ap325",
        "pct_6xx",
        "pct_legacy",
        "site_count"
      ],
      numeric_fields: [
        "ap_total",
        "count_2xx",
        "count_3xx",
        "count_4xx",
        "count_5xx",
        "count_6xx",
        "count_7xx",
        "count_other",
        "count_ap325",
        "pct_6xx",
        "pct_legacy",
        "site_count"
      ],
      downsample: false
    },
    %{
      id: "wifi_site_references",
      label: "WiFi Site References",
      route: "/spatial/wifi-map",
      default_time: "",
      default_sort_field: "updated_at",
      default_sort_dir: "desc",
      default_filter_field: "site_code",
      filter_fields: [
        "source_id",
        "site_code",
        "iata",
        "name",
        "site_name",
        "site_type",
        "region",
        "latitude",
        "lat",
        "longitude",
        "lon",
        "lng",
        "reference_hash"
      ],
      numeric_fields: ["latitude", "lat", "longitude", "lon", "lng"],
      downsample: false
    },
    %{
      id: "alerts",
      label: "Alerts",
      route: "/alerts",
      default_time: "last_7d",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "title",
      filter_fields: [
        "title",
        "status",
        "severity",
        "source_type",
        "source_id",
        "device_uid",
        "agent_uid"
      ],
      downsample: false
    },
    %{
      id: "logs",
      label: "Logs",
      route: "/logs",
      default_time: "last_7d",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "message",
      filter_fields: ["uid", "gateway_id", "agent_id", "severity", "source", "message"],
      downsample: false
    },
    %{
      id: "flows",
      label: "Flows",
      route: "/flows",
      default_time: "last_24h",
      default_sort_field: "time",
      default_sort_dir: "desc",
      default_filter_field: "src_endpoint_ip",
      filter_fields: [
        "src_endpoint_ip",
        "src_ip",
        "dst_endpoint_ip",
        "dst_ip",
        "src_endpoint_port",
        "src_port",
        "dst_endpoint_port",
        "dst_port",
        "protocol_group",
        "protocol_name",
        "protocol_num",
        "direction",
        "app",
        "sampler_address",
        "src_country_iso2",
        "dst_country_iso2",
        "src_cidr",
        "dst_cidr",
        "as_path",
        "bgp_communities"
      ],
      # Fields backed by array columns - builder will always use list syntax for these
      array_fields: ["as_path", "bgp_communities"],
      downsample: true,
      default_bucket: "5m",
      default_agg: "sum",
      default_value_field: "bytes_total",
      default_series_field: "app",
      value_fields: [
        "bytes_total",
        "packets_total",
        "bytes_in",
        "bytes_out",
        "packets_in",
        "packets_out"
      ],
      series_fields: [
        "protocol_group",
        "protocol_name",
        "app",
        "dst_port",
        "src_ip",
        "dst_ip",
        "direction",
        "sampler_address",
        "exporter_name",
        "in_if_name",
        "out_if_name",
        "src_cidr",
        "dst_cidr"
      ]
    },
    %{
      id: "services",
      label: "Services",
      route: "/services",
      default_time: "last_7d",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "service_type",
      filter_fields: [
        "uid",
        "service_id",
        "gateway_id",
        "service_type",
        "service_status",
        "name",
        "port",
        "protocol"
      ],
      downsample: false
    },
    %{
      id: "mtr_traces",
      label: "MTR Traces",
      route: "/diagnostics/mtr",
      default_time: "",
      default_sort_field: "time",
      default_sort_dir: "desc",
      default_filter_field: "target",
      filter_fields: [
        "target",
        "target_ip",
        "agent_id",
        "protocol",
        "check_name",
        "device_id",
        "target_reached",
        "error"
      ],
      boolean_fields: ["target_reached"],
      downsample: false
    },
    %{
      id: "interfaces",
      label: "Interfaces",
      route: "/interfaces",
      default_time: "last_7d",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "uid",
      filter_fields: [
        "uid",
        "device_id",
        "if_name",
        "if_index",
        "mac",
        "ip_addresses",
        "admin_status",
        "oper_status",
        "favorited",
        "metrics_enabled"
      ],
      boolean_fields: ["favorited", "metrics_enabled"],
      downsample: false
    },
    %{
      id: "timeseries_metrics",
      label: "Timeseries Metrics",
      route: "/dashboard",
      default_time: "last_24h",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "metric_name",
      filter_fields: [
        "gateway_id",
        "agent_id",
        "metric_name",
        "metric_type",
        "uid",
        "target_device_ip",
        "partition",
        "if_index"
      ],
      downsample: true,
      default_bucket: "5m",
      default_agg: "avg",
      default_series_field: "metric_name",
      series_fields: [
        "metric_name",
        "metric_type",
        "uid",
        "gateway_id",
        "agent_id",
        "partition",
        "target_device_ip",
        "if_index"
      ]
    },
    %{
      id: "snmp_metrics",
      label: "SNMP Metrics",
      route: "/dashboard",
      default_time: "last_24h",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "metric_name",
      filter_fields: [
        "gateway_id",
        "agent_id",
        "metric_name",
        "uid",
        "device_id",
        "target_device_ip",
        "partition",
        "if_index"
      ],
      downsample: true,
      default_bucket: "5m",
      # Use rate aggregation by default for SNMP metrics (byte counters need rate calculation)
      default_agg: "rate",
      default_series_field: "metric_name",
      series_fields: [
        "metric_name",
        "uid",
        "gateway_id",
        "agent_id",
        "partition",
        "target_device_ip",
        "if_index"
      ]
    },
    %{
      id: "rperf_metrics",
      label: "rPerf Metrics",
      route: "/dashboard",
      default_time: "last_24h",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "metric_name",
      filter_fields: [
        "gateway_id",
        "agent_id",
        "metric_name",
        "uid",
        "target_device_ip",
        "partition",
        "if_index"
      ],
      downsample: true,
      default_bucket: "5m",
      default_agg: "avg",
      default_series_field: "metric_name",
      series_fields: [
        "metric_name",
        "uid",
        "gateway_id",
        "agent_id",
        "partition",
        "target_device_ip",
        "if_index"
      ]
    },
    %{
      id: "cpu_metrics",
      label: "CPU Metrics",
      route: "/dashboard",
      default_time: "last_24h",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "uid",
      filter_fields: [
        "gateway_id",
        "agent_id",
        "host_id",
        "uid",
        "partition",
        "cluster",
        "label",
        "core_id"
      ],
      downsample: true,
      default_bucket: "5m",
      default_agg: "avg",
      default_series_field: "uid",
      series_fields: [
        "uid",
        "host_id",
        "gateway_id",
        "agent_id",
        "core_id",
        "label",
        "cluster",
        "partition"
      ]
    },
    %{
      id: "memory_metrics",
      label: "Memory Metrics",
      route: "/dashboard",
      default_time: "last_24h",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "uid",
      filter_fields: ["gateway_id", "agent_id", "host_id", "uid", "partition"],
      downsample: true,
      default_bucket: "5m",
      default_agg: "avg",
      default_series_field: "uid",
      series_fields: ["uid", "host_id", "gateway_id", "agent_id", "partition"]
    },
    %{
      id: "disk_metrics",
      label: "Disk Metrics",
      route: "/dashboard",
      default_time: "last_24h",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "uid",
      filter_fields: [
        "gateway_id",
        "agent_id",
        "host_id",
        "uid",
        "partition",
        "mount_point",
        "device_name"
      ],
      downsample: true,
      default_bucket: "5m",
      default_agg: "avg",
      default_series_field: "mount_point",
      series_fields: [
        "uid",
        "host_id",
        "gateway_id",
        "agent_id",
        "partition",
        "mount_point",
        "device_name"
      ]
    },
    %{
      id: "process_metrics",
      label: "Process Metrics",
      route: "/dashboard",
      default_time: "last_24h",
      default_sort_field: "timestamp",
      default_sort_dir: "desc",
      default_filter_field: "name",
      filter_fields: [
        "gateway_id",
        "agent_id",
        "host_id",
        "uid",
        "partition",
        "name",
        "pid",
        "status"
      ],
      downsample: true,
      default_bucket: "5m",
      default_agg: "avg",
      default_series_field: "name",
      series_fields: [
        "uid",
        "host_id",
        "gateway_id",
        "agent_id",
        "partition",
        "name",
        "pid",
        "status"
      ]
    },
    %{
      id: "interface_settings",
      label: "Interface Settings",
      route: "/devices",
      default_time: "",
      default_sort_field: "updated_at",
      default_sort_dir: "desc",
      default_filter_field: "device_id",
      filter_fields: [
        "device_id",
        "interface_uid",
        "favorited",
        "metrics_enabled",
        "threshold_enabled",
        "tags"
      ],
      boolean_fields: ["favorited", "metrics_enabled", "threshold_enabled"],
      downsample: false
    }
  ]

  def entities, do: @entities

  def entity(id) when is_binary(id) do
    Enum.find(@entities, &(&1.id == id)) ||
      %{
        id: id,
        label: String.capitalize(id),
        default_time: "",
        default_sort_field: "timestamp",
        default_sort_dir: "desc",
        default_filter_field: "",
        filter_fields: [],
        downsample: false
      }
  end

  def entity(_), do: entity("devices")
end
