name: Build ServiceRadar Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libc6-dev libsqlite3-dev

      - name: Build packages
        run: |
          ./buildAll.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: serviceradar-packages
          path: release-artifacts/*.deb