# .github/workflows/deploy-pages.yml
name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'  # Enable pnpm caching
          cache-dependency-path: 'docs/pnpm-lock.yaml'

      - name: Install pnpm
        run: npm install -g pnpm  # Install pnpm globally

      - name: Install Docusaurus dependencies
        working-directory: ./docs
        run: pnpm install  # Use --frozen-lockfile once lock file is synced

      - name: Build Docusaurus site
        working-directory: ./docs
        run: pnpm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4