name: OCaml Lint

on:
  pull_request:
    paths:
      - 'ocaml/**'
      - '.github/workflows/ocaml-lint.yml'

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use OCaml 5.2
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.0
          dune-cache: true

      - name: Install ocamlformat
        run: opam install ocamlformat -y

      - name: Check formatting with dune @fmt
        working-directory: ocaml
        run: opam exec -- dune build @fmt
