# .github/workflows/release.yml
name: Release HomeMon Packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build agent package
        run: |
          chmod +x ./setup-deb-agent.sh
          ./setup-deb-agent.sh
          mv -f homemon-agent_1.0.0.deb homemon-agent_$(echo $GITHUB_REF_NAME | sed 's/^v//').deb

      - name: Build poller package
        run: |
          chmod +x ./setup-deb-poller.sh
          ./setup-deb-poller.sh
          mv -f homemon-poller_1.0.0.deb homemon-poller_$(echo $GITHUB_REF_NAME | sed 's/^v//').deb

      - name: Build cloud package
        run: |
          chmod +x ./setup-deb-cloud.sh
          ./setup-deb-cloud.sh
          mv -f homemon-cloud_1.0.0.deb homemon-cloud_$(echo $GITHUB_REF_NAME | sed 's/^v//').deb

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            homemon-agent_*.deb
            homemon-poller_*.deb
            homemon-cloud_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}