# Copyright 2025 Carver Automation Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# .github/workflows/release.yml
name: Release ServiceRadar Packages
on:
  release:
    types: [created]
permissions:
  contents: write
  packages: write
jobs:
  build-packages:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Build packages
        run: |
          ./scripts/setup-deb-agent.sh
          ./scripts/setup-deb-poller.sh
          ./scripts/setup-deb-cloud.sh
          ./scripts/setup-deb-web.sh
          ./scripts/setup-deb-dusk-checker.sh
          ./scripts/setup-deb-snmp-checker.sh
      - name: List Artifacts (for debugging)
        run: ls -al ./release-artifacts
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-containers:
    runs-on: ubuntu-latest
    needs: build-packages
    env:
      VERSION: ${{ github.ref_name }}
      KO_DOCKER_REPO: ghcr.io/carverauto/serviceradar
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'
      - name: Setup ko
        uses: ko-build/setup-ko@v0.8
      - name: Build web UI
        run: ./scripts/build-web.sh
      - name: Move web artifacts
        run: |
          mkdir -p pkg/cloud/api/web/
          cp -r web/dist pkg/cloud/api/web/
          mkdir -p cmd/cloud/.kodata
          cp -r web/dist cmd/cloud/.kodata/web
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container images
        run: |
          # Set up ko repository
          export KO_DOCKER_REPO=ghcr.io/carverauto/serviceradar
          
          # Build and push container images for all components
          GOFLAGS="-tags=containers" ko build \
            --platform=linux/amd64,linux/arm64 \
            --base-import-paths \
            --tags=${VERSION},latest \
            --bare \
            --image-refs=image-refs.txt \
            ./cmd/agent \
            ./cmd/poller \
            ./cmd/cloud \
            ./cmd/checkers/dusk \
            ./cmd/checkers/snmp