# Copyright 2025 Carver Automation Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# .github/workflows/release.yml

name: Release ServiceRadar Packages
on:
  release:
    types: [created]
permissions:
  contents: write
  packages: write
jobs:
  build-deb-packages:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential protobuf-compiler jq
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Build DEB packages
        run: |
          # Build all DEB packages using the unified script
          ./scripts/setup-package.sh --type=deb --all
      - name: List Artifacts (for debugging)
        run: ls -al ./release-artifacts
      - name: Upload DEB Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-rpm-packages:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Create output directory
        run: |
          mkdir -p ./release-artifacts/rpm
      - name: Build all RPM packages
        run: |
          # Build all RPM packages using the unified script
          ./scripts/setup-package.sh --type=rpm --all
      - name: List RPM Artifacts (for debugging)
        run: |
          find ./release-artifacts/rpm -type f -name "*.rpm" | sort
      - name: Upload RPM Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-artifacts/rpm/*/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}