# .github/workflows/release.yml
name: Release ServiceRadar Packages
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Build packages
        run: |
          ./scripts/setup-deb-agent.sh
          ./scripts/setup-deb-poller.sh
          ./scripts/setup-deb-cloud.sh
          ./scripts/setup-deb-dusk-checker.sh
          ./scripts/setup-deb-snmp-checker.sh
      - name: List Artifacts (for debugging)
        run: ls -al ./release-artifacts
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
