name: swiftlint
on: [push, pull_request]
permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  swiftlint:
    name: swiftlint
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup bazel
        uses: bazelbuild/setup-bazelisk@v3
      - name: swiftlint (bazel)
        run: bazel run -c opt //:swiftlint_lint
