# .github/workflows/tests-web.yml
name: Web Tests
on: [push]
permissions:
  contents: write

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run JS Tests
        run: |
          cd web && npm install && npm run test