namespace:
  create: false
  name: sigstore-system

config:
  format: json
  contents:
    OIDCIssuers:
      - IssuerURL: https://code.carverauto.dev/api/actions
        ClientID: sigstore
        Type: uri
        IssuerClaim: iss
        SubjectDomain: code.carverauto.dev
    MetaIssuers:
      - Issuer: https://code.carverauto.dev/api/actions
        ClientID: sigstore

server:
  secret: fulcio-server-secret
  args:
    certificateAuthority: fileca
    port: 5555
    grpcPort: 5554
    ct_log_url: http://ctlog.ctlog-system.svc
    disable_ct_log: false
  ingress:
    http:
      enabled: false
    grpc:
      enabled: false
  service:
    type: ClusterIP

createcerts:
  enabled: false

ctlog:
  enabled: true
  namespace:
    create: true
    name: ctlog-system
